### ISSUE TITLE
[Bug/Question] Project Configuration 

### ISSUE THREAD

**Issue by jonnyforestGIS** [opengisch/qfieldsync#106]
Hi guys,
i'm using this versions:
**OS:** Windows 64-bits
**QGIS:** 3.4.4 Madeira 64-bits (OSGeo Installer)
**QFielsync:** 3.1.1

I upgrade to version 3.1.1. and when I try to click in the project configuration, the plugin give me the following traceback:

```python
WARNING    Traceback (most recent call last):
              File "C:/Users/jfgaspar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\qfield_sync.py", line 258, in show_project_configuration_dialog
              dlg = ProjectConfigurationDialog(self.iface, self.iface.mainWindow())
              File "C:/Users/jfgaspar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\dialogs\project_configuration_dialog.py", line 69, in __init__
              self.multipleToggleButton.setMenu(self.toggle_menu)
             AttributeError: 'ProjectConfigurationDialog' object has no attribute 'multipleToggleButton'

```

After I reboot QGIS the problem apparently disappear. Is this behavior normal?

Cheers,
João

**Comment by m-kuhn** [comment]
Not sure what happened. @3nids do you have an idea?
But if it disappears after a restart, I am not sure it's worth looking into it.

**Comment by jonnyforestGIS** [comment]
Ok, @m-kuhn. I only flag it because this can be reported for other users. Please be free to close this issue or  I can close it as well.

**Comment by m-kuhn** [comment]
@jonnyforestGIS pull requests to fix this issue will happily be accepted and we can also send you an offer to fix this problem.

**Comment by jonnyforestGIS** [comment]
@m-kuhn sorry I think I'm explained in the wrong way... What I want to say is that I can close this issue to reduce the noise if necessary.  What I want to say with "flag it" if others users have this experience, they can check this. Once again I'm sorry for this situation...

**Comment by 3nids** [comment]
I tried with a freshly installed plugin and I cannot reproduce. Could it be a compiled file left over from the previous plugin version?

**Comment by jonnyforestGIS** [comment]
@3nids, 
what your saying makes sense because I'm keeping the plugin since their early versions in QGIS 3.x and only did upgrades.  I will close this issue. Sorry for the noise. 
Regards,
João
