### ISSUE TITLE
Layer visibility lost

### ISSUE THREAD

**Issue by saemiw** [opengisch/qfieldsync#107]
In QGIS you can define if a layer is visible or not. If I copy a project to QField this setting (is layer xy visible or not) is kept. If I use Qfieldsync instead all layers are shown. The visibility settings are lost. It would of course be nice to keep the setting shown in QGIS.

I used 
QGIS 3.4.4.
QField 1.0.0-rc3
QFieldsync 3.1.1

**Comment by signedav** [comment]
Do you use offline editing for this or just "copy" on QFieldSync?

**Comment by saemiw** [comment]
I usually use "offline editing", but I'll try to reproduce the bug tomorrow again.

**Comment by m-kuhn** [comment]
It's actually an issue in QGIS offline editing. Pull request pending.
https://github.com/qgis/QGIS/pull/9371

**Comment by zersorger** [comment]
I've got the same issue, eg. with transperency settings. Also, if I change layer colours in QGIS, the new colours should also appear in Qfield after I synced it, right? For me only a few colours are correct and most of the layers have random colours.

**Comment by saemiw** [comment]
@zersorger I did not observe that with QGIS 3.4.4, QField 1.0.0-rc5 and QFieldSync 3.1.3. What are the versions you are using?

**Comment by 3nids** [comment]
closing since this has been fixed upstream.

@zersorger feel free to open an issue for the specific issue you mention
