### ISSUE TITLE
Paths are not relative

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QFieldSync#11]
I tried to export a project (with a single spatialite layer). The path is not saved relative unfortunately.

      <datasource>dbname='/home/mku/numerisation_poubelles_qfield_2/data.sqlite' table="poubelles20160308115916478" (Geometry) sql=</datasource>

I checked the project properties and there, the paths are set to "relative"

**Comment by carolinux** [comment]
I had looked at this - for me the datasource paths to the data.sqlite created are saved relative, ie:
``` <datasource>dbname='./data.sqlite' table="gt1__offline_20160714131039629" (Geometry) sql=</datasource>
```
But, I do get this:
```
    <OfflineEditingPlugin>
      <OfflineDbPath type="QString">/home/carolinux/Documents/project_with_postgis_connection_offline/data.sqlite</OfflineDbPath>
    </OfflineEditingPlugin>
```

**Comment by m-kuhn** [comment]
Should be fixed since
https://github.com/qgis/QGIS/commit/e4a69234d41e84986d3f6f58847ffff30bd0fcd0

**Comment by carolinux** [comment]
@m-kuhn You are referring to the original problem as being fixed, yes?

**Comment by m-kuhn** [comment]
No, the one your reported.

**Comment by carolinux** [comment]
I tried with the latest version of qgis (master), seems to work. I have Ubuntu.

**Comment by carolinux** [comment]
Ok, I think I got something. In the version of QFieldSync I had in my own repo this worked, but after the refactoring on your end, it  doesn't. Probably some slight change was introduced, will investigate.

**Comment by carolinux** [comment]
Scratch that, now I can't get it to work again either with the commit that was working before.

**Comment by carolinux** [comment]
It looks like a race condition as well. A work around that looks reasonable to me is to save the project in the new location before converting to offline. Then whatever happens under the hood can understand that it's supposed to use relative paths.

**Comment by m-kuhn** [comment]
Sounds good

**Comment by m-kuhn** [comment]
Nice, with the latest update no more crashes and no more absolute paths.

Remaining problem: shapefiles are made offline (copied to spatialite) and also moved to the destination folder. They should not be put into offline mode.

**Comment by carolinux** [comment]
so they should just be copied to the destination folder. Ok!

**Comment by m-kuhn** [comment]
At the moment they are copied to the folder but this copy is not actually used by the project.

**Comment by carolinux** [comment]
we can close this, I suppose
