### ISSUE TITLE
Layerstyles are lost in offlineproject

### ISSUE THREAD

**Issue by soester** [opengisch/qfieldsync#111]
I have a project with multiple layerstyles for one layer. They are used in different visibility presets (used like in demo project ['offline_bees.qgs'](https://github.com/opengisch/QField/blob/master/resources/demo_projects/offline_bees.qgs)).

If creating an offline project only the default style is exported.

Is this related to core offline project plugin or qfieldsync?

Layerstyles in combination with visibility presets are very usefull, specially in qfield with limited possibilities.

**Comment by soester** [comment]
To reproduce:
[live_qfield_users_survey_layerstyle.qgs.qgz.zip](https://github.com/opengisch/qfieldsync/files/4716316/live_qfield_users_survey_layerstyle.qgs.qgz.zip)
user survey with layer style and visibility presets added.

[live_qfield_users_survey_layerstyle_offline.zip](https://github.com/opengisch/qfieldsync/files/4716330/live_qfield_users_survey_layerstyle_offline.zip)
generated offline-project with qfieldsync

Setup:
qfieldsync 3.1.8
MacOSX 10.13.6

QGIS version | 3.12.3-București | QGIS code revision | 8234261527
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS High Sierra (10.13)
Active python plugins | QgisModelBaker; profiletool; DataPlotly; changeDataSource; quick_map_services; SRTM-Downloader; qfieldsync; pg_history_viewer; swiss_locator; timemanager; processing; db_manager

**Comment by soester** [comment]
@m-kuhn would this be a big thing to fix?
we are currently setting up new project templates and would love to use layerstyles.

**Comment by m-kuhn** [comment]
@soester is it possible to send me a demo project or is there too much interdependencies with the original database?

**Comment by soester** [comment]
@m-kuhn you could use the demo-project mentioned above
> To reproduce:
> [live_qfield_users_survey_layerstyle.qgs.qgz.zip](https://github.com/opengisch/qfieldsync/files/4716316/live_qfield_users_survey_layerstyle.qgs.qgz.zip)
> user survey with layer style and visibility presets added.
> 
> [live_qfield_users_survey_layerstyle_offline.zip](https://github.com/opengisch/qfieldsync/files/4716330/live_qfield_users_survey_layerstyle_offline.zip)
> generated offline-project with qfieldsync (without layerstyles...)

after exporting with qfieldsync the ```<map-layer-style name="single">``` is not listed in the offline project .qgs

**Comment by m-kuhn** [comment]
ouch, thanks :D

**Comment by m-kuhn** [comment]
Upstream pull request (QGIS) pending approval
If everything goes well this should be fixed in 3.14 and hopefully next 3.10 point release too.
