### ISSUE TITLE
Sync don't find data

### ISSUE THREAD

**Issue by kagou** [opengisch/qfieldsync#114]
When i use plugin under Qgis to sync from Qfield i get an error because the qgis extension search for a "data.sqlite". But Qfield have generated a "data.gpkg". 

Une erreur est survenue lors de l'éxécution du code Python: 

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/direction/Desktop/Cardet Export\\data.sqlite' 
Traceback (most recent call last):
  File "C:/Users/direction/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\dialogs\synchronize_dialog.py", line 65, in start_synchronization
    current_import_file_checksum = import_file_checksum(qfield_folder)
  File "C:/Users/direction/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\utils\file_utils.py", line 89, in import_file_checksum
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/direction/Desktop/Cardet Export\\data.sqlite'

Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.6.3-Noosa Noosa, 0c5774c068 

Chemin Python :
C:/OSGEO4~1/apps/qgis/./python
C:/Users/direction/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/direction/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/direction/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\direction\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cadastre/forms
C:/Users/DIRECT~1/AppData/Local/Temp/tmpq7r_tfu7

**Comment by simone100** [comment]
The identical problem of me and other user and I don't know how to solve with my version 3.4. I can do nothing with qfield, it is impossible to syncronyze the changes of the project in the field! 
https://github.com/opengisch/QField/issues/590#issuecomment-503552120

**Comment by simone100** [comment]
I tried even with other version of qgis and with other computers. The same issue appears!

**Comment by coastalrocket** [comment]
Seen on QGIS 3.4.6.

**Comment by gossforest** [comment]
I am running into this error as well. Qfield is looking for the .sqlite data and mine is in a .gpkg and has a custom name. Has anyone found a fix for this? I am using Qgis 3.6.3

**Comment by m-kuhn** [comment]
Is someone able to install the following file and check if it solves the issue?
Thanks

[qfieldsync.zip](https://github.com/opengisch/qfieldsync/files/3385147/qfieldsync.zip)

**Comment by henri-hulski** [comment]
I had the same problem with the difference, that QField doesn't created data.gpkg, but updated the original gpkg file ('bieszczady.gpkg) in place.
Using QGIS 3.8.0 on Linux.
When using the above ZIP file everything works fine beside getting the warning
"The project you import seems not to be an offline project."
But all data is imported.
