### ISSUE TITLE
Representations for checkbox are lost after project export

### ISSUE THREAD

**Issue by rbovard** [opengisch/qfieldsync#115]
I have a boolean field in my original project (data is stored in a geopackage) and when I export the project with QFieldSync, the representations for checkbox are empty (was originally automatically set to `TRUE` and `FALSE` due to the source I guess).

I need to manually set them to `true` and `false` to make my checkbox work in QField.

QGIS 3.4.5 / QFieldSync 3.1.3

**Comment by m-kuhn** [comment]
This might be solved in current master (see https://issues.qgis.org/issues/18532) but I didn't check it.

**Comment by varrieta** [comment]
Same issue with data stored in postgis layer. 

QGIS 3.8 / QFieldSync 3.1.3

**Comment by 3nids** [comment]
closing for lack of feedback
also, related PR in QGIS: https://github.com/qgis/QGIS/pull/33792
