### ISSUE TITLE
Sync not working with QGIS 3.4.8 LTR but with 3.4.4

### ISSUE THREAD

**Issue by saemiw** [opengisch/qfieldsync#116]
I use QGIS 3.4.4 and QFieldsync 3.1.3 to set a geopackage layer offline and synchronise data recorded with QField 1.0.3 back to my QGIS project. Updates I made on one field that uses value maps are synchronised perfectly.

On another computer I have the same setting, same project but QGIS 3.4.8 (LTR) installed. When I set my project offline and try to synchronise updates after fieldwork. Some updates are lost (not synchronised). You can see them on the offline_version but not after synchronising.

I'll come back with a sample project.

**Comment by m-kuhn** [comment]
@saemiw any progress on the sample project?

**Comment by saemiw** [comment]
not yet (found no time to investigate more, but will do so in due time).

**Comment by saemiw** [comment]
I am not able to reproduce it with QGIS 3.4.12 (and don't have too much time too look deeper into it). So lets close this issue.
