### ISSUE TITLE
Error when click on projectconfiguration

### ISSUE THREAD

**Issue by j-lippmann** [opengisch/qfieldsync#118]
`Ein Fehler trat bei der Ausführung von Python-Code auf: 

AttributeError: 'LayerSource' object has no attribute 'name' 
Traceback (most recent call last):
  File "C:/Users/Jan/AppData/Roaming/QGIS/QGIS3\profiles\testplugin/python/plugins\qfieldsync\qfield_sync.py", line 258, in show_project_configuration_dialog
    dlg = ProjectConfigurationDialog(self.iface, self.iface.mainWindow())
  File "C:/Users/Jan/AppData/Roaming/QGIS/QGIS3\profiles\testplugin/python/plugins\qfieldsync\dialogs\project_configuration_dialog.py", line 77, in __init__
    self.reloadProject()
  File "C:/Users/Jan/AppData/Roaming/QGIS/QGIS3\profiles\testplugin/python/plugins\qfieldsync\dialogs\project_configuration_dialog.py", line 139, in reloadProject
    unsuppoerted_layers_text += '
' + '' + layer.name + ': ' + layer.warning
AttributeError: 'LayerSource' object has no attribute 'name'

Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.8.0-Zanzibar Zanzibar, 11aff65f10 

Python-Pfad:
C:/OSGeo4W64/apps/qgis/./python
C:/Users/Jan/AppData/Roaming/QGIS/QGIS3\profiles\testplugin/python
C:/Users/Jan/AppData/Roaming/QGIS/QGIS3\profiles\testplugin/python/plugins
C:/OSGeo4W64/apps/qgis/./python/plugins
C:\OSGeo4W\bin
C:\OSGeo4W64\bin\python37.zip
C:\OSGeo4W64\apps\Python37\DLLs
C:\OSGeo4W64\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGeo4W64\apps\Python37
C:\OSGeo4W64\apps\Python37\lib\site-packages
C:\OSGeo4W64\apps\Python37\lib\site-packages\setuptools-39.1.0-py3.7.egg
C:\OSGeo4W64\apps\Python37\lib\site-packages\pip-10.0.1-py3.7.egg
C:\OSGeo4W64\apps\Python37\lib\site-packages\win32
C:\OSGeo4W64\apps\Python37\lib\site-packages\win32\lib
C:\OSGeo4W64\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Jan/AppData/Roaming/QGIS/QGIS3\profiles\testplugin/python
C:\Users\Jan\AppData\Roaming\QGIS\QGIS3\profiles\testplugin\python\plugins\mmqgis/forms
.`

**Comment by m-kuhn** [comment]
What kind of layers are in there?
