### ISSUE TITLE
sync not working UnicodeEncodeError

### ISSUE THREAD

**Issue by MeriemAchir** [opengisch/qfieldsync#119]
Hey ! 
i'm trying to import my qfield project to qgis but I get this error : 
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 30: ordinal not in range(128)
And I don't know how to resolve it.
qgis version : 2.8.9
Thank you.

**Comment by m-kuhn** [comment]
Hi,
not sure what exactly is happening, but first thing to try is updating to QGIS 3.4 or newer.
Thank you.
