### ISSUE TITLE
Crash with shapefiles

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QFieldSync#12]
Trying to convert a project including shapefiles to an offline project crashes here.

It looks like the offline editing plugin has finished its job and then an attempt is made to copy shapefiles.

The plugin tries to access the source of a layer which has been deleted.

Here is the (python part) of the stacktrace:

```
qfieldsync/utils/data_source_utils.py\", line 24, in change_layer_data_source
>~"    layer.writeLayerXML(XMLMapLayer, XMLDocument)\n"
qfieldsync/utils/export_offline_utils.py\", line 34, in handle_shpfiles
>~"    change_layer_data_source(shpfile_layer, new_file_path)\n"
qfieldsync/utils/export_offline_utils.py\", line 58, in offline_convert
>~"    handle_shpfiles(dataPath, shpfile_layers)\n"
qfieldsync/dialogs/push_dialog.py\", line 146, in push_project
>~"    export_folder=export_folder)\n"
```

**Comment by carolinux** [comment]
Maybe I am using a different version of the offline plugin because "it
works on my machine". Which commit or (version of qgis) should I sync at?

**Comment by m-kuhn** [comment]
Using master right now.

The layers are sent through the offline editing plugin (is this required for shapefiles?) and at the end removed by [this line](https://github.com/qgis/QGIS/blob/master/src/core/qgsofflineediting.cpp#L150-L151]) and I assume the plugin tries to subsequently query the removed layer for the source...


Update:

While debugging with a breakpoint, it suddenly didn't crash but gave me a "bad_alloc" and I ended up with an offline project. Maybe caused by some kind of a race condition?

You need to make sure that you don't use any layer references after running `convertToOffline()` which have been obtained before and sent through offline editing.

**Comment by carolinux** [comment]
Changing the order of the operations (see commit above) should fix this issue, I believe

**Comment by m-kuhn** [comment]
Sounds reasonable, yes!
