### ISSUE TITLE
worldfile is not copied along

### ISSUE THREAD

**Issue by 3nids** [opengisch/qfieldsync#123]
world files are not copied along rasters.

this would require an extra handling in `core.LayerSource.copy`.

There is no information in QGIS (datasource) about a worldfile apparently.

We either need to use GDAL bindings (tricky?) or use some testing code like (both with `w` at end of extension + wld extension):
```
  QString myWorldFileName = myInfo.absolutePath() + '/' + myInfo.baseName() + '.'
                            + outputSuffix.at( 0 ) + outputSuffix.at( myInfo.suffix().size() - 1 ) + 'w';
```
The latter seems the most reasonnable.

**Comment by m-kuhn** [comment]
Is this (partially) solved by https://github.com/opengisch/qfieldsync/pull/126 ?

**Comment by 3nids** [comment]
almost :)
