### ISSUE TITLE
Use unmodified filepath from preferences

### ISSUE THREAD

**Issue by saemiw** [opengisch/qfieldsync#124]
In the preferences of the qfieldsync plugin you can define where the offline files should be saved to. When you actually use it, the file path is always extended by the QGIS-Project name. We find this not useful and propose to export files directly to the export directory (with out adding a folder).

Filepaths I would want:
![grafik](https://user-images.githubusercontent.com/20398621/66489086-55225300-eaaf-11e9-80e3-e7df8b4f8624.png)

Filepath qfieldsync proposes (added the "red kite" with is the QGIS project name):
![grafik](https://user-images.githubusercontent.com/20398621/66489221-87cc4b80-eaaf-11e9-959c-539422b7d032.png)

**Comment by 3nids** [comment]
The project might have conflicting files.
Currently, the edited gpkg file is always named `data.gpkg`.

What is the drawback of having this in subfolders?

**Comment by saemiw** [comment]
@3nids : I found it not very intuitive that you can specify the directory and in the end the files are not in the directory you specified. I specifically called the export folder always "for tablet" and ended up with something "for tablet/red kite".

But hey its not a crucial thing. If the current behavour is important leave it.

**Comment by 3nids** [comment]
I would see the folder as a package, and that package is actually in the requested folder.
I have no strong opinion, I am just not sure it is worth the risk (conflicts) and effort (renaming of package file, file location).

**Comment by saemiw** [comment]
@3nids wait with becoming active. I'll have to think about it properly and come back to you in 1-2 days ok?

**Comment by 3nids** [comment]
sure, we can also set up a call.

**Comment by saemiw** [comment]
A good alternative for me would be that we leave the subfolder but don't name it according to the QGIS-project name but always call it "for QField". But this is only my opinion...what do other users think?

**Comment by 3nids** [comment]
it has been decided with @saemiw to save the last directory used as a project settings (defaults to global setting if not found)
it might interesting to add a warning if we detect that the same directory is used for several project (maybe looking for other qgs/z files in the end directory)

**Comment by saemiw** [comment]
@3nids I am not fully happy with this implementation yet. The current implementation does save the last path and re-uses this path the next time you want to set a project offline. It does however add the subfolder (name like the qgz-project) everytime. When you set your data offline several times, this leads to fodlers like this: C:\....\test Unterordner\test Unterordner\test Unterordner\test Unterordner. You could of course manually remove the "test Unterordner" everytime but this is painfully und should be handlred by the plugin no? Can you solve this issue?

**Comment by 3nids** [comment]
see #144

**Comment by 3nids** [comment]
@saemiw there is a beta (experimental) version (3.1.7) that can be either tested directly in QGIS master (with the new feature to test experimental plugins) or you can install the zip from here: https://github.com/opengisch/qfieldsync/releases/download/3.1.7/qfield-sync.3.1.7.zip

**Comment by saemiw** [comment]
great stuff, now I am completely happy! Thanks for the fix @3nids
