### ISSUE TITLE
Sync back: Don't show error message for "copy if missing" layers

### ISSUE THREAD

**Issue by saemiw** [opengisch/qfieldsync#127]
With https://github.com/opengisch/qfieldsync/issues/46 the possiblity to copy layers only if they are missing in the destination folder was introduced. We use it very happyily so we don't have to wait long when we deal with large basemap files.

BUT:
When you synchronise data from QField (offline -> "mother project") QFieldSync complains when these layers ("copy if missing" & "copy") are not available together with the other offline data:
![grafik](https://user-images.githubusercontent.com/20398621/66764006-3bb34980-eea9-11e9-8c76-169f705c88b8.png)

I propose for 2 improvement to the plugin:

1. I'd find it better if the"handle bad layers" message was suppressed for layers that have a QFieldSync configuration "copy" or "copy if missing". These layers are available anyway in the mother project and the data in them has not changed. Synchronisation of offline-data does not rely on these layers. 

2. The "mother project" that is opened at the end of the synchronising process should not update the layer of content from the offline qgs-Project file but keep the original layers and only update the data within these layers.

**Comment by suricactus** [comment]
Is this still an issue?

**Comment by suricactus** [comment]
Closed due to lack of feedback.
