### ISSUE TITLE
Check that "project home" is not set

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/qfieldsync#146]
If it is set, we have troubles with images 

https://github.com/opengisch/QField/issues/985

**Comment by RealSniperKing** [comment]
I have the same problem. After reboot my phone, the folder DCIM and pictures are visible in QGGIS project directory.
Do you have any solution for get the pictures without reboot phone ?

**Comment by m-kuhn** [comment]
Wait for https://qfield.cloud/

**Comment by RealSniperKing** [comment]
I don't have permission to use a cloud app for this project.
Apparently, the problem origin is connected to MediaScannerConnection.
[Folder added on Android is not visible via USB](https://stackoverflow.com/questions/13507789/folder-added-on-android-is-not-visible-via-usb)
