### ISSUE TITLE
QGIS freezes then crashes on basemap extent screen when packaging initiated

### ISSUE THREAD

**Issue by samillar94** [opengisch/qfieldsync#147]
## User Feedback

I was trying to package a project for QField - froze on the basemap extent screen

## Report Details

**Crash ID**: [a668f1c5b8a038c2c7d495e265a8760d69919377]('https://github.com/qgis/QGIS/search?q=a668f1c5b8a038c2c7d495e265a8760d69919377&type=Issues')

**Stack Trace**
<pre>
QColorProfile::fromSRgb :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::fillRect :
QRasterPaintEngine::drawImage :
QPainter::drawImage :
QgsShapeburstFillSymbolLayer::renderPolygon :
QgsFillSymbol::renderPolygonUsingLayer :
QgsFillSymbol::renderPolygon :
QgsSymbol::renderFeature :
QgsFeatureRenderer::renderFeature :
QgsVectorLayerJoinInfo::setEditable :
QgsVectorLayerJoinInfo::setEditable :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::staticRender :
QgsLabelingEngine::results :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.1-Bucure?ti
QGIS code revision: 121cc00ff0
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by m-kuhn** [comment]
Thanks for the feedback.
Is this something that happens repeatedly or just a single time?

**Comment by samillar94** [comment]
Hi, yes repeatedly, and no difference in QGIS 3.12.2.
I've found it works fine in 3.10 which I have also installed anyway, so I can work around for now.

**Comment by m-kuhn** [comment]
Does it happen with every project?
I guess this project has joins involved and this could be relevant.
Also, does it happen if you run the "rasterize" algorithm from processing directly?

**Comment by m-kuhn** [comment]
Closed due to lack of feedback.
Please reopen this if it is still an issue.
