### ISSUE TITLE
Tab to define picture naming pattern/path does not show up

### ISSUE THREAD

**Issue by meyerlor** [opengisch/qfieldsync#152]
I just updated to QField Sync 3.1.8 - unfortunately i can not see the tab under "Configure Project" where i could define the picture naming pattern. I m on Windows 10, QGIS version is 3.12.1-București.

The project is configured and pictures appear in QGIS when i open the feature form of an feature which has a foto

**Comment by signedav** [comment]
Hi @meyerlor  
This feature is only available from QGIS 3.14.
