### ISSUE TITLE
Value relation widget not work with Filter expression in Qfield

### ISSUE THREAD

**Issue by fmensio** [opengisch/qfieldsync#155]
Hi everybody,
in the last version of the plugin the issue "Value Relation widget with offline editing" it's resolved, but i've this issue.

Thanks in advance,
Federico Mensio 
Forest and Environment Institute (IPLA), Regione Piemonte

**Issue**
When I set a filter expression in the Value Relation widget, in Qfiled doesn't work, in Qgis is ok.

**Brief description**
I created a custom attributes form where for some fields of a point layer I use a table with code and description to decode in input mode (for users on the field) the value stored in the point layer using the description cointained in the table. I've used the Value Relation with a filter expression where I put the value of a field that is associated (in the table) to the codes and description. (ex "field_to_dec" = 'lithology' or "field_to_dec"='Slope_class')
Both are Postgis tables.
When I edit a field, all the descriptions contained in the decodification table appear (and not only those related to that field), and this for all fields that need a decode.

**Configuration**
Qgis 3.10.6
Qfieldsync 3.1.9
Qfield 1.5.3

![widget] (https://user-images.githubusercontent.com/61933407/83619949-e6898c80-a58c-11ea-984f-2f7a1d5481be.png)

![qfield] (https://user-images.githubusercontent.com/61933407/83619958-ebe6d700-a58c-11ea-8cb2-12f07414746b.png)

![qfield-l] (https://user-images.githubusercontent.com/61933407/83620040-0b7dff80-a58d-11ea-962a-006fd6912942.jpg)

**Comment by m-kuhn** [comment]
Hi @fmensio thank you for getting in touch.

There is an enhancement request for QField https://github.com/opengisch/QField/issues/724, please keep an eye on that or contact us directly if you want to make things move faster.

**Comment by fmensio** [comment]
Just a question, why the QfiledSync plugin, even I set all layers and
tables for offline editing, use online resources? (but the GPKG is
created...)
It's also return this error

Traceback (most recent call last):
              File "../../Library/Application
Support/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/gui/package_dialog.py",
line 118, in package_project
              offline_convertor.convert()
              File "../../Library/Application
Support/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/core/offline_converter.py",
line 189, in convert
              layer_id = project.mapLayersByName(layer_name)[0].id()
             IndexError: list index out of range

**Comment by m-kuhn** [comment]
What is the language that your QGIS is running in?

**Comment by fmensio** [comment]
QGIS 3.10.6
on MacOS 10.13
Python version 2.7.16

**Comment by m-kuhn** [comment]
Can you clarify on the **language** in which QGIS is running?

**Comment by fmensio** [comment]
I think, as all distro of Qgis, is developed in C++ with QT lib 5.12
I hope this is the information you need when you write "*language* in which
QGIS is running"

**Comment by m-kuhn** [comment]
Sorry, I was referring to the language of the user interface: french, english, italian, hindu, swahili etc.

**Comment by fmensio** [comment]
I use Italian or english but the problem Is the same.
I try, later, on Ubuntu with both languages

Il mer 3 giu 2020, 17:57 Matthias Kuhn <notifications@github.com> ha
scritto:

**Comment by m-kuhn** [comment]
We have found an issue on translated versions, but it should have worked reliably on English.
We will be releasing a new, stabilized version in the upcoming minutes, please test with this.

**Comment by fmensio** [comment]
Now it's perfect!!! Thank you so much.
Maybe the next improvement it's to introduce the filter expression on Value
relation widget...
At this moment however I've no sufficient knowledge for develope for it or
to help you.

**Comment by m-kuhn** [comment]
Thank you for the feedback :clap: 

We are looking for sponsors for this feature. Feel free to get in touch to get a quote.
