### ISSUE TITLE
Add option row widget (radio buttons)

### ISSUE THREAD

**Issue by 9ls1** [opengisch/qfieldsync#158]
In addition to fix the missing [**filter option in Value relation** (issue 155)](https://github.com/opengisch/qfieldsync/issues/155), it would be nice to have the **Range**-widget available in QField. 

In addition, would it be possible to include a widget type like "[**Option row**](https://github.com/qgis/QGIS/issues/28284)"?

Perhaps you could initiate a new campaign like the one you had for implementing [native camera integration](https://www.opengis.ch/projects/qfield-love/)?

Thanks for the great work you've done so far with QField.

**Comment by m-kuhn** [comment]
Range widget is implemented and will be released soon. See https://github.com/opengisch/QField/pull/826

I have renamed this issue, so it's targeted to this requirement.
Please feel free to get in touch to get an idea what is needed.

**Comment by suricactus** [comment]
This has been implemented: https://github.com/opengisch/qfieldsync/pull/584
