### ISSUE TITLE
we need a in progress cursor during export/import

### ISSUE THREAD

**Issue by mbernasocchi** [opengisch/QFieldSync#16]
if not it just looks that nothing is happening.

maybe better than a cursor, we could put a progressbar in the main dialog

**Comment by carolinux** [comment]
True, it would be great if you can point me to relevant Qt elements or examples.

**Comment by m-kuhn** [comment]
QProgressBar

QgsOfflineEditing emits signals

https://qgis.org/api/classQgsOfflineEditing.html
