### ISSUE TITLE
Default photo name = bad format

### ISSUE THREAD

**Issue by EulenspiegelTill** [opengisch/qfieldsync#163]
Version QField-Sync: V3.2.0
QGIS: 3.14.0-Pi- Ubuntu 18.04.4 LTS

With the new option **Photo Naming** added, the default name configuration with`'DCIM/$$Layername$$_' ||now() ||'.jpg'` results in a pretty shitty filename. 
`'DCIM/od-messung-messstelle_2020-07-17T09:56:06.jpg'` This Filename is not supported to be saved on our tablets. This result in taking a photo in QField with no error Message, but no photo to be safed.

Would there be the option to add a better default Value? Or a activating/deactivating button, to have the default names like before and only to edit the names when you really want to.

Or to add a default configuration like `'DCIM/$$Layername$$_' ||epoch(now()) ||'.jpg'`

**Comment by signedav** [comment]
I prefer not to have another button there. But I agree that a better default value would be possible.

The suggested expressions looks good.

**Comment by EulenspiegelTill** [comment]
Or a 'DCIM/$$Layername$$_' ||format_date(now(),'yyyyMMddhhmmsszzz') ||'.jpg' which would be more human readable but format specific to european datetime use..
