### ISSUE TITLE
How to attached multiple photos( 5 Photos ) on Qfield with digitize single feature ( point )

### ISSUE THREAD

**Issue by paruljain689** [opengisch/qfieldsync#168]
I have created a qfield project on qgis. when i open the project on qfield, while digitize point, i can attached only single photo. how to enable multiple photo on single point digitize.
Apart from that, How these photos can be transfer to server during live data streaming.

**Comment by VxTedxV** [comment]
> I have created a qfield project on qgis. when i open the project on qfield, while digitize point, i can attached only single photo. how to enable multiple photo on single point digitize.

https://qfield.org/docs/project-management/add-1-n-pictures.html OR configure your attribute table with 5 fields that could each contain 1 photo
