### ISSUE TITLE
QGIS crashes when exporting to offline if an annotation exists

### ISSUE THREAD

**Issue by gacarrillor** [opengisch/qfieldsync#170]
Steps to reproduce:

1. Open a QGIS project.
2. Add a text annotation on the map canvas. 
3. Use the `Package for QField` button with the default options and click on `Create`.
4. As soon as the process finishes, QGIS crashes.

QGIS v3.14.0
QFIeld Sync 3.2.1

_Note: Despite the crash, the offline project seems to be successfully generated._

**Comment by m-kuhn** [comment]
Confirmed.
First assessment: qfieldsync creates and stores the offline project and qgis crashes on reloading the source project. It looks like the fix will be in qgis itself, but needs more investigation.

**Comment by m-kuhn** [comment]
https://github.com/qgis/QGIS/pull/38261/files upstream pull request

**Comment by m-kuhn** [comment]
Fixed upstream, update to QGIS >= 3.10.9, QGIS >= 3.14.15
