### ISSUE TITLE
personal Synchronisation  script

### ISSUE THREAD

**Issue by yacgauryac** [opengisch/qfieldsync#181]
Hello,
i need to write a python script to synchronize package from a command line.
I have modify the synchronize_dialog.py file (cf attached file).
When i run it, 
data.gpkg-shm and data.gpkg-wal are deleted and 
"Opened original project {myOriginalProject}' is printed.
So everything looks ok But the fields i have created on my mobile are not imported in DB.

I work with a layer link to a Postgres DB via PostGIS :
Storage
PostgreSQL database with PostGIS extension
Geometry
Point (Point)

When i run the script (without the INIT code) , i got the same behaviour.
Does someone has any idea to solve this  issue ?
Do i miss something?
many thanks

[mySynchro.zip](https://github.com/opengisch/qfieldsync/files/5217052/mySynchro.zip)

**Comment by m-kuhn** [comment]
Please refer to the support channels (https://qfield.org/docs/support/index.html#support-and-development) for this kind of question.

**Comment by yacgauryac** [comment]
Arg, ok thank you :(
