### ISSUE TITLE
Error while copying

### ISSUE THREAD

**Issue by pcav** [opengisch/QFieldSync#19]
Possibly due to a missing valid input folder, but nevertheless the error should be handled more gracefully:

```
"C:/Users/a444304/.qgis2/python/plugins\qfieldsync\dialogs\push_dialog.py",
line 163, in push_project

export_folder=export_folder)

File
"C:/Users/a444304/.qgis2/python/plugins\qfieldsync\utils\export_offline_utils.py",
line 71, in offline_convert

raise Exception("Converting to offline project did not succeed")

Exception: Converting to offline project did not succeed
```

**Comment by carolinux** [comment]
Hi!

You'd like a more specific message, I suppose? And/or a UI alert instead of an exception?

**Comment by pcav** [comment]
Exactly, possibly with a suggestion for the user.

**Comment by m-kuhn** [comment]
Please test again @pcav

**Comment by m-kuhn** [comment]
This should be resolved with the latest release. Please reopen if the issue persists.
