### ISSUE TITLE
Synchro failed because it synchronise child table before parent.

### ISSUE THREAD

**Issue by SIGISLV** [opengisch/qfieldsync#191]
My problem is that qfield fail to synchronise because of a constrain on my child table. I have a parent table and a child table. When I synchronise I obtain an error from the database relate to a primary key violation.

I am aware of UUID but it's not an option in my case. 

@m-kuhn what do you mean in "Regenerate ids while merging with the database" especially in "QFieldSync needs to be aware of the dependencies and merge parents before children and cache the newly generated ids"  in this [comment](https://github.com/opengisch/qfieldsync/issues/117#issuecomment-502547069)

Have you any idea of how I can manage the order of layer synchronisation ? Or to make qfieldsync synchronise parent before child ?

**Comment by m-kuhn** [comment]
> @m-kuhn what do you mean in "Regenerate ids while merging with the database" especially in "QFieldSync needs to be aware of the dependencies and merge parents before children and cache the newly generated ids" in this comment

If you meant "how can I do this", this was a discussion on a purely conceptual level related to a possible improvement of QFieldSync / offline editing, it's not possible yet. This will need some development to get things working.

**Comment by SIGISLV** [comment]
Ok many thanks for your answer. I will create a process aside to synchronise into my database until the improvement will be release.

Is there any plan for this improvement ? any crowdfunding we can help ?
