### ISSUE TITLE
Possibility to add a layer outside of exported project folder

### ISSUE THREAD

**Issue by samueldurante** [opengisch/qfieldsync#193]
Hi,
I would find it great if we could have the ability to select a new action for heavy raster layer : a sort of "no action" which copy the relative path of layer without copying it.
In case of multiple folders with one project and one data.gpkg in it, it will add the ability to have a layer imported from a folder outside project folders: it will be common for several projects.

Example:
QFIELD_root
     - project1
             - project1_qfield.qgs
             - data.gpkg
     - project2
             - project2_qfield.qgs
             - data.gpkg
     - basemaps
             - basemap1.gpkg
             - basemap2.gpkg
             - basemap3.gpkg

The work around is to reopen the exported project before copying it to mobile device and add maually the basemaps.
I don't now if this implementation is hard or even desired because it breaks the rule "all in one folder"...

Thank you for helping!

**Comment by m-kuhn** [comment]
https://github.com/opengisch/QField/pull/1231

This should be doing what you need already now, see https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#data-sources-settings "localized paths"

Imroved documentation on qfield side would be nice.
