### ISSUE TITLE
Layer id error when copying/pasting styles

### ISSUE THREAD

**Issue by ghtmtt** [opengisch/qfieldsync#197]
Suppose you have saved as `qml` file a layer style with some *complex* widget, like the `Value Relation` that depends on an additional table.

When you create a new project but with the same layers and you import the style, when making the package, the plugin throws some errors because it isn't able to find the additional table. I think the plugin is looking for the layer **id** and not the layer **name**.

**Comment by ghtmtt** [comment]
Yep of course:

```
KeyError: 'legge39_349108d7_23ce_4f68_b976_a1e10e8b175f' 
Traceback (most recent call last):
  File "/home/matteo/.local/share/QGIS/QGIS3/profiles/matteo/python/plugins/qfieldsync/gui/package_dialog.py", line 123, in package_project
    offline_convertor.convert()
  File "/home/matteo/.local/share/QGIS/QGIS3/profiles/matteo/python/plugins/qfieldsync/core/offline_converter.py", line 219, in convert
    if offline_layer.customProperty('remoteSource') == original_layer_info[online_layer_id][0]:
KeyError: 'legge39_349108d7_23ce_4f68_b976_a1e10e8b175f'
```

`legge39` is the original name of the layer in bot project and db. Now, in the project where I imported the `qml` file I get another layer id:

```
v = iface.activeLayer()
v.id()
'legge39_70670b68_bf5a_4eac_aedf_d41c935259e0'
```

**Comment by suricactus** [comment]
Is this still an issue?
