### ISSUE TITLE
QField tab in layer properties is unnecesary wide

### ISSUE THREAD

**Issue by uclaros** [opengisch/qfieldsync#198]
When opening the QField tab in the layer properties window, the tab selector is forced to shrink and displaying icons only, regardless of the total width of the properties window.
![image](https://user-images.githubusercontent.com/11358178/96907852-78465780-14a4-11eb-9a5a-0d392cb33cac.png)

**Comment by m-kuhn** [comment]
Since I am aware that you are more than qualified to help, pull requests will be happily accepted ;)

**Comment by suricactus** [comment]
Thanks for reporting this issue. I have recently fixed noticed and fixed it too, but it is not released yet.

**Comment by uclaros** [comment]
Nice! Thank you both! :)
