### ISSUE TITLE
PostgreSQL Failing when syncronizing back project

### ISSUE THREAD

**Issue by ghtmtt** [opengisch/qfieldsync#199]
I've a table with 13 fields in postgres and many triggers are defined. When exporting the whole project with QFieldSync the triggers are not exported into geopackage (both field and geographic ones, but that's ok, fields and geometries could be applied when syncing back to the DB).

The problem is that when synchronizing back from offline to QGIS (and then to the DB) the import fails. This is the error I get from both QGIS message log and from the server:

`2020-10-23 11:04:44.442 CEST [30851] matteo@pafrt2 STATEMENT:  UPDATE "dati"."pf" SET "sezione"='D',"pf"='056',"label"='offline eitchetta',"complesso"='CALVANA BISENZIO',"localita"='offline loc',"proprieta"='1',"gestore"='16' WHERE`

so it *seems* that the sync query is truncated.

For some other tables (with less columns but that still have triggers) the synchronization works nice.

**Comment by suricactus** [comment]
I am pretty sure this is fixed with QField projects packaged on QGIS 3.22. Please reopen the problem persists.
