### ISSUE TITLE
"fid"-attribute field automaticaly generated. Qfield forces me to fill in a specific number.

### ISSUE THREAD

**Issue by bsturm** [opengisch/qfieldsync#205]
I am not sure where to put his Issue, so i put it in here, too:

During the packaging procedure a new attribute field "fid" is automatically generated.
When in editing mode, Qfield forces me to insert a unique Number into this field, eg. 1, then 11, then 111...

When I don't add a number to this field, it says "Bedingung ungültig".

Deleting and reinstalling Qfield didn't change anything.

### Reproduction Steps:

1. Create new Project
Create layer for offline use, without fid-field.

2. Package for Qfield
3. Copy to Tablet, Open Project, Switch to Editing Mode
4. Add new Point
5. "fid" field exists, input is forced.

### Expected behavior:

The layers should be as i created them, without additional fields added. I should not be forced to enter anything.

### Observed behavior:

see above.

### Screenshots and GIFs

![Screenshot_20201215-154926_QField 1](https://user-images.githubusercontent.com/58474997/102232095-006a3b80-3eef-11eb-9277-ea637bf68443.jpg)

**QField version:** 
1.7.7
QfieldSync: 3.4.0
QGIS : 3.10.12 LTR

## Additional information:

* Problem didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by suricactus** [comment]
Did you get the issue solved?

**Comment by bsturm** [comment]
Yes. I posted this issue in /gfield as well, since I was not sure where to put it. It got solved there!

01.04.2021 12:51:57 Ivan Ivanov ***@***.***>:
