### ISSUE TITLE
Hardware back button

### ISSUE THREAD

**Issue by AgroGPS** [opengisch/qfieldsync#209]
I think You totally ignore hardware/Android back button. From smartphone usage - when I something don't want and want to go back, I press back button. And in QField it doesn't works like that. For example - from table of selected features I choose the feature to edit and I change some attribute. But then I found out that it's not that feature that I want edit. I want to go back to the table of selected features and select another feature. So, I press hardware back button. Sorry, I can't exactly remember where I get, but then I edit another feature. But when I then check the first selected/edited the changed values are there :O Nevertheless I don't confirm the editions on that feature!

**Comment by AgroGPS** [comment]
I'm very sorry, I made an mistake :( That's not a qfiledsync issue but QField. Can the admin move it to QField, please?

**Comment by m-kuhn** [comment]
Thanks a lot for these suggestions. Very valuable :+1: 
Please reopen them again in QField (github doesn't offer an admin panel that would allow to do so).

Some pro tips: I would suggest to keep issues generic. Ideally illustrated with an image and steps to reproduce. Avoid the term "you" in the initial report - unless of course you have a support contract with a developer to who you can talk :)
