### ISSUE TITLE
QFieldSync not functioning for copying existing features

### ISSUE THREAD

**Issue by Paul-Losse** [opengisch/qfieldsync#211]
Layers for which features are created in QGIS and set to 'offline editing' appear in QField without problems. However if one layer is set to 'copy', any features created in QGIS do not show in QField. The layer appears in the list of layers and features can be digitised when in QField. Again this is only a problem for geopackage layers. This problem does not occur with shapefile layers.

**Comment by suricactus** [comment]
Can you provide a sample project?

**Comment by Paul-Losse** [comment]
Dear Ivan,

Please find a sample project attached.

When using 'copy' in the QField Syn plugin, features (points, lines or 
polygons) do not appear in the project when transferred to QField. This 
problem does not occur if 'offline editing' is selected in the 
QFieldsync plugin. Note that this is only a problem when using the 
geopackage format. If all layers are shapefiles, this problem does not 
occur.

Best regards

Paul Losse

**Comment by suricactus** [comment]
Dear Paul Losse,

Can you share you QGIS and QFieldSync version? Would be amazing to try the latest experimental version of QFieldSync too, since it is going to be the officially supported version very soon. Also, can you upload the attached project using GitHub interface, since your email response lost the attached file.

Best,
Ivan

**Comment by Paul-Losse** [comment]
Hi Ivan,

I'm running QGIS version 3.16.15 and QField Sync version 3.4.4

How do I upload the project using the GitHub interface?

Best regards

Paul

**Comment by Paul-Losse** [comment]
[Example project.zip](https://github.com/opengisch/qfieldsync/files/7994690/Example.project.zip)

**Comment by Paul-Losse** [comment]
Example project added

**Comment by suricactus** [comment]
Hey, @Paul-Losse. Just tried your project with the latest experimental version of QFieldSync BETA19 and the upcoming BETA20. It works fine. Since QFIeldSync 3 will be replaced very soon, please check the new version and let me know if it works for you.
