### ISSUE TITLE
Unable to export PGSQL layers

### ISSUE THREAD

**Issue by chanteclair12** [opengisch/qfieldsync#213]
Hello
I am a new user of QField,
I tested the transfer of a Qgis project containing PGSQL layers to QField last summer.
It worked well, both on QField and back of the field when synchronizing with PGSQL.

I have been trying since this morning to redo the same operation on a new project and there it is the drama :-)
Cannot use the 2 desired PGSQL layers. In the plugin, i put these layers in "Offline edition" like it is told in this link (https://qfield.org/docs/fr/synchronise/qfieldsync.html) but it does not work ... i have a message in the interface of the plugin "Unsupported layers".

I'm still on the same versions as this summer (Qgis 3.4.5, QField 3.2.2 plugin, PGSQL 9.6).

I tested with Qgis versions 3.10 and 3.16 and the latest version of the QField 3.4.0 plugin. 
Not better. 
I can open the project on the tablet and see the OSM background loaded, the list of layers is present but also a message "The following layers cannot be loaded. Check them and reconfigure your Qgis project".

Does anyone have any idea what is wrong?
Thank you.

**Comment by suricactus** [comment]
Can you provide a test project? It dramatically increaces the chance to get your problem checked.

**Comment by chanteclair12** [comment]
Sorry, 
I have forgotten this old post.
I found a solution for this issue. Remembering it was by using a Uuid in the main layer instead of usual gid.
Thanks for your answer.
