### ISSUE TITLE
If "DCIM" is not at the same level of the QGIS project, photos are not copied back when doing "Synchronize from QField"

### ISSUE THREAD

**Issue by gioman** [opengisch/qfieldsync#226]
Steps:

*) you have a folder (call it "A") with a QGIS project and postgis layers

*) inside the A folder you have another one that contains the canonical "DCIM" for the photos, let's says is "media/DCIM"

*) qgis is configured to look for the attachment photos in such folder

*) qfield sync is also configured to save photos in that folder

*) the project is placed off-line with qfield sync in a folder, call it "B". "B" is transferred to the mobile device.

*) with qfield a layer is edited and pictures taken, they go as expected inside "media/DCIM". Work finished and "B" is transferred back to the desktop

*) with Qfield sync the data is syncronized with "Synchronize from QField", but the new photos are not copied from "B/media/DCIM" to "A/media/DCIM"

If instead of "media/DCIM" is used just "DCIM" is all ok.

**Comment by m-kuhn** [comment]
QFieldSync doesn't know where the photos ended up. To support this, I think a new configuration option needs to be added where a regex/glob pattern can be specified which folders to sync. (`media/DCIM`, `media/*`, ...).

**Comment by gioman** [comment]
> QFieldSync doesn't know where the photos ended up

@m-kuhn Hi Matthias, thanks for the reply, but I'm not sure I follow. QFieldSync does indeed know where the photos are to be saved, it is configured here

![Screenshot_20210330_103421](https://user-images.githubusercontent.com/1951107/112967771-81b6a880-9143-11eb-949e-4ee06ff03685.png)

and indeed the photos are saved on the configured location with QField. They are just not synchronized back to the desktop.

**Comment by m-kuhn** [comment]
With this expression it's possible to configure file name and path, so we don't know if we need to copy `media`, `media/DCIM` or ...

Evenmore you could have something like `CONCAT(@username, '/DCIM/', "feature_name", '/', "feature_id", '.jpg')` or `CONCAT(format_date(now(), 'yyyyMMdd'), format_date(now(), 'hhmm'), '.jpg')` which will make it almost impossible to guess the right paths to sync.

**Comment by gioman** [comment]
But for naming expressions that do not contain variables or functions, should not be straightforarwd? anyway, I believe what you say.

**Comment by m-kuhn** [comment]
I think every naming expression will contain variables or functions (like `format_date(now(), ...)` in your example) -- otherwise each picture will have exactly the same name. Now we could evaluate the expression to `media/DCIM/registos-flora-pico_20210330123211223.jpg` and then take the first part of the path (`media`), but it will likely fail for expressions using field names, so I'd prefer to have one approach that always works instead of trying to smart out the system.

**Comment by gioman** [comment]
got it.

**Comment by suricactus** [comment]
This is coming in the next QFieldSync version, check https://github.com/opengisch/qfieldsync/pull/449
