### ISSUE TITLE
Phyton Error during Packaging for Qfield - Project unusable in Qfield

### ISSUE THREAD

**Issue by bsturm** [opengisch/qfieldsync#230]
I am getting the following Alerts.
Note: The Layer `"Artkürzel_EWZR" appearing under "Key Error" is a table-layer i have connected vie value-relation-widget to the Layer i want to work with as an offline layer:

> Ein Fehler trat bei der Ausführung von Python-Code auf: 
> 
> KeyError: 'Artkürzel_EWZR_aa6e4a5d_3bb6_4a5d_a8d2_555a4270c73d' 
> Traceback (most recent call last):
>   File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\package_dialog.py", line 123, in package_project
>     offline_convertor.convert()
>   File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\offline_converter.py", line 268, in convert
>     if offline_layer.customProperty('remoteSource') == original_layer_info[online_layer_id][0]:
> KeyError: 'Artkürzel_EWZR_aa6e4a5d_3bb6_4a5d_a8d2_555a4270c73d'
> 
> 
> Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] 
> QGIS-Version: 3.16.4-Hannover Hannover, 654e76b3cb 
> 

The Project turns out to be unusable in Qfield.

The resulting Offline Layer can't be edited.

**Comment by 3nids** [comment]
something similar here, but without any key
![image](https://user-images.githubusercontent.com/127259/115349230-e2218e80-a1b3-11eb-8a1d-84696f894b22.png)

(in 3.4.2)

**Comment by 3nids** [comment]
partially fixed in #233

**Comment by suricactus** [comment]
should be fixed in https://github.com/opengisch/qfieldsync/pull/177
