### ISSUE TITLE
Cable export settings overwrite cloud export settings

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/qfieldsync#231]
Each time "configure current project" is clicked, the settings for "lock geometries" in the cloud tab are overwritten with the settings for cable export.
Should only the active tab be saved or should they be synchronized in the gui between the two tabs?

![image](https://user-images.githubusercontent.com/588407/113663982-43713a00-96ab-11eb-86e0-ac87666b6f93.png)

**Comment by suricactus** [comment]
This is fixed for some time, the lock geometries setting is moved per layer and it is global to cable/cloud export.
