### ISSUE TITLE
Path oft Raster File (geopackage) doesn't get changed while packaging

### ISSUE THREAD

**Issue by bsturm** [opengisch/qfieldsync#234]
After packaging process all file paths are changed to project folder except my background raster.
The path of the raster is unchanged, naturally resulting in an error after exporting to qfield: raster-layer can not be found.

workaround: Before copying the project folder to my tablet, I have to open the packaged project, change datasource of my raster-layer to the file that is now in my project folder, save that and then copy.

happened several times now.

qgis 3 16 5
qfieldsync 3 4 2

**Comment by suricactus** [comment]
Thanks for the report@bsturm . Do you remember which version this issue started? Or it has always been like this?

**Comment by bsturm** [comment]
I don't remember it happening before this version.
First time it happened was mid of march, so I am quite sure it started with the recent version.

30.04.2021 11:25:32 Ivan Ivanov ***@***.***>:

**Comment by nirvn** [comment]
@bsturm , could you type the following command - `iface.activeLayer().source()` - in the python console after selecting your raster layer in the layer tree and tell us what the returned value is?

E.g.:
![image](https://user-images.githubusercontent.com/1728657/116691389-f1d77900-a9e4-11eb-90ff-5791366827c6.png)

**Comment by bsturm** [comment]
Which Project? Original Project or packaged project?

**Comment by nirvn** [comment]
@bsturm , original project please :)

**Comment by bsturm** [comment]
Output:

'Q:/Grundlagen/Luftbilder/2019 Gesamtbild/mosaic_all_gpkg.gpkg'

**Comment by nirvn** [comment]
@bsturm , what kind of raster format is it in?

**Comment by bsturm** [comment]
It's a geopackage

in another project (where the transfer did work) i got the following output:
'GPKG:Q:/Qfield Export/Brutvogelkartierung/mosaic_all_gpkg.gpkg:mosaic_all'

**Comment by nirvn** [comment]
OK -- are you in a position to try out with QGIS 3.18? I'm wondering if it's a fix that hasn't been backported to 3.16.

**Comment by bsturm** [comment]
I can't try it with 3.18. - we are only using LTS here at work, sorry :|

**Comment by nirvn** [comment]
@bsturm , OK, when you export that geopakage raster, the resulting project file has a broken layer or the layer's source refer to the original location of the dataset?

**Comment by bsturm** [comment]
After exporting, the layer's source still refers to the original location of that dataset

**Comment by nirvn** [comment]
@bsturm , could you attach the dataset to this issue? I'm puzzled as to why it wouldn't work here.

Can you try to type this in the python console and paste the returned values: `QgsProviderRegistry.instance().decodeUri('gdal', iface.activeLayer().source())`? Thanks

**Comment by bsturm** [comment]
{'layerName': 'mosaic_all', 'path': 'Q:/Grundlagen/Luftbilder/2019 Gesamtbild/mosaic_all_gpkg.gpkg'}

The file has about 400mb, maybe i could send you a link?

**Comment by nirvn** [comment]
I am mesmerized, it should work just fine :) If you can send a link here, that'd be good. I'll look into it some more locally.

**Comment by bsturm** [comment]
https://next.nabu-bw.de/s/gAJdLDmbjS6Kp5P

**Comment by suricactus** [comment]
@bsturm Is the issue still present. If yes, could you please share your project and raster with us again since the links expired.

**Comment by bsturm** [comment]
I will share a project and link soon.
