### ISSUE TITLE
Qfield crash on sync

### ISSUE THREAD

**Issue by lomptorne** [opengisch/qfieldsync#235]
Hello,

I allow myself to open an issue because my plugin crash on sync.
It crash on export but still make a valid project that work on Qfield.
And it also crash on import but this time newly added datas are not imported back on Qgis.
I use Qgis 3.8, the Qfield build for windows and the plugin version 3.2.2.

My test project contains few postgres layers( line point polygons) and a wms background.
The project crash just after the import/export when it's reloading.

I tried with a newly created Qgis profile It don't help at all. 

I also join the Qgis crash report in case it could help the issue. 

[Qgis report.txt](https://github.com/opengisch/qfieldsync/files/6441492/Qgis.report.txt)

Thanks you for your consideration, kind regards, Clément.

**Comment by m-kuhn** [comment]
Thanks for the report.
You are using "QGIS Version: 3.8.3-Zanzibar" which is very old and no longer officially supported.
Can you retry with QGIS 3.16 or 3.18?

**Comment by lomptorne** [comment]
Thanks for the feedback, It's my company who handle software update so unfortunately it's not possible for me to test on a newer version of QGis. But after more tests, I think the problem is related to Qgis annotation system, if I put an annotation with the Qgis tools on my projet it'll crash on sync. 

Thanks you for your suport, kind regards, Clément.
