### ISSUE TITLE
Python Error when creating Basemap

### ISSUE THREAD

**Issue by TSanderPGG** [opengisch/qfieldsync#237]
I get an error every time I try to create a basemap with QField Sync (see below). I have created basemaps before, but this error never appeared. I reinstalled QField Sync and updated to the newest QGIS Version, but the error still appears. It happens in projects with layers and also in projects with nothing in it but the XYZ-Tile which I want to create the basemap from.

```
2021-05-18T18:31:57     WARNING    Traceback (most recent call last):
              File "C:/Users/suntj/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\package_dialog.py", line 123, in package_project
              offline_convertor.convert()
              File "C:/Users/suntj/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\offline_converter.py", line 135, in convert
              self.project_configuration.base_map_mupp)
              File "C:/Users/suntj/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\offline_converter.py", line 334, in createBaseMapLayer
              new_layer = QgsRasterLayer(results['OUTPUT'], self.tr('Basemap'))
             KeyError: 'OUTPUT'
```

**Comment by uclaros** [comment]
I just came to report the same issue.
It seems that `createBaseMapLayer()` does not handle any errors in algorithm `qgis:rasterize`.
So if the algorithm fails for some reason, like using some long output path inside OneDrive in my case, then the packaging stops unexpectedly and this error is shown.

Temporary workaround: Use a simple output path without special characters ie `c:\tmp\`

**Comment by suricactus** [comment]
Hey, @uclaros thanks for the comment, I was having trouble to reproduce it.

**Comment by TSanderPGG** [comment]
Thank you @uclaros, I also tried to create a basemap in a path inside OneDrive. Using a simple output path worked for me too!

**Comment by TSanderPGG** [comment]
In addition to the long path and inside OneDrive it seems the packaging also stops when an umlaut is part of the path text. Can someone relate?

**Comment by uclaros** [comment]
Half the problem is in QGIS not properly handling paths in the gdal tool.
But the other half is in QFieldSync not checking if the gdal tool was successful.
