### ISSUE TITLE
Add a warning/stop QFieldsync when project is set to use absolute paths

### ISSUE THREAD

**Issue by gioman** [opengisch/qfieldsync#238]
If the QGIS project is set to use absolute paths, QFieldsync will export a project with absolute paths that will not work on QField for obvious reasons.

Sometimes a user sets absolute paths by mistake, but the there is also another outstanding scenario:

If the user will save the project into a PostgreSQL BD (because also maybe the project has only PostGIS and remote layers) then the project properties will **always** revert automatically to "save paths = absolute", causing issue when exporting with QFieldsync and moving the off-line project to QField.

**Comment by suricactus** [comment]
Waiting for QGIS to be released with https://github.com/qgis/qgis/commit/ee141a1a8ee06f3d052bee265b11e7af09b14d20
