### ISSUE TITLE
Default Values or Expression changed to NULL in QField-Sync Export package

### ISSUE THREAD

**Issue by mbodnar-GS** [opengisch/qfieldsync#241]
I have set numerous fields to a default value including DATE and all the positional data.
A few months ago when I exported the QFIELD package to my device this default value was maintained. 

Now with 3.16.7 or 3.18.3 and QFieldSync 3.4.2 all the default settings are changed to NULL in the Qfield project so the data collected does not have these default fields as intended. 

I have looked for a similar report but could not find it so I have generated this ticket. Apologies if it is a simple known issue or redundant report.

**Comment by mbodnar-GS** [comment]
I did additional testing on a separate machine (Win10) and found the export works as intended. Not sure why the package for QField function was not working properly on the first machine. I do have 3.16.7 LTR and 3.18.3 both installed in parallel, perhaps that is why the export did not work properly on the first machine.

**Comment by suricactus** [comment]
Hey @mbodnar-GS can you share a project/subset of the problematic project that caused the issue?
