### ISSUE TITLE
Syncing child feature before syncing parent feature to PostGIS violates foreign key constraint

### ISSUE THREAD

**Issue by geomoes** [opengisch/qfieldsync#249]
We have a QGIS project with a parent and two child layers (1:n relation) all stored in PostGIS. The parent primary key is a UUID (created in attribute form with the uuid() function). Both child layers use an UUID field as foreign key. Foreign key constraints are set properly in PostGIS and relations in QGIS (at project level and in the parent layer attribute form.
In QGIS and GField we can create new parent features and associated children features. In QGIS we have no problem to save to PostGIS.

When we sync with QFieldSync only the parent and one of the children layers is written to the database. The second layer always isn't written to the database and gives the following error:
`insert or update on table "child2" violates foreign key constraint "child2_fk" DETAIL: Key (uid)=(51ccac98-a32d-41c2-b9b3-c4beed1327da) is not present in table "parent"` 

The odd thing is, that the child1 layer and the parent layer are updated and inserted correctly and the parent key does exist in the database. 
So it seems that QFieldSync always tries to first sync the child2 layer to the database before the parent layer exits. What would explain the error.  

We checked every corner of the configuration, removed the child2 layer and reconfigured it in QGIS. We also removed the child1 layer, but still the child2 layer refuses to get synced. We do not see any differences between the two child layers, nor in their configuration, that could explain the different behavior.  We don't see any possibility to tell QFieldSync to first sync the parent layer before trying to add the children layers.  

For us it looks like a bug in QFielsSync.

**Comment by m-kuhn** [comment]
I don't see a lot of options either ( except disabling fk constraints in the db)

**Comment by geomoes** [comment]
Just tried a dirty workaround. I added an alias to the parent layer, so that it would lay before the name of the childrens layers in aphabetical order. 
The old (alphabetical) order was: gestion, peuplement, parquets => resulted in violation of foreign key constraint
The new (alphabetical) order is now: _parquets, gestion, peuplements => synchronizes without any problems.
So it seems, that QFieldSync respects the alphabetical order of the layer names while syncronizing and even considers alias names.

Even though this is not really a programmatical solution to the problem, it could be at least a quick and dirty workaround.
I'll test it again to see if it really keeps on working.

**Comment by m-kuhn** [comment]
Thank you for sharing the workaround

**Comment by turtlemap** [comment]
> The upcoming 3.22 should fix this issue. Check [qgis/QGIS#44636](https://github.com/qgis/QGIS/pull/44636)

I just experienced the same issue in Qgis LTR 3.22.8 / QFIELD 2.8.4
