### ISSUE TITLE
Add current_value() variable to picture naming patern

### ISSUE THREAD

**Issue by CATER-COM** [opengisch/qfieldsync#250]
Actualy applying picture naming patern work only on registered features beacause patern can access de attrubutes.

When a picture is created and not saved the attributes remain empty and it don't work.

QGIS now have 2 variables to deal with this problem of accessing value in a form before saving feature, it is designed primarily for cascading field. The variables are current_value() and   current_parent_value() (when there's sub form).

If this variables are made available in the contexte of picture naming patern, we could apply the patern without saving et access again the feature.

Thanks for this great app !

**Comment by suricactus** [comment]
Hey, @CATER-COM , please check the latest master release of QField. The support for live form values came with this PR https://github.com/opengisch/QField/pull/2047 .
