### ISSUE TITLE
python error when packaging 

### ISSUE THREAD

**Issue by 3nids** [opengisch/qfieldsync#256]
![image](https://user-images.githubusercontent.com/127259/122568305-e9490980-d049-11eb-829d-d0443546d583.png)

with 4.0 beta 6

**Comment by suricactus** [comment]
Do you have QGIS 3.20? Just updated and got the same error.

**Comment by 3nids** [comment]
yes, master

**Comment by suricactus** [comment]
Any idea why the slots might suddenly get broken?

**Comment by 3nids** [comment]
change of PyQt version? or you are still on the same?

**Comment by suricactus** [comment]
| old | new |
|-----|-------|
| ![Screenshot from 2021-06-21 18-57-31](https://user-images.githubusercontent.com/2820439/122792726-194f1180-d2c3-11eb-8216-784690218c92.png) | ![Screenshot from 2021-06-21 18-59-36](https://user-images.githubusercontent.com/2820439/122792723-181de480-d2c3-11eb-9123-eb01f95d0da5.png) |

**Comment by suricactus** [comment]
Just tested, the complete removal of the `pyqtSlot` slot made it work in 3.20.
```diff
    @pyqtSlot("QgsOfflineEditing::ProgressMode", int)
    def on_offline_editing_max_changed(self, _, mode_count):
        self.__max_task_progress = mode_count
```
