### ISSUE TITLE
Add visible layers/Add visible vector layers as Offline does not work as an option in Project properties

### ISSUE THREAD

**Issue by joebullardPA** [opengisch/qfieldsync#258]
I use QFieldSync 3.4.4 with QGIS 3.16.6. When configuring my layers with all layers set to Remove, selecting Add visible layers/Add visible vector layers as Offline from the Eye menu does not add any to offline editing or to the project as it should. They instead remain as they were - set to Remove.

**Comment by suricactus** [comment]
Thanks for spotting this. There should be a fix.now on master and the fix will ship with the next QFieldSync release.
