### ISSUE TITLE
QFieldSync changes generated uuid() on PostGIS layer (offline)

### ISSUE THREAD

**Issue by Horizen89** [opengisch/qfieldsync#259]
I have a system of PostGIS layers linked together by QGIS relations.
A geometry layer generates a first uuid(), and is linked to a "event" non-spatial layer generating a second uuid(). This "event" layer can then be linked to various other forms using this uuid().

Everything was working fine until lately, as the fist uuid() is correctly created, but is not copied correctly to the database when imported with QFieldSync. All the related informations are synced corretly (like the "event" table and all the other related informations), but the uuid() on the geometry layer is changed upon import, which of course breaks the relation with the "event" table and all the other ones.

If I manually change back the uuid() to the one that is stored in the .gpkg extracted from QField, the relation is restored, confirming that everything else is OK.

There is nothing I can see that can trigger such a change. No trigger/rule on the database side, and the option is not checked in the layer properties (the "Apply default value on update" button).

Again, I didn't experienced this behavior until last week or so.

EDIT: To give more details, if I write the same content (extracted the content from the .gpkg generated by QField and saved it as a SQL Dump) and pushed it in SQL to the PostGIS database, everything works perfectly. This is why I suspect the problem comes in the interaction between QGIS and QFieldSync.

To clarify what happens, here is an example:
In QField, I create a Point, that generates a uuid = A123. I create a Event with uuid = B234, and a Photo, with uuid = C345.
QGIS/QField relations push the Point uuid to the Event table, and the Event uuid to the Photo table.

If I open the QField .gpkg once extracted from the tablet, I get everything right:
Point: A123
Event: B234, reference to Point A123
Photo: C345, reference to Event B234

But when I transfer this to QGIS/PostGIS, the geometry layer fails to keep it's uuid. The rest is still perfect:
Point: **Z987**
Event: B234, reference to Point A123
Photo: C345, reference to Event B234

**Comment by suricactus** [comment]
Can you please share your QGIS/QFieldSync versions that cause the issue? Also, please check if which if any of the previous versions of QFieldSync work for you https://plugins.qgis.org/plugins/qfieldsync/ .

**Comment by Horizen89** [comment]
I had the problem with 3.4.3, so I upgraded to 3.4.4, and still have the issue.
I'll try the previous versions shortly and come back to you!

**Comment by Horizen89** [comment]
I so far tested with 3.4.0, 3.3.0 and 3.2.0 without success... which doesn't make much sense as it worked well two weeks ago.
I suspect something else is interfering... but I'm not proficient enough to know what.
Is there a way to intercept requests QFieldSync is making to QGIS, and QGIS to the database, in order to determine if something breaks along the way? I have no message in the QGIS log...

It feels like the uuid() generated in QField for the geometry layers is not accepted when the transfer occurs, and that QGIS generates a new one to comply with the "not null" restriction...

**Comment by Horizen89** [comment]
I can confirm that the uuid() is modified before being sent to the database. The query shows the wrong uuid(). So this happens within QGIS. What is the best way to track queries within QGIS? Is there a way to enable a log for the plugins such as QFieldSync?

**Comment by Horizen89** [comment]
If somebody else falls into that crack:
I wasn't able to find any problem with any part of the project (QField/QGIS/Postgresql).
That being said, it was obvious that the problem occurred within QGIS, either from QFieldSync, or from QGIS itself. (The raw data from the device was alright, and Postgres did write exactly what it received. So the UUID changed between the moment I activated QFieldSync and when QGIS sent the update to the database).

After a few tests, I realized that the problem was limited to the 3 geometric table I had in the project. I simply recreated these 3, replaced them in the project, copied the content of the database to the new tables, recreated the Relations within QGIS, and everything works fine again...

**Comment by suricactus** [comment]
Hey, @Horizen89 thanks for the update! I can asure you that QFieldSync does not modify your data, so I believe it was some kind of layer/datasource configuration that created the issue. Nevertheless, I am happy you managed to find your way and share your experience. Happy QField-ing!

**Comment by Horizen89** [comment]
UPDATE: The issue came back after a sync, and here are two observations:

1 - Simply recreating the Relations is necessary, no work on the database side (this usually involves putting back the geometry layers first).

2 - This seems to be directly related to JOINS on the layer. I literally took the same project, removed the JOINS, and everything runs smoothly. I have yet to determine if this happens to any level of join, or if it still happens if I set joins to be editable. I guess the problem comes from the geopackage conversion?

**Comment by Horizen89** [comment]
Yet another test:
If I use a version that has JOINS offline, but that I remove those JOINS from the extracted geopackage before using QFieldSync, the import seems to work!

**Comment by suricactus** [comment]
Hey, @Horizen89 , there were some changes done in QGIS 3.22 https://github.com/qgis/QGIS/pull/44636 . Not sure if they are directly to your issue, but would be nice if we get a feedback from you if all works well or not.

**Comment by Horizen89** [comment]
I did not realize the version you are talking about is not LTR or LR.
I have to say, I never installed a Nightly build... and I'm not sure where to start to do it right...

**Comment by Horizen89** [comment]
I just installed 3.22 and will try to reproduce the issue today. I'll post updates on the matter.

**Comment by Horizen89** [comment]
I will test further tomorrow, but a few quick tries seem to show that the problem has been solved somewhere between 3.16.7 and 3.16.13. I can reproduce with 3.16.7 and before, but 3.16.11/13 and 3.22 look perfect!

I don't know what changed, but hey, great!

**Comment by Horizen89** [comment]
I can confirm that I no longer experience the behavior with later versions of QGIS.
If this can help somebody pinpoint the cause, I can add that with 3.16.7, I am not able to export my project on the device, edit the project on the device, and then export the content to my computer for import to QGIS without unplugging the phone from the computer and plugging it back.
I don't need to do this on later versions.
The import was also a lot slower.

**Comment by suricactus** [comment]
Thanks for your detailed feedback, @Horizen89 . Then I'm happy to close this issue as solved.
