### ISSUE TITLE
Default values are lost when using "offline editing" option

### ISSUE THREAD

**Issue by saemiw** [opengisch/qfieldsync#26]
Default values defined in QGIS desktop are taken along by QField Sync if the action option "copy" is used in the project configuration ("configure projects now"). If I use "offline-editing" instead of "copy" all defined defaults are lost. 

example: I have a layer with the field "fruit" I define a default value "apple". With "copy" option of QField Sync I also get a default value "apple" on QField. With the "offline editing" option the default is lost (or does not display) in QField.

I use QField v.0.8.8 and QFieldSync v.0.9.1

**Comment by saemiw** [comment]
Little surprising but also worth noting: 

Also triggers are lost when using the "offline-editing" option to transfer a geopackage to QField.

**Comment by m-kuhn** [comment]
Triggers as in postgres triggers?

That's not going to happen "out of the box". Problem 1) is how to "translate" them from postgres to sqlite, problem 2) is how to prevent them from running a second time on synchronizing back.

What we will possibly add at some point is the possibility to add post-synchronization processing scripts which could redefine triggers automatically on the resulting dataset.

**Comment by saemiw** [comment]
I used geopackage and defined a trigger with sql like this. 

> CREATE TRIGGER nestname AFTER INSERT ON nestnames 
> BEGIN 
> UPDATE nestnames SET nestname = observer||rowid WHERE rowid = new.rowid; 
> END 

For 1) I see your point. Maybe it could be possible to keep triggers when working only with geopackage/sqlite-databases. Translation would not be necessary in this case no?
For 2) I have not thought about that...but you are of course right.
Conclusion: No urgent need to adapt something (unless copying of geopackage/sqlite triggers is easily doable).
