### ISSUE TITLE
QField sync error messages

### ISSUE THREAD

**Issue by Socamiste** [opengisch/qfieldsync#262]
Hello,
I have a problem synching data collected in Qfield with the main project. The data synchronises successfully but the original project cannot be opened, leaving me with a blank screen. I've tried saving the project to reopen later hoping the data from the modified gpkg will be there but I get the message "unable to perform zip". I created the project on version 3.10 using Qfield 3.4.4. Any help appreciated.

**Comment by suricactus** [comment]
Please attach the project original and the QField projects, so we can help.
