### ISSUE TITLE
QField sync errors

### ISSUE THREAD

**Issue by Socamiste** [opengisch/qfieldsync#263]
I created a project in QGIS 3.14 to export to Qfield. Collected data and tried synching with the project on my laptop. After numerous attempts, I updated to the latest, stable version of QGIS and used QField sync v.4.0.0 to try to sync the data once more. The data appears on the map but I got the following error message;

IndexError: list index out of range Traceback (most recent call last): File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\libqfieldsync\offline_converter.py", line 561, in on_offline_editing_next_layer layer_name=self.__offline_layer_names[layer_index - 1] IndexError: list index out of range

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May 3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] QGIS version: 3.16.8-Hannover Hannover, 8c50902e

Python Path: C:/PROGRA~1/QGIS31~1.8/apps/qgis-ltr/./python C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins C:/PROGRA~1/QGIS31~1.8/apps/qgis-ltr/./python/plugins C:\Program Files\QGIS 3.16.8\bin\python39.zip C:\PROGRA~1\QGIS31~1.8\apps\Python39\DLLs C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib C:\Program Files\QGIS 3.16.8\bin C:\PROGRA~1\QGIS31~1.8\apps\Python39 C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\site-packages C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\site-packages\win32 C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\site-packages\win32\lib C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\site-packages\Pythonwin C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python C:\Users\User\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools C:\Users\User\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools C:/Users/User/Documents/Qfield_import

**Comment by suricactus** [comment]
Hey, @Socamiste . Thanks for reporting. Please provide us with the following information:

1) Have you tried with the latest 4.0.0 beta-x version and do you get the same error?
2) Have you tried with the latest 3.x.x stable version and do you get the same error?
3) Is it possible you provide the online and offline project, so we can try to reproduce the error?
