### ISSUE TITLE
error with plugin upgrade

### ISSUE THREAD

**Issue by 3nids** [opengisch/qfieldsync#27]
Got this error while upgrading the plugin to 0.9.1

>   File "/home/drouzaud/.qgis2/python/plugins/qfieldsync/dialogs/project_configuration_dialog.py", line 29, in 
    from qgis.core import (
ImportError: cannot import name QgsMapLayerProxyModel

**Comment by 3nids** [comment]
it's in gui in 2.x, while in core in 3.x

**Comment by m-kuhn** [comment]
This is part of qgis2compat version 0.3.3. Was there no notice to update qgis2compat when updating qfieldsync?

**Comment by 3nids** [comment]
well no, both were updated at the same time, maybe in the wrong order

**Comment by 3nids** [comment]
I0ve got qgis2compat 0.3.4 now, but QFieldSync seems to be inactive. It's listed and active in plugin dialog, but don't see any option or menu in QGIS
