### ISSUE TITLE
Layers disappearing from the project when exporting

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/qfieldsync#28]
if I choose a layer to be exported as offline (.sqlite), it remains in the project and in the canvas.
If it's of the type "copy" (so it remains as .shp), it disappears from the original source project.

**QFieldSync version: 0.9.1
QGIS version: 2.18.1
OS: Debian sid
Layer type: shapefile**

Migrated from https://github.com/opengisch/QField/issues/89

**Comment by jlgranda** [comment]
Hi, I think that follow is a relationate issue.

I try to develop qfieldsync standalone version (thank you for advice https://github.com/opengisch/qfieldsync/issues/159) .  At moment this works, the original project has <mapcanvas></mapcanvas> element, when read the project and copy,  the offline copy is without that.

When I try to load offline into QField, the map are all extend and GPS position set into middle Pacific Ocean :(
