### ISSUE TITLE
not able to download photos with slash in photo name on windows

### ISSUE THREAD

**Issue by lindacamathias** [opengisch/qfieldsync#282]
The synchronization of a photo does not work on Windows when there is a slash (e.g. DCIM/ ) in the photo name.

1. configure photo naming in QGIS (see screenshot) 
this is my photo naming 
QGIS 3.16.9  
![image](https://user-images.githubusercontent.com/77726342/128038560-c2fd48ba-8a87-46fa-9d87-1905f49b5db9.png)

2. sync project to QFieldCloud
3. take photos in QField and push changes to Cloud
4. in QGIS sync photos from Cloud to local

foto_1 and foto_3 are syncronised properly. 
foto_2 -> 

An error has occurred while executing Python code: 

KeyError: 'DCIM\\test2_slash_20210803165139796.jpg' 
Traceback (most recent call last):
  File "C:\Users/Linda/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\cloud_transferrer.py", line 405, in cb
    self._on_download_file_finished(reply, filename, temp_filename)
  File "C:\Users/Linda/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\cloud_transferrer.py", line 429, in _on_download_file_finished
    self._temp_dir2main_dir("download")
  File "C:\Users/Linda/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\cloud_transferrer.py", line 504, in _temp_dir2main_dir
    self._files_to_download[source_filename]["project_file"].local_path
KeyError: 'DCIM\\test2_slash_20210803165139796.jpg'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.16.9-Hannover Hannover, 9f8d2f79 

Python Path:
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/Linda/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Linda/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\Users\Linda\AppData\Roaming\Python\Python39\site-packages
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:/Users/Linda/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/Linda/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\Linda\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\Linda\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
C:/Users/Linda/Documents/projekte/my_testdata/bp_assess

**Comment by lindacamathias** [comment]
QFieldCloud project bp9 (suricactus has been invited)

**Comment by suricactus** [comment]
can you try the plugin deployed there, should be fixed now https://github.com/opengisch/qfieldsync/actions/runs/1100900416

**Comment by suricactus** [comment]
Please check this version https://github.com/opengisch/qfieldsync/actions/runs/1102358190
