### ISSUE TITLE
Project configurations can't be changed once they are defined

### ISSUE THREAD

**Issue by saemiw** [opengisch/qfieldsync#29]
When first using QField Sync on a new project, the user is asked to "Configure project now". Once this is done and the project is saved the configuration settings are saved to the QGIS-Project file. This is very helpful so one doesn't have to set the configuration again and again when using the same settings. But the project configuration can't be changed/adapted (inside the QField Sync Plugin) afterwards (which would be helpful in some situations).

**Comment by m-kuhn** [comment]
Did you try the plugin -> QFieldSync -> project configuration menu?

The idea was to set it up once as a project maintainer and then give the pre-configured project to field workers. These should not normally have to deal with (and certainly not mess with) the configuration so it's better if it's a bit hidden.

**Comment by saemiw** [comment]
> Did you try the plugin -> QFieldSync -> project configuration menu?
Yes that is exactly what I meant.

> The idea was to set it up once as a project maintainer and then give the pre-configured project to field workers. These should not normally have to deal with (and certainly not mess with) the configuration so it's better if it's a bit hidden.
Your idea is perfectly fine but some option the come back to the configuration (from inside the plugin) would never the less be helpful. Sometimes even a project maintainer needs to revisit his original settings. And in some cases the field workers are also the project leaders that want to adapt he export (for example resolution or layers of the basemap) to changing situations. So a slightly hidden button or something to access and change the configurations somehwere in the plugin would be a helpful improvement of the plugin.

**Comment by m-kuhn** [comment]
There is a menu item in the menu bar "Plugins => QFieldSync => Project Configuration" ("Erweiterungen" in German"). Does this not work for what you want?

**Comment by saemiw** [comment]
Hi Mathias, oh sorry. Yes I wasn't aware of this menu. Yes this will help. Sorry for not understanding before. Thanks!!!

**Comment by m-kuhn** [comment]
Great!
