### ISSUE TITLE
Message "1 attachment(s) are currently being uploaded..." never disappears

### ISSUE THREAD

**Issue by lindacamathias** [opengisch/qfieldsync#291]
After pushing new features with photos to the cloud the green message "1 attachment(s) are currently being uploaded in the background"  never disappears.  Only the number of attachments is updated (e.g. from 3 attachments to 1). 

![Screenshot_20210804-165548_QField Dev](https://user-images.githubusercontent.com/77726342/128509983-55ddead9-a956-4881-a5b7-d5b791f36b2d.jpg)

M. Kuhn ".. ideally it would be shown outside this panel- an upwards pointing arrow - animated"

QField master dev 95fe41

**Comment by suricactus** [comment]
If this is stiill a bug, please report it on the QField repository.
