### ISSUE TITLE
Error when synchronizing from QField when an "int" field has been cleared in QField

### ISSUE THREAD

**Issue by gioman** [opengisch/qfieldsync#292]
Qfield Sync:
4.0.0-BETA8
v3.4.4

QField:
2.0.2 Beta3

QGIS:
master
3.20

Take a project with a PostGIS layer with an "int" field (filled), make it offline and port it to QField.

In QField edit an existing feature and clear the "int" field.

Try synchronize basck to PostGIS with QFieldSync, it will fail as it will try to update the feature with something like

`UPDATE "schemaname"."tablename" SET "columnname"='' WHERE "i...`

instead of something like

`UPDATE "schemaname"."tablename" SET "columnname"=NULL WHERE "i...`

**Comment by paschendale** [comment]
The same thing happens on **numeric** and **timestamp** fields as well. 

---

Although not a QFieldSync fix, a workaround is to use BEFORE INSERT DO .... triggers on PostgreSQL to change the value before commiting and avoiding such errors on the client side.

For the specific **int** problem, create a function `try_cast_int()`:

```
CREATE OR REPLACE FUNCTION public.try_cast_int(
	anyelement,
	p_default integer DEFAULT NULL::integer)
    RETURNS integer
    LANGUAGE 'plpgsql'
AS $BODY$
begin
  begin
    return $1::int;
  exception 
    when others then
       return p_default;
  end;
end;
$BODY$;
```

And use it on a trigger function to change the value before it is commited:

```
CREATE OR REPLACE FUNCTION avoid_int_error()
    RETURNS trigger AS
    $BODY$      
    BEGIN
        NEW.my_int_field= try_cast_int(NEW.my_int_field);
        RETURN NEW;
    END;
    $BODY$
	LANGUAGE plpgsql;
```

```
CREATE TRIGGER avoid_int_error  BEFORE INSERT OR UPDATE ON my_table
    FOR EACH ROW EXECUTE PROCEDURE avoid_int_error();
```

**Comment by suricactus** [comment]
@gioman @paschendale this bug reports is quite old. There were a lot of changes in QField and QFieldSync, is this still an issue?
