### ISSUE TITLE
layer order is dropped when exporting

### ISSUE THREAD

**Issue by 3nids** [opengisch/qfieldsync#30]
layer ordered is not brought along in the new project (opening creating project on desktop shows the order is not the original one)

**Comment by m-kuhn** [comment]
First insights (with QGIS 2.18)

 * rendering order is in `QgsLayerTreeMapCanvasBridge`
 * `QgsLayerTreeMapCanvasBridge` is in gui (probably not the right place to save the rendering order!)
 * `QgsOfflineEditing` (which creates the new unordered layers) lives in core and has no access to the bridge
 * fail with 2.18

For QGIS 3.0

* bring the bridge (or at least the order) to core

In the meanwhile

* we can possibly workaround it in QFieldSync

**Comment by 3nids** [comment]
Is the offline editing plugin working as expected in 3.0? I wouldn't mind using 3.0 to generate the export. And that would save you from doing a hack in QFieldSync.

Otherwise, you have a rough idea how hard it would be in the plugin?

**Comment by m-kuhn** [comment]
> Is the offline editing plugin working as expected in 3.0?

Probably not, but fixing it requires bigger changes in the source code which would be too dangerous for a stable release.

On the other hand, it would be quite easy to do in the plugin.
