### ISSUE TITLE
Value relations are changed to wrong tables during export-process

### ISSUE THREAD

**Issue by koenigherford** [opengisch/qfieldsync#305]
If you export a project with some value relations, some of the value relations are changed in an invalid way to wrong tables. In result you get wrong value relations in your offline-project

How to reproduce

Step 1) Prepare some data in postgresql-database
```
CREATE TABLE public.test_1 (
    test_1_id   integer PRIMARY KEY,
    test_1_attr_1   varchar(40),
	test_1_ref_table_a integer,
	test_1_ref_table_b integer,
	test_1_attr_2   varchar(40)
);

insert into public.test_1 values 
    (1,'attribute 1a', 1, 11, 'attribute 1b'), 
	(2,'attribute 2a', 2, 12, 'attribute 2b');

CREATE TABLE public.test_a (
    test_a_id   integer PRIMARY KEY,
    test_a_attr   varchar(40)
);

insert into public.test_a values 
    (1,'Attribute Table_A No. 1'), 
	(2,'Attribute Table_A No. 2');

CREATE TABLE public.test_b (
    test_b_id   integer PRIMARY KEY,
    test_b_attr   varchar(40)
);

insert into public.test_b values 
    (11,'Attribute Table_B No. 11'), 
	(12,'Attribute Table_B No. 12');
```

Step 2a) Insert tables into project and create value relations
![grafik](https://user-images.githubusercontent.com/28433436/131956747-0f7d8395-5d5a-4a4e-a160-f60d9822cdab.png)

Step 2b) Check attributes of table "test_1": -> data/value relation is OK 
![grafik](https://user-images.githubusercontent.com/28433436/131956850-c35b329b-0d34-454a-b390-858e882a0497.png)

**Export via QFIELDSYNC**
Step 3a) Export data with QFieldSync (Installed 4.0.0. Beta 7)

Step 4a) Open Offline-Project from step 3

Step 5a) Check attributes of offline-table "test_1": -> data/value relation is WRONG
![grafik](https://user-images.githubusercontent.com/28433436/131957024-87e23bb8-690f-4595-bbee-6a4f0b82a0be.png)
A new field FID was added

Step 6a: Look up the attribute-table definition and value relation definition in qfieldsync-offline-project
1) a new field "fid" is created in comparison to original table
2) the value relation of field "test_1_ref_table_a" switched from "table test_a" to "table test_b" (layer, key column and value column are affected) – which differs from original project and results in unexpected /wrong data
![grafik](https://user-images.githubusercontent.com/28433436/131955181-032960b0-9d12-4358-96b0-a05b6c6b08c9.png)

**Export via OFFLINE-EDITING-PLUGIN** 
Step 3b) Export data with offline-editing-plugin

Step 3c) Save offline-project

Step 4a) Open offline-Project from step 3b/c

Step 5a) Check attributes of offline-table "test_1": -> data/value relation is OK
![grafik](https://user-images.githubusercontent.com/28433436/131956407-0e71a340-8258-41e8-9cc4-50f2417f8893.png)

So the issue seems to be in qfieldsync-process. Maybe something goes wrong with the field-index of values-relations when inserting the new fid-field

**Test-project attached**
[opengis_test_2021_03_09.zip](https://github.com/opengisch/qfieldsync/files/7103621/opengis_test_2021_03_09.zip)

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.5-Hannover | QGIS code revision | 58ba7c1ed6
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | actions_for_relations; batchvectorlayersaver; changeDataSource; clipper; ClosestPoint; closest_points; DataDrivenInputMask; DbgBaum; embedding_svg; Go2NextFeature3; lockzoom; mmqgis; OSMDownloader; pluginbuilder3; processing_js; qfieldsync; qgis_resource_sharing; qtiles3; quick_map_services; splitmultipart; SplitPolygonShowingAreas; VectorBender; xplanung; db_manager; processing

</body></html>

 
[opengis_test_2021_03_09.zip](https://github.com/opengisch/qfieldsync/files/7103621/opengis_test_2021_03_09.zip)

**Comment by suricactus** [comment]
hey @koenigherford , thanks for the detailed report. Have you tried with the latest beta 9 (https://plugins.qgis.org/plugins/qfieldsync/version/v4.0.0-beta9/)?

**Comment by koenigherford** [comment]
@suricactus 

...tried to install v4.0.0.-beta 9 ...
...but got an error report during install...
```
 [:(Couldn't load plugin 'qfieldsync' due to an error when calling its classFactory() method 

ImportError: cannot import name 'TypedDict' from 'typing' (C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\typing.py) 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/b2306704/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\__init__.py", line 40, in classFactory
    from qfieldsync.qfield_sync import QFieldSync
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/b2306704/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\qfield_sync.py", line 32, in 
    from qfieldsync.core import Preferences
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/b2306704/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\__init__.py", line 1, in 
    from .cloud_converter import CloudConverter  # NOQA
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/b2306704/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\cloud_converter.py", line 28, in 
    from qfieldsync.libqfieldsync.layer import LayerSource
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/b2306704/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\libqfieldsync\__init__.py", line 2, in 
    from .offline_converter import OfflineConverter
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/b2306704/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\libqfieldsync\offline_converter.py", line 27, in 
    from typing import Dict, List, Optional, TypedDict
ImportError: cannot import name 'TypedDict' from 'typing' (C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\typing.py)


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.16.5-Hannover Hannover, 58ba7c1ed6 

Python Path:
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/b2306704/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/b2306704/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/b2306704/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/b2306704/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ClosestPoint
C:/Users/b2306704/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask
C:\Users\b2306704\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:/Users/b2306704/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\b2306704\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\b2306704\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
.
C:/Users/b2306704/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask
C:/temp/opengis_test_2021_03_0) ]
```

...but although it seems to be installed...
![grafik](https://user-images.githubusercontent.com/28433436/132160799-993e0e62-149c-4f0c-b40d-ffa97183da29.png)

the menu-entry
![grafik](https://user-images.githubusercontent.com/28433436/132160962-3e027fbb-03b3-4fc0-b856-d95fa5867c33.png)
can not be opend further. So installation with 3.16. failed.

Is the minimum version for qfieldsync beta 9 qgis 3.20.2 ? (Then will to have to ask my admin to install this qgis-version first. This may take some time...)

**Comment by ralfkoenig** [comment]
Tried this on my private laptop.

Issue can not be confimed with a fresh installation of QGIS 3.20.2 and QFieldSync 4.0.0.-beta9 

Issue can be closed

**Comment by m-kuhn** [comment]
Thanks for the feedback
