### ISSUE TITLE
Symbology lost during sync due to layer name change

### ISSUE THREAD

**Issue by pcav** [opengisch/qfieldsync#31]
See thread on:
http://lists.qfield.org/pipermail/users-qfield.org/2017-February/000024.html
Sample data attached.
[symb.tar.gz](https://github.com/opengisch/qfieldsync/files/789489/symb.tar.gz)

**Comment by m-kuhn** [comment]
Looks like the expression is preserved, but the layer name changes from `my_places` to `my_places (offline)`, so the `get_feature` expression no longer works... That's the core offline_editing functionality from QGIS that changes the layer name...

Not sure what to do there...

**Comment by signedav** [comment]
This issue persists. Occurs on users configuration for default values using other tables.
