### ISSUE TITLE
QFieldSync - project update failed API error

### ISSUE THREAD

**Issue by jpdupuy** [opengisch/qfieldsync#312]
Hello,

Version 4.0.0-beta12 : I tried to enter a project description (since it did not work when I created an empty project).
However when I try to the project description (since it was empty) I receive the follwoing error message 
   Project update failed : API error

![image](https://user-images.githubusercontent.com/72449015/133093990-599bc1b8-1ef7-43bf-8b1a-285b219acd35.png)

**Comment by suricactus** [comment]
Hi, @jpdupuy . Thanks for reporting this. It has already been addressed in https://github.com/opengisch/qfieldsync/pull/313 and the fix is coming with the new beta13 later today/tomorrow.

**Comment by suricactus** [comment]
Already fixed in BETA13.
