### ISSUE TITLE
QFieldSync - does not accept anymore project names with @ or underscore

### ISSUE THREAD

**Issue by jpdupuy** [opengisch/qfieldsync#314]
When the Project Name value get changed in the project name field 
 - you cannot enter anymore the @ sign
 -  when you enter underscore characters they are ignored
![image](https://user-images.githubusercontent.com/72449015/133094826-b5b99574-0b25-45ab-8372-ffd05efabfc0.png)

**Comment by suricactus** [comment]
Fixed in beta15.
