### ISSUE TITLE
Question regarding photo naming

### ISSUE THREAD

**Issue by vlebert** [opengisch/qfieldsync#317]
Hi 

I have a question regarding the photo naming (Qfield panel in Qgis project properties). I think it is related with qfieldsync, but I am not 100% sure).

I want to prefix the pictures taking with a prefix corresponding to a field of the layer.

Let' say the photo naming is set like this:

`'DCIM/' || attribute(  $currentfeature , 'ad_code') || '_' ||   format_date(now(),'yyyyMMddhhmmsszzz') || '.jpg'`

(I guess `'DCIM/' || "ad_code" || '_' ||   format_date(now(),'yyyyMMddhhmmsszzz') || '.jpg'` would give the same results)

I ran a few test and I come to this conclusions:
- If I edit a feature with existing data, photo naming is working as expected
- If I edit a new feature, and take a picture **before** editing `ad_code` field, photo naming does not take into account `attribute(  $currentfeature , 'ad_code')` (understandable as the photo is already taken)
- If a edit a new feature, and take a picture **after** editing `ad_code` field, photo naming does not take into account `attribute(  $currentfeature , 'ad_code')` (Which is an issue I beleive)
- If I edit a new feature and find a way to fill `ad_code` with a default value through formula for example, photo naming is working as expected. It is however not always possible.

Am I in the right place to adress this issue?

Do you share these conclusions?

Do you confirm bullet point number 3 is and issue?

Thanks

Valérian

**Comment by suricactus** [comment]
Hey, @vlebert thanks for the well described issue. Can you please share QField version you are using?

**Comment by vlebert** [comment]
Hi

I am curently 1.9.6, though I am not 100% sure it was the version I ran the tests with, a fiew weeks ago

**Comment by suricactus** [comment]
Can you please try with v2.0 which is in beta. This should be fixed. You can download it also from https://github.com/opengisch/QField/commit/8dc9ebc1a8bb212f05a845d0ef68371a22b6b7cc

**Comment by vlebert** [comment]
Hi

I tried with the unstable version from playstore. My 3rd point is fixed in this version. Thanks

Last case a bit tricky : if you edit the field used in photo naming AFTER taking the picture, the photo name is not changed accordingly. However it is difficult to imagine a different behaviour.

**Comment by suricactus** [comment]
@vlebert Thanks for the confirmation.

The tricky case - this is the way it works right now. As soon as you take the picture it needs to be stored somewhere. If the naming expression fails to return good result, then it uses the default timestamp naming.
