### ISSUE TITLE
opening layer properties of a memory layer makes QGIS crash

### ISSUE THREAD

**Issue by 3nids** [opengisch/qfieldsync#319]
if I open the layer properties of a layer coming out of processing (i.e. memory layer), I get a crash here

![image](https://user-images.githubusercontent.com/127259/133793098-5f7d67d7-9b69-488b-b5e0-7a8fccf84266.png)

**Comment by nirvn** [comment]
This is fixed by the following commit (https://github.com/opengisch/libqfieldsync/commit/9ed162b2b4407dfd1d597f4735e8f9ee63ae58f6), which changed the `Path(self.filename).exists()` to `os.path.isfile(self.filename)`. The latter doesn't assert on overly long filename strings.
