### ISSUE TITLE
Relations are lost when using "offline editing" option 

### ISSUE THREAD

**Issue by saemiw** [opengisch/qfieldsync#32]
When preparing a project for offline-use with QFieldSync plugin the relations (defined in the QGIS Project properties) are not writen to the offline project. This is crucial if you want to use the relation reference widget in combination with offline-editing. I worked with geopackages. 

Here is a video that demonstrated the problem: https://youtu.be/l7WCdPt5kc0

It would be great if the problem could be fixed before the next point release (which is this friday...:-S).

**Comment by m-kuhn** [comment]
Fixed in https://github.com/qgis/QGIS/commit/94c4d6b4273003cdc27551632d0f9cc2efd39c6a (will be in 2.18.4)

**Comment by saemiw** [comment]
Not completely, but I think you're very close. 

In the QGIS-Project-File there is a tag <previewExpression>. In the original .qgs-File this tag is filled with field called "display expression" defined in the Edit-Widget-Properties. After using QFieldSync the content of this tag is lost. If I refillthe content of this tag...everything works fine. 

So before using qfieldsync the tag looks like this:
<previewExpression>observer</previewExpression>
After using qfieldsync the tag looks like this:
<previewExpression></previewExpression>

This picture shows the settings in the Widget Properties for the relation reference widget AFTER use of QFieldSync. Notice how the _**display expression**_ is empty:
![display expression_notcorrect](https://cloud.githubusercontent.com/assets/20398621/23356518/78ece680-fcda-11e6-9847-80914006219b.JPG)

This is how it should look like if QFieldSync works (I think):
![display expression_correct](https://cloud.githubusercontent.com/assets/20398621/23356517/78ea66bc-fcda-11e6-90a1-eefde129ade2.JPG)

**Comment by saemiw** [comment]
Attached you find the project where the problem occurs. All layers (but 2) contain a field "observer" which is a reference to the layer "add_observer". Here is what I do to encounter the problem.

1. open the attached QGIS project
2. set it offline using QField Sync Plugin
3. Open the offline-Project and check if the **_display expressions_** of the field "observer" (see printscreens above) are empty. They should be.

I noticed that when I open the offline project on my computer and re-define the **_display expression_** from QGIS for 1 layer, it somehow also solves the problem for the other layers.

I use QGIS 2.18.4 and QFieldsync 0.9.2

**Comment by m-kuhn** [comment]
This should be fixed in 2.18.5 (upcoming nightly build). Sorry for the inconvenience.

**Comment by saemiw** [comment]
Thanks for the fast fixing, nothing to be sorry about.

**Comment by meyerlor** [comment]
this is again an issue with QGIS 3.14 / Qfield Sync 3.1.10 / Qfield 1.5.3
