### ISSUE TITLE
SVG symbols are not packaged

### ISSUE THREAD

**Issue by 3nids** [opengisch/qfieldsync#33]
If you have a layer with SVG symbols, they are not packaged to QField and you end up with interrogation marks in the map.
It would be nice to have a new tab in QFieldSync to choose folders which would be packaged (i.e. copied along the project).
Relative paths should be respected so the layer would be rendered as expected.

**Comment by 3nids** [comment]
coming on this one again
there is a path resolving that points to the source location of the SVG.
The idea would be to detect the symbols having a relative path (and not starting with .. I guess) with the API, copy them along while preserving the structure of directories (so relative path would remain)

**Comment by 3nids** [comment]
mail sent to Martin to get some ideas

**Comment by 3nids** [comment]
there is now the embedded SVG symbols in the project file 
see https://github.com/qgis/QGIS-Enhancement-Proposals/issues/126

@gacarrillor is it sufficient for you?

**Comment by gacarrillor** [comment]
I think that QEP would be enough, right!

**Comment by 3nids** [comment]
It is already implemented in 3.6!

**Comment by gacarrillor** [comment]
Didn't know about it, we'll test it and let you know.

**Comment by gacarrillor** [comment]
@3nids We tested the SVG packaging in the QGIS project. In fact, it solves the requirement we had concerning SVG for styles in QField. Thanks for letting us know!

**Comment by 3nids** [comment]
great, I will tag this as won't fix then

**Comment by m-kuhn** [comment]
@3nids / @gacarrillor can you write a couple of sentences for the qfield documentation?

**Comment by jhonalex06** [comment]
Done 

references: https://github.com/opengisch/QField-docs/pull/29/files
