### ISSUE TITLE
Map themes are corrupted when using "offline editing" option 

### ISSUE THREAD

**Issue by saemiw** [opengisch/qfieldsync#34]
1. In my QGIS project I set up a handful of Map themes.
2. Then I use QFieldSync to set all layers offline
3. After step 2 the names of the defined map themes are still present but they don't contain any layers.

I use QFieldSync 1.0.0 and QField 0.9.5. (but this is not related to QField as it is already wrong in the qgs-project file when looking at it with desktop QGIS).

**Comment by m-kuhn** [comment]
Should be fixed with QGIS 2.18.5
