### ISSUE TITLE
Export MBTiles to QField QGIS v3.22.0

### ISSUE THREAD

**Issue by alpinfra** [opengisch/qfieldsync#341]
QGIS 3.22.0 crashes when exporting a project containing MBTiles to QField.
Does not happen with version 3.16.4, here the export finishes successfully

**Steps to reproduce the issue:**
1. Install Plugin QFieldSync
2. create or load MBTiles file
3. Choose Package Project for QField
4. Click on Create
5. QGIS crashes, but not immediately

**QGIS Version:**
3.22.0

Desktop OS: Windows 10, v 21H1, Build 19043.1348
Error Messages: None, QGIS freezes/crashes

**Comment by m-kuhn** [comment]
Are there any error messages available?
Would you able to provide a minimal project/dataset to reproduce the issue?

**Comment by suricactus** [comment]
QFieldSync version? There is quite a lot changed between latest stable and latest experimental. Can you try with both?

**Comment by alpinfra** [comment]
`Crash ID: [69743e41dbb4efc045eac61a8f81a6718f59c39b](https://github.com/qgis/QGIS/search?q=69743e41dbb4efc045eac61a8f81a6718f59c39b&type=Issues)


**Stack Trace**

QgsDefaultRasterLayerLegend::createLayerTreeModelLegendNodes :
QgsLayerTreeModel::addLegendToLayer :
QgsLayerTreeModel::refreshLayerLegend :
QgsLayerTreeModel::layerLegendChanged :
QObject::qt_static_metacall :
QObject::qt_static_metacall :
QObject::qt_static_metacall :
QgsRasterLayer::setRendererForDrawingStyle `:`
QgsRasterLayer::setDataProvider :
QgsRasterLayer::readXml :
QgsMapLayer::readLayerXml :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :



**QGIS Info**
QGIS Version: 3.22.0-Bia?owie?a
QGIS code revision: d9022691f1
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.2
Running against GDAL: 3.3.3



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043`

**Comment by alpinfra** [comment]
I just tried to upload a minimalistic project file as a ZIP, but it won't let me - marked as "is not included in the list" in red letters down below :(

**Comment by alpinfra** [comment]
> QFieldSync version? There is quite a lot changed between latest stable and latest experimental. Can you try with both?

tested with the latest stable, not the experimental plugin. 
Also, it works with the latest QGIS LTR 3.16.13

**Comment by suricactus** [comment]
I am afraid there is not much that can be done here without a test project. Also, being able to work on 3.16.13 most probably means it is a QGIS problem.
