### ISSUE TITLE
Cannot upload local QfieldSync directory

### ISSUE THREAD

**Issue by suricactus** [opengisch/qfieldsync#349]
> I have a bug when trying to convert a project into cloud project
> 
> When I want to convert currently open project to cloud project, if I use the button with three dots, then select one folder in my computer, I have a message saying that "The entered path does not contain a QGIS project file yet" then I click "ok" and it send me back to the folder selection (see image below)
> 
> ![cannot upload local QfieldSync directory](https://user-images.githubusercontent.com/26409106/146552152-6028460c-9d97-4580-b63b-c8b6bc073260.png)
> 
> However, if I write the folder path by hand instead of using the three dots button, then the button "create" become enabled. 
> 
> ![manual entry of the directory](https://user-images.githubusercontent.com/26409106/146552978-2e611ac1-6690-4547-8605-90616b41b7bf.png)

Initially reported as [#185](https://github.com/opengisch/qfieldcloud/issues/185) by @MMR100

**Comment by BoswachterMarc** [comment]
I experienced the same problem using qgis 3.22.2-Białowieża and the latest QFieldSync plug-in.
My workaround was using the manually option 'create a new empty QFieldCloud project'. Converting the currently open project to cloud project was an easier option (I remember it worked before).

![afbeelding](https://user-images.githubusercontent.com/57868975/149190898-f079f125-8d37-4b71-b3a6-b55b73112823.png)
