### ISSUE TITLE
Configuration is lost when opening project with an older QGIS version

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/qfieldsync#351]
Hello, 

I think it could be very interesting to save the configuration of QFIELD Sync in the project, then, when we can share the same project, on different computers (for different purposes) without losing the registered configuration.

 > Saving the actions on each layer (offline / copy / etc.)
 > Saving the name of pictures with their name expression.

Thank you for your attention, 

Regards

**Comment by suricactus** [comment]
Can you provide more details? Theae configurations are savwd withing the project so they should be available if you open the se projwct file on a different QGIS machine with the samw or newer QGIS version.

**Comment by Ipickedausername** [comment]
Hello,

I sent the project to someone else, when we opened it on his computer, the parameters of QFIELD Sync were reset. 
I made few tests on my computer. If I change the QGIS version, QFIELD Sync kept the parameters. So I'll have to check again on another computer.

**Comment by Ipickedausername** [comment]
I made few tests, each time I open the projet on another version of QGIS, all parameters on QFIELD Sync are lost.

**Comment by m-kuhn** [comment]
Which versions of qgis are we talking about?

**Comment by Ipickedausername** [comment]
I opened it with QGIS 3.16.15, then opened a new project on QGIS v3.22.2 and open my project. 

I just tred again, after your message, and all parameters where keps. I don't understand how it happened (several times). 

For now I can't help more about this issue, but, I'll redo everything and check better, step by step. Then, I hope I can give more informations.

**Comment by suricactus** [comment]
@Ipickedausername please note that configuration between 3.22 and 3.16 are only forwards compatible, but not backwards compatible. This is an issue that you might experience with some other QGIS plugins too.
