### ISSUE TITLE
Error when trying to import table with relationreference field with NULL value

### ISSUE THREAD

**Issue by soester** [opengisch/qfieldsync#359]
There is an error when trying to sync back to Postgres 

Error Log:
'2022-01-20T13:45:51     CRITICAL    Layer v_erfassung_messung_messstelle : PostGIS error while adding features: ERROR: insert or update on table “od_messung_messstelle” violates foreign key constraint “od_messung_messstelle_id_messtelle_teilobjekt_fkey”
             DETAIL: Key (id_messtelle_teilobjekt)=(0) is not present in table “vl_messstelle_teilobjekt”.'

Althought the Field Value displayed in QGIS is 'NULL' Qfieldsync interpretes it as '0'

Qfieldsync 3.4.2 

Were there any changes in the current version?

**Comment by suricactus** [comment]
Nope, QFieldSync 3.x has no active development since a few months. Can you try with the latest experimental version? Also, can you please share your QGIS version.
