### ISSUE TITLE
Error when lauching QField Sync

### ISSUE THREAD

**Issue by Romain076** [opengisch/qfieldsync#36]
I've got this error when i want to launch QField Sync plugin.
Can you help me please?

Une erreur est apparue lors de l'exécution du code Python :

Traceback (most recent call last):
  File "C:/Users/rvaillant/.qgis2/python/plugins\qfieldsync\qfield_sync.py", line 268, in show_project_configuration_dialog
    dlg = ProjectConfigurationDialog(self.iface, self.iface.mainWindow())
  File "C:/Users/rvaillant/.qgis2/python/plugins\qfieldsync\dialogs\project_configuration_dialog.py", line 56, in __init__
    self.reloadProject()
  File "C:/Users/rvaillant/.qgis2/python/plugins\qfieldsync\dialogs\project_configuration_dialog.py", line 86, in reloadProject
    for theme in self.project.mapThemeCollection().mapThemes():
  File "C:/Users/rvaillant/.qgis2/python/plugins\qgis2compat\apicompat\qgsproject.py", line 11, in visibilityPresetCollection
    return self.visibilityPresetCollection()
AttributeError: 'QgsProject' object has no attribute 'visibilityPresetCollection'

Version de Python :
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

Version de QGIS :
2.8.9-Wien Wien, 26c3ece

Chemin vers Python : ['C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python/plugins\\processing', 'C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python', u'C:/Users/rvaillant/.qgis2/python', u'C:/Users/rvaillant/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win32.egg', 'C:\\PROGRA~1\\QGISWI~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1\\bin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win32.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\python_dateutil-2.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\pytz-2014.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win32.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', u'C:/Users/rvaillant/.qgis2//python', 'C:/Users/rvaillant/.qgis2/python/plugins\\NNJoin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\qgis-ltr\\python\\plugins\\fTools\\tools', 'C:/Users/rvaillant/Desktop/Rollot']

**Comment by m-kuhn** [comment]
Please update to QGIS 2.18.

**Comment by Romain076** [comment]
I have updated to QGIS 2.18.4 and now, i have this message quand i want to install this plugin...
Can you help me please? I didn't find any solutions on the web for now

![image](https://cloud.githubusercontent.com/assets/26646129/24350039/16ef29da-12e1-11e7-9072-130644a0d18f.png)

**Comment by m-kuhn** [comment]
Did you install qgis2compat?

**Comment by Romain076** [comment]
Yes this was the first thing I've done.
In this message, it's written that this plugin is corrupted, I don't understand...

**Comment by marc-p** [comment]
Romain076 you probably have this working already but I am posting for the benefit of those who might search this up. I think that after installing QGis2compat you have to restart QGis for the plugin to work. I had the same problem and after restarting it went away. Or some other magic, but it resolves itself.
