### ISSUE TITLE
Qfield cloud log in issues

### ISSUE THREAD

**Issue by joekbullard** [opengisch/qfieldsync#388]
Apologies if this isn't the right place to post, I'm not sure if this is a qfield cloud issue or sync issue.

I've recently joined the Qfield cloud invite beta, I have created a profile on the web application service and can log in. I have also installed the experimental version of Qfield sync.

* OS: macOS Big Sur
* QGIS Version: 3.22.3-Białowieża
* Qfield sync version: 4.0.0-BETA18

Firstly, when selecting the QField Cloud Project Overview menu the default window behaviour puts the login dialog popup to the back (behind QGIS main window and the projects overview menu). Once I attempt to login with my credentials I receive a login failed message - I have tried this with several passwords to be sure. Note from the images below, the projects overview window changes in color tone after the failed login attempt.

<img width="643" alt="Screenshot 2022-02-16 at 22 57 21" src="https://user-images.githubusercontent.com/35529853/154371535-d0f8180b-f821-4061-a247-e8d887717ab9.png">

<img width="642" alt="image" src="https://user-images.githubusercontent.com/35529853/154371673-0f13adc7-db9d-402c-b4e9-888dc773cab1.png">

**Comment by suricactus** [comment]
Please upgrade to QFieldSync BETA 19, see the full discussion here. https://github.com/opengisch/QField/discussions/2526
