### ISSUE TITLE
[Bug] Install Qfield Sync cause duplicate information in Offline Editing Plugin

### ISSUE THREAD

**Issue by jonnyforestGIS** [opengisch/qfieldsync#39]
**OS:** Windows 7 64-bits
**QGIS Version:** 2.18.9 64-bits

Hi guys,
After install QGIS2compat and Qfield Sync plugins i notice that after we insert new rows using the plugin of Offline Editing we have duplicate rows for each new insertion.

**Workflow:**
1) Install QGIS2compat and QField Sync;
2) Open DB Manager
3) Create table with id serial / name text. Select type of geometry (e.g. poin) and add a srid.
4) Make Offline Editing
5) Add a new point and save in the spatial table offline and save.
6) Syncronize.
7) Duplicate row with same geographical information.

Try the same workflow without install the plugins and works fine.

Please someone try for other Operating Systems the same behavior. I will try to test in LTR in Windows 7 as well.

Best regards,
João Gaspar

**Comment by zakigates** [comment]
same issue here.

**Comment by jonnyforestGIS** [comment]
@zakigates you use as well the Windows OS or you are reporting with another OS?

**Comment by zakigates** [comment]
I use Windows OS 7-32-bits

**Comment by zakigates** [comment]
The problem of duplicated data is solved for me, but aparently I did nothing special I've just created a new project and followed the instructions they discribed in the doc and it works very well. I added new  features in QField and when I synchronized with QGIS I got just what I recently added.
