### ISSUE TITLE
Can't upload projet to cloud

### ISSUE THREAD

**Issue by katagen** [opengisch/qfieldsync#391]
I can't upload any projects to qfieldcloud.
When I sync, I always have this error:
![error](https://user-images.githubusercontent.com/37768582/155674410-06cfeae2-41fa-41ac-a9f5-09892a29b112.JPG)
![error1](https://user-images.githubusercontent.com/37768582/155674553-13205669-183a-419b-8f0a-f5c45f3a20f4.JPG)

**Comment by suricactus** [comment]
Can you provide a little bit more details. What QFieldSync version are you using, what QGIS version, what platform, if possible - share your project?

**Comment by katagen** [comment]
I use 4.0.0-BETA19 of Qfieldsync, on 3.16.10 of QGIS.
It's happen on all my projects... here one for exemple!
[Test.zip](https://github.com/opengisch/qfieldsync/files/8142222/Test.zip)

**Comment by katagen** [comment]
Did you find the reason?

**Comment by suricactus** [comment]
No need to try anymore, the bug has been fixed in the referenced PR https://github.com/opengisch/qfieldsync/pull/394 . It was 3.16 specific.
