### ISSUE TITLE
Python error with layer basemap feature

### ISSUE THREAD

**Issue by VxTedxV** [opengisch/qfieldsync#40]
When trying to create a basemap from a raster layer, I get the error described above (occurs when packing project to QField). Tried with .vrt and .ecw rasters.
QGis 2.18.4 / QFieldSync 1.0.0

`Traceback (most recent call last):`
`File "C:/Users/***********/.qgis2/python/plugins\qfieldsync\dialogs\package_dialog.py", line 113, in package_project offline_convertor.convert()`
`File "C:/Users/***********/.qgis2/python/plugins\qfieldsync\core\offline_converter.py", line 99, in convert self.project_configuration.base_map_mupp)`
`File "C:/Users/***********/.qgis2/python/plugins\qfieldsync\core\offline_converter.py", line 161, in createBaseMapLayer alg = processing.Processing.getAlgorithm('qfieldsync:basemap').getCopy()`
`AttributeError: 'NoneType' object has no attribute 'getCopy'`

**Comment by m-kuhn** [comment]
Can you check that

* the processing plugin is enabled
* in the options of the processing plugin, the QFieldSync provider is enabled

and report back if that solves something for you

**Comment by VxTedxV** [comment]
That's it ! Thanks.
PS : need to restart QGis to work.

**Comment by m-kuhn** [comment]
I'll leave this open as it needs to be easier.

Either enable automatically or at least a helpful message.
