### ISSUE TITLE
QFieldSync does not copy SVG files to QFieldCloud

### ISSUE THREAD

**Issue by jpdupuy** [opengisch/qfieldsync#407]
Hello,

The project I created refers to SVG files in the project file folder.

I am currently working with QGIS 3.22.4 LTR and QFieldSync 4.0.0

Creating a new project file to QFieldCloud (convert the currently opened project to the cloud = recommended), I noticed that the qgs and gpkg files are transferred to the cloud, but the SVG files are not).
Workaround : I had to copy the SVG files to the C:\users\<username>\qfiled\cloud\<projectname>\<svgfiles>

Could you please fix this issue so that you do not have to copy manually the SVG files, or tell me if there is another way to address this issue.

**Comment by Diethart123** [comment]
That's right - the original SVG symbols are replaced with question marks
![Symbolproblem](https://user-images.githubusercontent.com/76101669/161030101-0e3d4fae-1783-4cf3-853a-7c0fd8fc3802.JPG)

**Comment by suricactus** [comment]
Hey, @jpdupuy if you place your SVGs in `svgs` directory within your project directory, then configure `svgs` as "Attachment directory" and then sync it with QFieldCloud, it should work.

This is coming with the next QFieldSync.

More here https://github.com/opengisch/qfieldsync/pull/449

**Comment by jpdupuy** [comment]
Hi, @suricactus many thanks for the information. I shall test it for sure. It should speed up the file transfer.
