### ISSUE TITLE
Impossible to sync offline from Postgis

### ISSUE THREAD

**Issue by cazitouni** [opengisch/qfieldsync#410]
Hello, 

I open an issue beacause since I upgrade to the latest version of the qfield sync plugin it's now impossible for me to offline sync layer from my Postgis database.

The plugin told me that the layer was not found and just push them directly from source instead of copying them in a gpkg.
The layer is of course accessible in the project and configured for offline editing in the cable sync panel.

If I use an old version of the plugin Qgis just crash. 

I use Qgis 3.24 and the latest stable version of the plugin.
After some tests the problem happens but more randomly with the LTR 3.22.

**Comment by suricactus** [comment]
Can you provide a test project, seems your usecase is quite specific.

**Comment by cazitouni** [comment]
Found the issue. It was a buggy geopackage that I use to store lists and photos. I move everything into postgis and it now works
Thanks you for your answers. 
Kind regards, Clément
