### ISSUE TITLE
Impossible to sync  ; same issue in the offliene plugin

### ISSUE THREAD

**Issue by Amphibitus** [opengisch/qfieldsync#411]
I work with QGIS 3.24.1 and the newest Qfieldsyc Plugin 4.0.0

![grafik](https://user-images.githubusercontent.com/7237786/162023738-5ff9816e-86fe-49fa-8b70-d46cf1bb6481.png)

After start "Offlinesync" i get an Error Message

![grafik](https://user-images.githubusercontent.com/7237786/162023873-6b5fd195-a9dc-45ae-8b7f-70d3950674b0.png)

the file data.gpkg is created, the layer tabels too but no data is transfered in the table kk_lsch
![grafik](https://user-images.githubusercontent.com/7237786/162024500-cad4d845-8167-4c10-9181-80c9415d072a.png)

![grafik](https://user-images.githubusercontent.com/7237786/162024676-ac450b67-b19b-4c48-879b-4eba0648259d.png)

Layer "kk_lsch" is only linked with the datasource

![grafik](https://user-images.githubusercontent.com/7237786/162025955-ee39cc5c-abe2-4199-b7e6-f3f6f278ddc6.png)

Now I see that the offline Plugin doesn't work correctly either and have the same issue

It looks like, only the first table is exported. If I delete "kk_lhal" or change the order, the export works fine.

if i change the export destination to Spatialite it also works well

**Comment by suricactus** [comment]
Quite interesting issue. Is there any chance you provide a test project?

**Comment by suricactus** [comment]
As mentioned in https://github.com/opengisch/qfieldsync/issues/417 , these features are refering to the same issue. Fix is coming with the next release.
