### ISSUE TITLE
ERROR with expression "get_feature_by_id", different line number via QField Cloud

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/qfieldsync#427]
Hello, 

I'm loading a list in a field, filtered by this expression :

`CASE 
	WHEN string_to_array(attribute(get_feature_by_id('OPTIONS',0),'Compart'), '-')[0] = 0 THEN
		string_to_array("Compart", '-')[0] <> 0
	ELSE
		string_to_array("Compart", '-')[0] = string_to_array(attribute(get_feature_by_id('OPTIONS',0),'Compart'), '-')[0]
END`

When the first number of "Compart" (in layer OPTION") = 0 then load everything except the one starting with a '0'. 
Else, load the results which start by the selected number. 

Everything is working when I'm exporting the project with cable. 

Here two pictures of the working list. 

![working_2](https://user-images.githubusercontent.com/72577399/167308383-818fbde3-96ad-40b9-a776-20aa4ca20564.jpg)
![working_1](https://user-images.githubusercontent.com/72577399/167308378-23321774-0a23-4eda-a477-f44c23411e8e.jpg)

But, when I'm exporting the project on cloud, this is not working anymore. 

![Not_working-1](https://user-images.githubusercontent.com/72577399/167308555-940723c5-f22d-4cfc-9022-8806598649e7.jpg)

The list is loaded from another layer : 

![Compartiment](https://user-images.githubusercontent.com/72577399/167308566-09d7f21a-aa3c-46f2-9cae-8ea502eac321.jpg)

To ensure it is working, I have to change the expression like this : 

`CASE 
	WHEN string_to_array(attribute(get_feature_by_id('OPTIONS',1),'Compart'), '-')[0] = 0 THEN
		string_to_array("Compart", '-')[0] <> 0
	ELSE
		string_to_array("Compart", '-')[0] = string_to_array(attribute(get_feature_by_id('OPTIONS',1),'Compart'), '-')[0]
END`

To sum up, I'm changing the ID in `get_feature_by_id` from 0 to 1. 
In the first case, the corresponding row is 0, in the second case it is . 

I can't change my project to make it work on the cloud, because I'll not be able to use it on QGIS anymore. 

Do you know where is it coming from ? I guess there is en error somewhere. 

Thank you !

**Comment by suricactus** [comment]
First, feature IDs in QGIS are unstable across sessions. There are a few cases where you can depend on them after restart, e.g. when they are specific type of int.

One scenario where feature IDs are usesless is in offline editing. Noone can guarantee what is going to be the new value after offline editing your layer. Therefore I would suggest you don't use `get_feature_by_id`, but get the feature by a stable attribute.
