### ISSUE TITLE
can't install qfieldsync, "cannot import name QtWidgets"

### ISSUE THREAD

**Issue by libegon** [opengisch/qfieldsync#43]
Cette extension est corrompue. Python dit:
cannot import name QtWidgets

**Comment by m-kuhn** [comment]
Did you install qgis2compat?

**Comment by libegon** [comment]
Yes I did, but this error appeared when I tried to install it in the qgis plugin manager.
So I downloaded the plugin from http://plugins.qgis.org/plugins/qfieldsync/ and copied the file in /usr/share/qgis/python/plugins and this error disappeared.
Sorry for the bother.

**Comment by m-kuhn** [comment]
Glad it works for you.

If someone else steps into this issue, it would be great if you could try to restart QGIS at this point and check if it works then.

**Comment by jonnyforestGIS** [comment]
Hi guys,
same issue with 2.18.13 in Windows 7 SO 64-bits.

So if i try to install from plugin manager i have the same error like @libegon but if we copy to the plugins folder and star QGIS 2.18.3 works fine without errors.

Regards,
João

**Comment by Marwe** [comment]
I have the same issues and cannot properly install QField Sync currently. Tried on linux (ubuntugis unstable), same appears on Windows install (QGIS standalone and OSGEO4W netinstall).
QGIS versions were 2.18.x.

Here is what happens:
* install QField Sync - fails due to missing qgis2compat dependency (message appears: good)
* install qgis2compat (v. 0.4.6)
* restart - Error at startup, breaks processing toolbox:
> ImportError: cannot import name uic 
> Traceback (most recent call last):
>   File "/usr/share/qgis/python/plugins/processing/gui/ProcessingToolbox.py", line 31, in 
>     from qgis.PyQt import uic
> ImportError: cannot import name uic
> 
> Python-Version: 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609] 
> QGIS-Version: 2.18.15 Las Palmas, ac2d111

* if you install qfield anyway (eg. directly after qgis2compat), you get the Error:
> cannot import name uic

Will try install via commandline now.

**Comment by Marwe** [comment]
Installing qgis2compat from git yields same error at startup

> ImportError: cannot import name uic 
> [...]
>   File "/usr/share/qgis/python/plugins/processing/gui/ProcessingToolbox.py", line 31, in 
>     from qgis.PyQt import uic
> ImportError: cannot import name uic

**Comment by Marwe** [comment]
There is a duplicate, corresponding bug for qgis2compat:
https://github.com/opengisch/qgis2compat/issues/3

**Comment by Marwe** [comment]
OK, there is a recent PR "Drop qgis2compat dependency"
https://github.com/opengisch/qfieldsync/pull/58

So I guess we have to wait for this one. Sorry for the noise.

**Comment by m-kuhn** [comment]
@Marwe can you test the latest release 1.1.0?

Please uninstall qgis2compat and enable "experimental" plugins.

Thanks

**Comment by Marwe** [comment]
Could not yet find it in Extensions nor http://plugins.qgis.org/plugins/qfieldsync/
Tried git checkout directly (https://github.com/opengisch/qfieldsync/tree/master/qfieldsync), but then get the following at qgis startup. Do I miss some compilation step with the Makefile maybe?

<pre>
Konnte Erweiterung qfieldsync nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

IndexError: list index out of range 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/martin/.qgis2/python/plugins/qfieldsync/__init__.py", line 34, in classFactory
    from qfieldsync.qfield_sync import QFieldSync
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/martin/.qgis2/python/plugins/qfieldsync/qfield_sync.py", line 46, in 
    from qfieldsync.dialogs.package_dialog import PackageDialog
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/martin/.qgis2/python/plugins/qfieldsync/dialogs/package_dialog.py", line 56, in 
    FORM_CLASS = get_ui_class('package_dialog')
  File "/home/martin/.qgis2/python/plugins/qfieldsync/utils/qt_utils.py", line 47, in get_ui_class
    return [obj for _, obj in inspect.getmembers(m) if inspect.isclass(obj) and obj.__name__[:3] == 'Ui_'][0]
IndexError: list index out of range


Python-Version: 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609] 
QGIS-Version: 2.18.15 Las Palmas, ac2d111 
</pre>

**Comment by m-kuhn** [comment]
For using a git checkout, one needs to also run `make` first.
Anyway, the new version should be available now.

**Comment by Marwe** [comment]
I installed 1.1.1 without problems, and it works (Tried the export successfully).
I don't know about QGIS 2.14 LTR, but at least for 2.18 everything seems to be fine.
Thank you very much!
