### ISSUE TITLE
Consider adding some filters to the qfield layers list in project properties

### ISSUE THREAD

**Issue by nyalldawson** [opengisch/qfieldsync#438]
For large projects, the layers table in the qfield tab of project properties becomes extremely hard to navigate. I'd love to see some filters added here, specifically:

1. A checkbox for "show visible layers only", which would hide any non-visible/checked layers from the list
2. A freeform "text filter" box, which would filter the table by matching against any part of the layer name / source.

**Comment by suricactus** [comment]
Implemented in https://github.com/opengisch/qfieldsync/pull/600#issuecomment-2311779673 .
