### ISSUE TITLE
Import Local project: missing Project-File

### ISSUE THREAD

**Issue by dan-gis** [opengisch/qfieldsync#444]
- Trying to Import project from folder. All necessary data (including .qgs) is imported in: 
...\Tablet\Android\data\ch.opengis.qfield\files\Imported Projects\ [Projectfolder]
- In Qfield 2.2.0 under "Local Projects & Datasets" the Project doesn't appear. 
- in Qfield under "Imported Projects" the Project-folder with the data appears, but without the .qgs - File (but it's there when checking in Explorer).
- Same procedure / project with Qfield dev. (c97101) works fine.

Problem with file-names or permissions?

![Tablet_Qfield_Importet_Project](https://user-images.githubusercontent.com/78069382/179621524-1720665c-b49a-4e50-8f69-7fe4f6f0dc93.PNG)
![Qfield_2 2 0_Import_Projects](https://user-images.githubusercontent.com/78069382/179621527-8a06fa98-13ea-4ba2-ae22-5db23e7c8f34.jpg)
![Qfield_dev_Import_Projects](https://user-images.githubusercontent.com/78069382/179621531-b030b913-b572-4e93-ba03-7c2e9f59f235.jpg)

**Comment by nirvn** [comment]
Fixed in upcoming 2.2.1

**Comment by dan-gis** [comment]
Hi Mathieu
Thank you for commenting and closing #444. Is there a workaround so I can use my projects? Changing names or something? Thank you! Dani

**Comment by nirvn** [comment]
@dan-gis , yes, you can change your project file name from `7106.10_WikoBE_013_Sta...qfield.qgs` to `7106-10_WikoBE_013_Sta...qfield.qgs` and it'll work. Basically make sure there are not dots in your file name (other than the .qgs suffix).
