### ISSUE TITLE
Possibility to copy directly the packaging in the directory QField of the device

### ISSUE THREAD

**Issue by veroniqueC** [opengisch/qfieldsync#445]
Hy,

Is it planned to develop the possibility of copying the export packaging  directly to the smartphone/device in the Qfield repertory (without having to copy/paste manually)? Even if now there is the cloud...

Thanks

**Comment by suricactus** [comment]
Not sure what exactly you mean, but this is exactly why QFieldCloud exists, so you don't need to manually copy anything anywhere.
