### ISSUE TITLE
QGS project export duplicates composer

### ISSUE THREAD

**Issue by nicolasmcfadden** [opengisch/qfieldsync#45]
Hello,

I'm working on a .qgs project using geopackages for field work. When exporting the main QGS project to an offline project, the composers of the main QGS project are duplicated. I therefore get an extra composer for each time I export the project to an offline project.

Expected behavior: Export doesn't create duplicate composers in source project

QGIS version: 2.18.11
QField Sync 1.0.0

**Comment by 3nids** [comment]
this has been reverted by 937ec7dfcd4140750c06cb93fb277d071de74ca0
this would need to be checked again
