### ISSUE TITLE
Missing data layers on export

### ISSUE THREAD

**Issue by r-gibs** [opengisch/qfieldsync#450]
When exporting a project using QField Sync with QGIS 3.22, data from layers within the data geopackage go missing. 

These layers appear in the shape list in the exported project, are editable, and new features appear on the map. However, previously existing data points are absent in the exported project.

**Comment by m-kuhn** [comment]
Did this also happen with older QGIS versions or is this related to QGIS 3.22?
Can you provide a sample project to reproduce the issue?

**Comment by r-gibs** [comment]
I started running into the issue this year. However, it's not isolated to QGIS 3.22, I tried it with an older version (QGIS 3.18) and have the same problem.
It doesn't happen every time I export but appears to affect the same layers.

It's a client project, I'll check if I can send it. Can I email it privately to you?

**Comment by hertzogmarie** [comment]
I have exactly the same problem. Would be glad if you could update if there's a solution to this problem. I also tried to downgrade to QGIS 2.18.1 Las Palmas, but there the same problem occurs. Last autumn it worked all fine. Thanks in advance.

**Comment by suricactus** [comment]
A sample project would help a lot. 

Note versions earlier than QGIS 3.16.10 are not supported.
