### ISSUE TITLE
Check if copy is needed for big files (e.g. basemaps)

### ISSUE THREAD

**Issue by saemiw** [opengisch/qfieldsync#46]
It would be nice to have an option that checks whether layer that should be copied already exist (in the same state) at the destination path. Or maybe an option that does not actually copy specified layers but adds them in the .qgs-Project file as a layer that is present. 

I am thinking mainly about base maps that can be very large and take many minutes to copy. We used the sync plugin during field work every evening to set the project offline for next days work. The acutal data are very small in size, but the basemap always took very long to copy to the offline project. QFieldSync allows to "remove" some layers but then of course you also don't have them on QField.

**Comment by m-kuhn** [comment]
Would a new option "Copy if missing" be what you are looking for?

**Comment by saemiw** [comment]
Yes this would be perfect.

**Comment by saemiw** [comment]
This seems to work! Thanks for the very helpfull addition. Saves a few minutes in case of large basemaps.
