### ISSUE TITLE
QGIS crashes during QFieldSync-export of a postgresql-materialized-view-layer

### ISSUE THREAD

**Issue by koenigherford** [opengisch/qfieldsync#467]
It seems that qgis-crashes are caused by cable-export of a project which conatins (only) a materialized-view-layer.

I have a postgresql-materialized view (which dissolves  lots of polygons to some outlines). While exporting this project with this layer to a local folder (default styling) QGIS crashes. 

In my settings only
![grafik](https://user-images.githubusercontent.com/28433436/193027663-53045359-4ebc-418e-833e-07c6f938f0d2.png)
-actions are available (although materialized views are not editable). Maybe better "copy" shall be available ???

If the layer is exported to a local gpkg before export (and the postgresql-connection is removed) QGIS does not crash.

Stack Trace
QgsPolygon::toCurveType :
QgsVectorDataProvider::convertToProviderType :
QgsVectorLayerEditBuffer::commitChanges :
QgsVectorLayer::commitChanges :
QgsOfflineEditing::convertToOfflineLayer :
QgsOfflineEditing::convertToOfflineProject :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.2-Bia?owie?a
QGIS code revision: 1601ec46d0
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by m-kuhn** [comment]
Can you try to export this layer with the qgis offline editing (core) plugin and can you try with the latest patch version?

**Comment by koenigherford** [comment]
Updated QGIS to 3.26.3 and tried to export it by offline-editing-plugin to local harddisc.

Result was crash too (see below)

Althrough a access violation is reported the layer can be imported from postgres-db. Because the table is a "materialized view" modifications of this data are not possible in QGIS.

Issue was reported on qgis-issues-page: https://github.com/qgis/QGIS/issues/50466

**Comment by suricactus** [comment]
Upstream issue has been closed, I am closing this one too.
