### ISSUE TITLE
Possible not to include _qfield in the project name when exporting the project?

### ISSUE THREAD

**Issue by 9ls1** [opengisch/qfieldsync#470]
Is it possible to tell QField Sync **not** to include **_qfield** in the QGIS-project name during export?
E.g. xxxx.qgs is named xxxx_qfield.qgs in the ...\export\xxxx-folder created with Cable Export . 
I first posted this question in the QField Discussions [https://github.com/opengisch/QField/discussions/3412](https://github.com/opengisch/QField/discussions/3412), but it may be better to post it here (as well)?

Using QGIS 3.26.3 and QField Sync 4.2.0.

**Comment by suricactus** [comment]
Hey, @9ls1 , as I already answered you in the other thread, it is not planned to remove the `_qfield` suffix. Please follow the alternative solution I proposed to you.
