### ISSUE TITLE
when synchronizing changes from qfield back to the original project, errors in file copy abort the process.

### ISSUE THREAD

**Issue by alansaviolobo** [opengisch/qfieldsync#471]
Steps to reproduce:
1. export a project to qfield that includes photos.
2. make changes in qfield ( add a photo ).
3. sync the changes back to the original project.

if there is a file with the same name in the destination folder, then the process gets aborted with the message "X and Y are the same files.

It would be ideal to silently proceed or notify the issue in the console.

**Comment by suricactus** [comment]
Hi @alansaviolobo . This is with, or without QFieldCloud?

**Comment by alansaviolobo** [comment]
No cloud. Wire copy

**Comment by alansaviolobo** [comment]
This basically occurs when the main project (.qgz) and the exported project (_qfield.qgs) are placed in the same folder.

**Comment by suricactus** [comment]
This is dangerous behaviour to have them in the same directory, why would you need that? QFieldSync always assumes the destination directory is empty and even might try to delete the existing files. If you are trying to save space/copy time, there should be other workarounds.

A sensible files structure in most of the cases is:
```
myproject/package/project_qfield.qgs
myproject/files/project.qgs
```

**Comment by alansaviolobo** [comment]
I was working with the foll folder srtucture:
Project/my-proj.qgz
Project/export/my-proj_qfield.qgs

Which creates two copies of the DCIM folder(photos). This is what i was
trying to avoid.

**Comment by suricactus** [comment]
Probably worth trying to achieve similar results if you remove the `DCIM` directory from the "Attachment dirs" configuration in QFieldSync and symilink to the master DCIM?

**Comment by alansaviolobo** [comment]
I dont remember seeing such an configuration in qfield sync. Let me check
again.

Also, i sync all the files using dropbox which i think doesnt support
symlinks.

**Comment by alansaviolobo** [comment]
I see this option now. appears to be a new option. How do I go about using this ?

![attachment directories](https://user-images.githubusercontent.com/1202289/197670941-bf01f105-2168-468e-bfca-20ea46e8b6a4.png)
