### ISSUE TITLE
Qfieldsync prevents resizing project properties dialog

### ISSUE THREAD

**Issue by Scolopax** [opengisch/qfieldsync#475]
When qfieldsync plugin is enabled in Qgis, it is no longer possible to resize the "Project Properties" dialog windows. It become critical when your sceen resolution is under 768 in height : "OK", "Cancel", "Apply" becomes unaccessible and QGIS freeze if you try to resize dialog.

Steps to reproduce :
- set you screen resolution to 1366 x 768 or under
- open qgis with a blank profile
- install qfieldsync plugin
- open "Project properties" dialog
- try to resize it

Tested with QGIS 3.22 and 3.28. Qfieldsync version : 4.2.0

**Comment by amerio1** [comment]
Confermo che, quando il plugin qfieldsync è abilitato in Qgis, non risulta possibile ridimensionare le finestre di dialogo "Proprietà progetto". Tuttavia faccio presente che ho verificato che  disabilitando il plugin, i comandi dello stesso  rimangono attivi, ed è possibile comunque eseguire le operazioni per poter esportare i progetti.
Ieri ho comunque segnalato il problema tramite mail sul sito OPENGIS-ch (forse ho sbagliato la modalità?)
nella mail ho indicato, più o meno,  quanto segue:
“quando il plugin qfieldsync è abilitato in Qgis, non risulta  possibile ridimensionare le finestre di dialogo "Proprietà progetto". 
Che sto usando Qgisd 3.28.3 su windows 10. 
Ho fatto presente che a seguito di un suggerimento ricevuto:
    1. ho creato un nuovo utente Qgis;
    2. che  erano presenti solo dieci plugin  e che  la finestra di dialogo “proprietà di progetto “ funzionava regolarmente;
    3. che scaricando il plugin QfieldSync mi è comparso lo stesso problema che riscontravo con l’utente che stavo utilizzando in precedenza (di conseguenza ha appurato che il plugin non aveva interferenze con altri che avevo sulla postazione solita);
    4. che accedendo con il vecchio utente e disabilitando il plugin  QfieldSync la finestra ha ripreso a funzionare correttamente
A mio parere è pertanto chiaro  che la impossibilità di poter ridimensionare le finestre  di dialogo “proprietà di progetto “ è da attribuire a qualche problema che crea il plugin QfieldSync.

**Comment by suricactus** [comment]
@amerio1 please write in English, or at least use automated translation of your messages. Most of the community members and maintaners do not speak your language ;) .

**Comment by agiudiceandrea** [comment]
@suricactus, summarizing the @amerio1 comment: he confirms the issue occurs after installing the QFieldSync plugin in QGIS 3.28.3 on Windows 10.

**Comment by suricactus** [comment]
Thanks! The fix will come with the next QFieldSync version. In the meantime, you can use the zip in the bottom of this page https://github.com/opengisch/qfieldsync/actions/runs/4152250084 .

**Comment by amerio1** [comment]
grazie

Il giorno sab 11 feb 2023 alle ore 17:44 Ivan Ivanov <
***@***.***> ha scritto:
