### ISSUE TITLE
Visibility of rules in rule-based postgresql-layers is getting lost using mapthemes

### ISSUE THREAD

**Issue by koenigherford** [opengisch/qfieldsync#48]
Exporting a postgresql-layer with rule-based symbology (qgis 2.18.13) has following result in the offline-project **after** changing the maptheme:
The visibility of all the **rules** is activated or deactivated (the check-state of the layer itself works). 
The difference is shown below (all rules are checked/activated) . 
In some cases all rules are deactivated/unchecked. So no features are displayed in the map. I've got no idea why some postgresql-layers have completley unchecked rules and others have completely checked rules an reproduce this behaviour. In my testproject below all rules are checked - in another project with lots of layers and rules all the rules are deactivated.

SHP/Spatialite-datasources seem not to be affected.

Probably it's the same reason for qfield-issue #175

![grafik](https://user-images.githubusercontent.com/28433436/32605160-a993aece-c550-11e7-928e-2ad8542e47a7.png)

**Comment by suricactus** [comment]
This feature is refering to QGIS 2.18. Please open a new issue if it is still a problem.
