### ISSUE TITLE
Couldn't load plugin 'qfieldsync' due to an error when calling its classFactory() method

### ISSUE THREAD

**Issue by nicolewatts** [opengisch/qfieldsync#484]
The latest release of qfieldsync (4.3.1) throws an error when attempting to install or upgrade the plugin
```
Couldn't load plugin 'qfieldsync' due to an error when calling its classFactory() method

ImportError: cannot import name 'TypedDict' from 'typing' (C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\typing.py) 
```
Tested on Windows 10 using QGIS version 3.16.6

**Comment by suricactus** [comment]
This error is due to old Python version. Note QGIS 3.16 is no longer supported (https://qgis.org/en/site/getinvolved/development/roadmap.html). Please upgrade to newer QGIS version.
