### ISSUE TITLE
Update don't wrok

### ISSUE THREAD

**Issue by guenlm** [opengisch/qfieldsync#491]
Hello
I try to synchronize a Postgis layer but updates nether run and add/delete only sometimes... The log 's table in the gpkg show the differents commands done on the mobile but they don't come back in the QGis project. For delete, I have this error :
```
 Requête erronée : DELETE FROM "public"."geoobjet_point" WHERE "pkuid" IN () a retourné 7 [ERROR: syntax error at or near ")"
             LINE 1: DELETE FROM "public"."geoobjet_point" WHERE "pkuid" IN ()
```
Is there a log of synchronization engine somewhere ?
Maybe an explication... : My original Postgis have incremental primary key (pkiud) but I replace it by a default value in QGis like  rand( 100000,9999999999999) to have "unique" value to avoid conflicts on mobile.... Maybe it's not possible for QFieldSync...?
I know its' better to have uuid primary key but it's impossible to change the original Postgis layer now. Maybe I can keep my incremental primary key in Postgis and add an uuid field (unique) only used for QFieldSync... How can I do that ?
I know that QFieldCloud is better but for the moment, my Postgis server is not published... so it is not reachable form the mobile...

thank's for your help
 Guen

**Comment by guenlm** [comment]
OK, I tried and I have an error for the update 👍 
```
Requête erronée : UPDATE "public"."geoobjet_point" SET "nom"='update ordi' WHERE a retourné 7 [ERROR: syntax error at end of input
             LINE 1: ...ATE "public"."geoobjet_point" SET "nom"='update ordi' WHERE 
```
but I don't have all the message..; WHERE what ?

**Comment by suricactus** [comment]
This is when Offline Editing does not recognize the primary key.

If the problem is confirmed without QFieldSync, please check the QGIS documentation and issues for support.

**Comment by guenlm** [comment]
ok thank's.
and do you know if it would possible to add an new uuid field in the table only to perform synchronisation with offline mode ? without changing the incremental primary key of Postgis ?
