### ISSUE TITLE
folder .qfieldsync - only reader 

### ISSUE THREAD

**Issue by robibrazze** [opengisch/qfieldsync#494]
hi,
when i package layers (version of qgis 3.16.15), the plugin create folder .qfieldsync for sincro whit qfieldcloud that don't work well bacause the attibute of the folder is "only reader".
I tried manually to remove "only reader", but after save the modify the attribute retuned "only reader".
I think that the problem is win 11...

any help to solve?
Thanks a lot
Roberto

**Comment by robibrazze** [comment]
@suricactus yes, it is still an issue

**Comment by suricactus** [comment]
@robibrazze can you try with a different path. The problem is that your QGIS does not have permissions to create the file in the selected location. What if you try in a temporary directory in your "My documents"?
