### ISSUE TITLE
Package Project for QField: Selection/Deselection All Directories not working

### ISSUE THREAD

**Issue by dompec** [opengisch/qfieldsync#499]
## Describe the issue

The Buttons "Deselect All" and "Select All" at "Package Project for QField"-dialog don't de/select all listed directories. 

## Reproduction steps

1. Create a QGIS-Project an save it at directory with having other directories at same file-level.
2. Open QFieldSync "Package Project for QField"
3. Press "Deselect All" if diretories are selected or "Select All" if all directories are deselected.

## Expected behavior

"Deselect All" should deselect all directories. "Select All" schould select all directories.

## Observed behavior

When packing the project for QField the Directories at section "Advanced" are all checked/selected by default. If I press "Deselect All" only the first directory ist deselcted. The others stay selected. So I have to deselect every single directory seperately. The other way around: if I have deselected all directories and I press "Select All", only the first directory is checked.

## Screenshots and GIFs

![DESELECT](https://user-images.githubusercontent.com/127151635/223551839-0f22a218-8023-4d1a-869f-08fccff4daa6.gif)

![SELECT](https://user-images.githubusercontent.com/127151635/223551923-839a6298-1216-47b0-b485-7965190a2eb7.gif)

## Desktop (please complete the following information)

- OS: Windows 10
- QGIS Version 3.28.4 [fd0fb72ab3]
- QFieldSync Version 4.4.8

## Additional information

- Problem started happening recently, didn't happen in an older version of QField: Not observed in older versions. I never recognized that option to de/selection directories in older versions
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]
- Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by suricactus** [comment]
This issue should be fixed in #599 and will land with the next QFieldSync release.
