### ISSUE TITLE
QField photo naming issue

### ISSUE THREAD

**Issue by Sergo993108** [opengisch/qfieldsync#503]
Hi all. There is a problem with the naming of photos. It is necessary, that at putting a point in Qfield when the person takes a photo, it inside a project folder DCIM will be named in the following way : DiscriptionID_PointID_AreaName_Date_pic1.jpg
To do this, in the Layer Properties of the QField tab in Attachment naming for each photo, the following expression was spelled out: 'DCIM/' || "DiscriptionID" || '_' || "PointID" || '_' || "AreaName" || '_' || format_date("Date",'ddMMyy') || '_pic1.jpg'
I also tried the following way:  'DCIM/' || "DiscriptionID" + '_'+"PointID"+'_'+"AreaName"+'_'+format_date('Date','ddMMyy') ||'_pic1.jpg'
But unfortunately, in both cases the name for the photo is given in the default format JPEG_20230203040.jpg

Also, there was an option to ideally use a CASE condition. Sometimes, if an observation point is not described in a given location, but is simply marked as passed, only the PointID is filled in. Therefore, it was decided to use CASE and expression in this case looked like this 
CASE WHEN "DiscriptionID" IS NULL THEN 'DCIM/' || "PointID "+'_'+"AreaName "+'_'+format_date("Date",'ddMMyy') ||'_pic1. jpg' ELSE 'DCIM/' || "DiscriptionID" || '_' || "PointID" || '_' || "AreaName" || '_' || format_date("Date",'ddMMyy') || '_pic1.jpg' END
But the function still didn't work and ended up naming the photo by default as well. 

Can anyone help with this problem?

**Comment by suricactus** [comment]
There was a known issue on QFieldSync which prevented configuration to be users to setup their image path. Can you try with any of these combinations and share results?

- latest QField 2.7 and latest QFieldSync 4.4.8
- latest QField 2.6 and latest QFieldSync 4.4.8

**Comment by Sergo993108** [comment]
@suricactus By the next expression, a bit similar with one that i write above 'DCIM/' || "PointID" || '_' || "AreaName" || '_' || format_date("Date",'ddMMyy') || '_pic2.jpg' it shows in Preview field that it will work well (see in the attachment screenshot), but after taking photo in Qioeld it does not works with the photo as i can see in DCIM folder. But with the Case expression, in both cases it shows in Preview field in Expression Dialog NULL, so i think it means that CASE here is incorrect or does not wotk with photo naming.

![image](https://user-images.githubusercontent.com/28626492/224900006-44f77b3a-f9ed-4b98-8180-63429e14fbf0.png)

**Comment by m-kuhn** [comment]
@Sergo993108 can you try to update qfield and qfieldsync to the latest version?

**Comment by Sergo993108** [comment]
@suricactus @m-kuhn I have updated version of QField on my phone to 2.6.3-Geeky Gecko (aaa93d v2.6.3)
Version of QFieldSync is 4.4.8. Version of QGIS is 3.28.4
For now CASE expression (it is ideally what i want to use this expression) work partly.  
Im using CASE expression in next way:
CASE WHEN "DiscriptionID"=NULL THEN 'DCIM/' || "PointID" + '_'+"AreaName"+'_'+format_date("Date",'ddMMyy') ||'_pic1.jpg' ELSE 'DCIM/' ||  "DiscriptionID"  + '_'+"PointID" + '_'+"AreaName"+'_'+format_date("Date",'ddMMyy') ||'_pic1.jpg' END
From this expression as i can see from the photo name that starts to store in DCIM folder, only ELSE part works fine (Photo name starts to be AA8_SK2_Hillside_140323_pic1.jpg) It means that it works when i fill DiscriptionID. But when i left it empty (add nothing, so it stores with default NULL value) it does not work and assigns name for photo in default format JPEG_20232202020.jpg

**Comment by Sergo993108** [comment]
Also after updating QField on my phone i have next issue from #504

**Comment by m-kuhn** [comment]
@Sergo993108 there are two different issues here:

 - The rule with `'DCIM/' || "PointID" || '' || "AreaName" || '' || format_date("Date",'ddMMyy') || '_pic2.jpg'` that works on QGIS but not in QField photo naming. **This was an issue in QField/QFieldSync that has been fixed**. Can you confirm with the latest update everything works as expected on QField?
 - The broken `CASE` statement which is also broken on QGIS. This is an issue with the expression which is not a QField bug, so this should be treated separately via a QGIS support channel. Note: I can spot at least one issue in there `"DiscriptionID="NULL"` should be `DiscriptionID IS NULL`

**Comment by Sergo993108** [comment]
@m-kuhn Thanks Matthias, now CASE expression works fine and it names photos as i wanted. 
Only one issue left is with saving this points. I mentioned this issue in #504.
I will close this issue with photo naming since we have found a solution.
