### ISSUE TITLE
Point layer saving issue

### ISSUE THREAD

**Issue by Sergo993108** [opengisch/qfieldsync#504]
After updating QField upto version 2.6.3 problem with saving project file starts to happen. 
![a308961f-57e6-4af3-89a4-b0cf5ef7a574](https://user-images.githubusercontent.com/28626492/224919878-19ba10dc-36c4-4ed9-95dc-ee11c57b2352.jpg)
I changed just "Measure (M) value attached to vertices" setting because had the same issue once on Iphone device, but for now on Android it did not helped.
![f6c1f208-11b4-4886-b60d-eeca0bc65e1d](https://user-images.githubusercontent.com/28626492/224920203-578e3769-d396-44c8-a1e2-7f2ba595b39b.jpg)

**Comment by nirvn** [comment]
@Sergo993108 , could you provide steps to replicate the issue and a sample project?

**Comment by Sergo993108** [comment]
@nirvn Unfortunately, I can't share the project package because it is for the company, think it is quite confidential. 
But i think there is nothing in the project itself, because the same project saved a layer with dots in an old version of Qfield ( I can not remember exactly what version was, because I mercilessly updated it to 2.6.3)

**Comment by nirvn** [comment]
@Sergo993108 , try to open the bees project sample that's shipped with QField and add random apiary points to the project. I suspect you will find the digitizing of points there to work. And it'll demonstrate why we need a specific sample project to replicate your issue :)

So, step one is to confirm that on other projects, you can digitize points just fine.

Step two, come up with a reduced test project that you can share (i.e. no confidential information) with us so we can have a look at the issue reported here. You can also share a sample project via email if you do not feel comfortable sharing it here.

**Comment by Sergo993108** [comment]
@nirvn I'll definitely try your suggestion now, but here's what I discovered just a second ago. After I turned on the setting to have the cursor follow my location, I was able to save a layer with a new point. That is, I can't put the point in an arbitrary place, but I can only put and save it where I am, in that location

**Comment by nirvn** [comment]
@Sergo993108 , can you attach a screencast of a point addition failure with the bees project?

**Comment by nirvn** [comment]
@Sergo993108 , in 10 minutes or so, this PR (https://github.com/opengisch/QField/pull/4036) will have APKs for you to test. I'm hopeful this will fix the issue you are facing.

**Comment by Sergo993108** [comment]
@nirvn @m-kuhn Thank you very much for your help. The beta version you shared fixed the bug I was talking about. There were still some minor issues with my project, of course. Perhaps I will run new threads with them. But the two that you helped solve now were the most problematic ones. 
Thanks again.

**Comment by nirvn** [comment]
@Sergo993108 , fantastic, glad we could help.
