### ISSUE TITLE
[Feature Request]: Showing up toolbar tooltip when hovering over toolbar handle

### ISSUE THREAD

**Issue by TNogatz** [opengisch/qfieldsync#509]
### Feature request
Would be great to show the title of the toolbar when hovering over the toolbar handle. This is how most other toolbars behave, for instance the help toolbar:
![Help_toolbar](https://user-images.githubusercontent.com/26670955/226831623-cea8b2b2-4d9c-4365-8da0-e8f05ae74787.png)

### Observed behavior
Hovering over the QFieldSync toolbar handle nothing is shown:
![IMG_20230322_083434](https://user-images.githubusercontent.com/26670955/226834003-5ae972ca-71a9-476d-85ca-7b713857ab8b.jpg)

### QFieldSync version
4.4.9

**Comment by SeqLaz** [comment]
This is already implemented. I will go ahead and close this!
![image](https://github.com/user-attachments/assets/f519dc53-26e4-49a5-8892-97b562a033d3)
