### ISSUE TITLE
qfieldsync asks to sync layers that have not been modified

### ISSUE THREAD

**Issue by kiri03** [opengisch/qfieldsync#515]
I have a project set up with some read-only vector layers placed to show in the background, as a reference for the field editors.
Those layers, although they are set as read-only, are not edited or modified by any user, but despite this, whenever I synchronize from QGIS, it asks me to reload those layers from the cloud, as if they had been modified by some editor.
Is there a way to configure those vector layers so that they stay locked and don't try to download every time I sync the project from the cloud to QGIS?

Thanks.

**Comment by suricactus** [comment]
What QGIS/GDAL version are you using? This should have been prevented in recent versions, as the gpkg files are no longer modified on read, but only if they are turned into editing mode.

Unfortunately, there are not too many things to be done to easily improve the situation.

**Comment by suricactus** [comment]
This should be fixed in the latest version.
