### ISSUE TITLE
Duplicate values ​​in qfieldsync screen on newest ubuntu and QGis releases

### ISSUE THREAD

**Issue by BoswachterMarc** [opengisch/qfieldsync#517]
1/ I noticed some strange behavior on the latest Ubuntu release 23.04 in combination with QGis 3.30.2-'s-Hertogenbosch and QFieldSync v.4.4.9. I can sync all files twice... :-)

2/ This does not happen with the same project on a Ubuntu 20.04.6 LTS release with QGis 3.26 Buenos Aires installed and the same QFieldSync v.4.4.9

I don't see anything irregular on the QFieldCloud dashboard (files, jobs, ... everything looks fine).
And it looks like syncing on 1/ works normal; I just wanted to bring this to your attention.

![afbeelding](https://user-images.githubusercontent.com/57868975/235799950-9c19f90d-9abd-4ba7-a3d6-f7812bcbe4b8.png)
![afbeelding](https://user-images.githubusercontent.com/57868975/235800038-5ab0a20f-2f88-4108-a497-5d38a11218f1.png)

**Comment by m-kuhn** [comment]
@vlebert I think you had the same issue with a newer QGIS version and more recently?

**Comment by vlebert** [comment]
Hi @m-kuhn 
Yes, same issue on MacOS / QGIS 3.28

Closing QGIS and reopening a fresh instance fix it if you do QField Sync as first action. If you do something else, the bug may happen again
