### ISSUE TITLE
Strange syncing behaviours. Not syncing correctly. jumping between versions.

### ISSUE THREAD

**Issue by herrsei123** [opengisch/qfieldsync#520]
I'm on QGIS 3.22.12 with QfieldSync 4.4.9 on Ubuntu.
And with QField up to date on Android 11 on Samsung A71.

To follow my thouths, i write the plattform capitallized. 

Following behaviour: i mapped some cars to my Layer cars.gpkg on ANDROID. When i sync changes of the geopackage layer from ANDROI to CLOUD, afterwards i cant sync the changes from CLOUD to my DESKTOP. it says it fetches the new files, but then everything is like before i started mapping on android. 
AND: if i hit the "sync" button on ANDROID, it restores the old cloud state of the project before the changes. 
BUT: when i instead go to WEBVIEW of my files e.g. https://app.qfield.cloud/a/USERNAME/PROJECT/files and there i download the synced file manually to my DESKTOP i get the newest state with mapped cars. But when i sync with the "official" way in QFieldSync or even on ANDROID with "Syncronize Project" i'm always back on my old porject BEFORE mapping the Cars.

i can also play this further to some length of madness: now after having manually synced newest cars layer to my desktop: i'm adding to points there. I then sync it to CLOUD. then i hit syncing button on ANDROID: And voila, it restores a state AFTER the first mapping on android BUT before mapping the second points on my DEKSTOP.

So somtheing does not work correctly with the sync :-(

Otherwise: great tool for mapping!

**Comment by SeqLaz** [comment]
Hi,
Thank you for reaching out.
Please contact support via the chat bot on the qfield.cloud application, the question mark at the bottom right.
Please specify the project and user in question.
Thank you.

**Comment by ffrosch** [comment]
@herrsei123 did the support find the issue?

We are facing the same problem right now. It would be interesting what caused it for you!

**Comment by ffrosch** [comment]
@herrsei123 thank you very much for the reply. I opened a support ticket for this. I'll post the results here if they find anything.
