### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted 

### ISSUE THREAD

**Issue by BoswachterMarc** [opengisch/qfieldsync#523]
I am getting this error since I made following changes in a QFieldCloud project (and testing offline, making a package manually with QFieldSync). I was 

- adding a one to many relation
- making a non spatial layer for the data on the many side
- changing the settings of a certain text field in QGis to work with the one to many relation (adding the relation/widget type 'relation editor')

I see there was a similar problem before: https://github.com/opengisch/qfieldsync/issues/502

![image](https://github.com/opengisch/qfieldsync/assets/57868975/889c4f6a-feb6-4c3d-bf23-09d3404b93bb)
![image](https://github.com/opengisch/qfieldsync/assets/57868975/599cf48a-a624-4cb0-8a65-fff3e80c2266)

I am  working on Ubuntu 22.04.2 LTS, QGis 3.30.3 's Hertogenbosch c006973ad1 and QFieldSync 4.4.9 

Is this error a problem on my side or is it a bug?
Will this error pollute the QfieldCloud project when I synchronize it?
Can I get rid of this error popping up?

I don't have a small sample project to share. I don't know if I can reproduce the problem.

---
**Update:** I copied the project to another Ubuntu 23.04 pc (Gnome version 44 - Wayland) with the same QGis version and when making a small change in a attribute form of a polygon layer (setting a field from editable to not editable), the error pops up again...

![afbeelding](https://github.com/opengisch/qfieldsync/assets/57868975/54fccf41-47a2-4976-b5bc-247b9c789107)

**Comment by m-kuhn** [comment]
Hi @BoswachterMarc we are about to release a new fixed version.
Could you install https://github.com/opengisch/qfieldsync/releases/download/v4.5.0/qfieldsync.v4.5.0.zip via plugin manager and see if it fixed the issue?
Thank you!

**Comment by BoswachterMarc** [comment]
@m-kuhn I installed the v4.5.0 and my first impression is that it no longer occurs on the Ubuntu 23.04
I can only test it more extensively in a few days...

**Comment by m-kuhn** [comment]
This should be fixed with 4.5.0, please reopen if this persists after an upgrade. Thank you
