### ISSUE TITLE
Layer setting Remove from project is ignored

### ISSUE THREAD

**Issue by itsakifa** [opengisch/qfieldsync#525]
Although the layer is set to "remove from project", a gpkg is created for offline editing and added to the QField package.

![image](https://github.com/opengisch/qfieldsync/assets/4679915/6ecdb09f-fed9-45c8-a8ba-4551a1491b21)

**Comment by suricactus** [comment]
Can you provide a test project?

**Comment by suricactus** [comment]
Closing due to lack of feedback.
