### ISSUE TITLE
QGIS Project  is bloated by qfieldSync

### ISSUE THREAD

**Issue by Amphibitus** [opengisch/qfieldsync#527]
The project file is bloated by qfieldSync because all subdirectories of the project directory are included in the .qgs file. Isn't it more advisable to only store the folders to be synchronized. For me, this means that Qfield takes forever to load a project.

![grafik](https://github.com/opengisch/qfieldsync/assets/7237786/4cc19825-ef7d-4b7a-99d2-e1a82334be1e)

**Comment by suricactus** [comment]
Uploading a `.zip` with a sample project with the problematic structure with a lot of dirs might help to better understand the performance issues you are experiencing. Thanks!
