### ISSUE TITLE
Photo Naming Issue in QField

### ISSUE THREAD

**Issue by parydeogracias** [opengisch/qfieldsync#539]
Hello all,

I am using QField for taking photos for surveys and have encountered an issue with the custom naming settings for photos. The custom naming I have set is not being recognized, and photos are being saved with a generic name.
I used the following naming configuration for my photos:
"'DCIM/doe-otb/'||left( "name", strpos("name",'/')-1)||'_'||right( "name", strpos("name",'/')-1)||'_'||'vue_ensemble_OTB_ferme_' || format_date(now(),'ddMMyyyyhhmmss') || '.jpg'". Instead of having names based on the above configuration, the photos are being saved with names like JPEG_20230825092823396.JPG.

QField Version: v2.8.5 
QField sync Version: v4.6.0
Operating System: Android 11
Hardware: Samsung Galaxy Tab 10"

**Comment by m-kuhn** [comment]
Does it work with a simpler expression?

**Comment by parydeogracias** [comment]
Now it's working with version 2.8.7 of qfield. Thank you!
