### ISSUE TITLE
QField Audio Recorder icon not appearing

### ISSUE THREAD

**Issue by negir08** [opengisch/qfieldsync#540]
Unable to get the audio recorder icon in the qfield project created to capture audios recording. I am using QGIS v3.32.2, created a shapefile 'point1' with one of the attribute as Widget Type 'Attachment'. Also gave attachment naming as 'audio/point1_' || format_date(now(),'yyyyMMddhhmmsszzz') || '.mp3'. I do followed the documentation but couldn't get the desired button as in [https://docs.qfield.org/how-to/pictures/#configurable-attachment-path](url) . Please help.

**Comment by VxTedxV** [comment]
In QGis, widget type 'attachment' is good and then, Integrated document viewer must be defined as 'audio'.

**Comment by negir08** [comment]
Thanks, was able to do it. Had to reinstall QGIS and QFieldSync plugin.
