### ISSUE TITLE
Recompile plugin

### ISSUE THREAD

**Issue by nesar77** [opengisch/qfieldsync#541]
Hi everybody,

I've installed the qfieldcloud on my own server; I would like to compile the qfieldsync plugin to connect to my server. 
I've changed the server_urls variable in cloud_api.py file and now I'd like to rebuild the plugin.
How can I do it?

**Comment by m-kuhn** [comment]
You can double click the nyuki icon on the login screen to change the server url.

The plugin itself is not compiled, it's a regular QGIS plugin.

**Comment by nesar77** [comment]
Hi @m-kuhn,
thank you very much; your suggetion works fine!

**Comment by suricactus** [comment]
Please check the documentation here: https://docs.qfield.org/get-started/tutorials/get-started-qfc/?h=connect#change-the-default-qfieldcloud-server-in-qfield-and-qfield-sync
