### ISSUE TITLE
QField Sync Issues

### ISSUE THREAD

**Issue by Oisin-JK** [opengisch/qfieldsync#547]
I have a project configured for offline editing, which I exported to a QField project using QFieldSync. 
All layers to be synchronised are geopackage layers. There are multiple layers in each geopackage.

On synchronising the project I get several errors.

### **1. QFieldSync Log:** 
> "The project you imported does not seem to be an offline project"

It is an offline project. It was created from the project I am trying to sync to. All relevant layers are showing cable export action = "offline editing"

### **2.  General Log**

> 2023-11-24T17:56:43     INFO    Application state:
>              QGIS_PREFIX_PATH env var: C:/PROGRA~1/QGIS32~2.11/apps/qgis-ltr
>              Prefix: C:/PROGRA~1/QGIS32~2.11/apps/qgis-ltr
>              Plugin Path: C:/PROGRA~1/QGIS32~2.11/apps/qgis-ltr/plugins
>              Package Data Path: C:/PROGRA~1/QGIS32~2.11/apps/qgis-ltr/.
>              Active Theme Name: default
>              Active Theme Path: C:/PROGRA~1/QGIS32~2.11/apps/qgis-ltr/./resources/themes\default\icons/
>              Default Theme Path: :/images/themes/default/
>              SVG Search Paths: C:/PROGRA~1/QGIS3~1.10/apps/qgis/./svg/
>               C:/Users/arbor/AppData/Roaming/QGIS/QGIS3\profiles\default/svg/
>               C:/PROGRA~1/QGIS3~1.12/apps/qgis/./svg/
>               C:/PROGRA~1/QGIS3~1.14/apps/qgis/./svg/
>               C:/PROGRA~1/QGIS3~1.18/apps/qgis/./svg/
>               C:/PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./svg/
>               C:/PROGRA~1/QGIS32~1.11/apps/qgis-ltr/./svg/
>               C:/PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./svg/
>               C:/PROGRA~1/QGIS32~2.11/apps/qgis-ltr/./svg/
>              User DB Path: C:/PROGRA~1/QGIS32~2.11/apps/qgis-ltr/./resources/qgis.db
>              Auth DB Path: C:/Users/arbor/AppData/Roaming/QGIS/QGIS3\profiles\default/qgis-auth.db
>              
> 2023-11-24T17:58:19     WARNING    Error zip file does not exist: 'C:/Users/arbor/Documents/Jobs/00938 - Notcutts Safety Surveys/Survey/938_Notcutts Oxford/Oxford.qgz'

The file 'C:/Users/arbor/Documents/Jobs/00938 - Notcutts Safety Surveys/Survey/938_Notcutts Oxford/Oxford.qgz' does exist. It is the currently open project.

But I note that some of the PATHS appear out of date. e.g. C:/PROGRA~1/QGIS32~2.11/apps/qgis-ltr appears to relate to an old installation of QGIS 3.22.11, not 3.28.11. QGIS 3.22.11 is no longer installed, although some legacy folders exist. 

Is this an issue I need to fix? Where do I edit all the environment variables and paths?

### **3. After Synchronisation**
Rather than updating the layers, it changes their source to the QFIeld project.

**Am I doing something wrong? Is this a bug?**

I have successfully synchronised other similar projects.

QGIS version info is as follows:

QGIS version 3.28.11-Firenze QGIS code revision b02458a196
Qt version 5.15.3
Python version 3.9.5
GDAL/OGR version 3.7.2
PROJ version 9.3.0
EPSG Registry database version v10.094 (2023-08-08)
GEOS version 3.12.0-CAPI-1.18.0
SQLite version 3.41.1
PDAL version 2.5.5
PostgreSQL client version unknown
SpatiaLite version 5.1.0
QWT version 6.1.6
QScintilla2 version 2.13.4 
OS version Windows 10 Version 2009

Active Python plugins coordinate_capture 0.2
felt 1.1.0
GeoCoding 2.19
magic_map_loader 1.1
oam_qgis3_express 0.1.0
qfieldsync v4.6.1
qgis2web 3.16.0
QuickOSM 2.2.3
db_manager 0.1.20
processing 2.12.99

**Comment by Oisin-JK** [comment]
The Synchronisation process seems so flaky. Another project, same set-up as the one referred to above. It synchronises with no error, but I have directly compared data between the two and it has not updated. I now can't trust that any record has been correctly updated. Argh!

**Comment by suricactus** [comment]
Hey! It would be interesting to share your master and offlined project, so we can try to reproduce.

**Comment by Oisin-JK** [comment]
is there a way to share outside of a public forum?
