### ISSUE TITLE
Problem at the end of qfieldsync execution on geometrytype

### ISSUE THREAD

**Issue by beb190** [opengisch/qfieldsync#552]
Hello,
Following the last update I have an error message on the geometry. It works fine with the old program...

The message in QGIS :

An error occurred while executing the Python code 

AttributeError: type object 'Qgis' has no attribute 'GeometryType' 
Traceback (most recent call last):
  File "C:\Users/gcf.cof/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\package_dialog.py", line 180, in package_project
    raise err
  File "C:\Users/gcf.cof/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\package_dialog.py", line 176, in package_project
    offline_convertor.convert()
  File "C:\Users\gcf.cof\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfieldsync\libqfieldsync.whl\libqfieldsync\offline_converter.py", line 143, in convert
    self._convert(project)
  File "C:\Users\gcf.cof\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfieldsync\libqfieldsync.whl\libqfieldsync\offline_converter.py", line 258, in _convert
    layer.geometryType() is not Qgis.GeometryType.Null
AttributeError: type object 'Qgis' has no attribute 'GeometryType'

Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.28.4-Firenze Firenze, fd0fb72ab3 

Chemin Python :
C:/PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python
C:/Users/gcf.cof/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/gcf.cof/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.22.13\apps\Python39
C:\PROGRA~1\QGIS32~1.4\bin\python39.zip
C:\PROGRA~1\QGIS32~1.4\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib
C:\PROGRA~1\QGIS32~1.4\bin
C:\PROGRA~1\QGIS32~1.4\apps\Python39
C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages\Pythonwin
C:/Users/gcf.cof/AppData/Roaming/QGIS/QGIS3\profiles\default/python
D:\eclipse\plugins\org.python.pydev.core_7.0.3.201811082356\pysrc
C:\Users\gcf.cof\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\gcf.cof\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:\Users\gcf.cof\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfieldsync\libqfieldsync.whl
C:/Users/gcf.cof/AppData/Local/Temp/2/tmp6g8m7f3w

**Comment by m-kuhn** [comment]
Hi, thank you for reporting.
Can you try to reproduce this behavior with a currently supported QGIS version (3.28 or newer?)
Thanks!

**Comment by beb190** [comment]
Hi,
Yes it's the same issue with currently QGIS stable version (3.28) but when i try in the last development version (3.34.2) no problem... I'm waiting update... Thanks !

**Comment by suricactus** [comment]
Hey! Thanks for reporting. This was a regression, will be fixed in the next QFieldSync release.
