### ISSUE TITLE
When configuring basemap the map unit cannot be less than 1.

### ISSUE THREAD

**Issue by Trashmonk** [opengisch/qfieldsync#56]
Hi, I have noticed that when I try and configure the basemap map units I cannot make them less than 1. My map projections is EPSG:4326 which means the map units are in degrees, 1 degrees is very low resolution. Would it be possible to set map units to 0.01 or smaller?

Thanks!

**Comment by m-kuhn** [comment]
We have ported the algorithm to QGIS 3 And included this there. Could you could try to prepare this basemap on qgis 2.99 (without qfieldsync)?

**Comment by Trashmonk** [comment]
So, I have installed qgis 2.99 (QGIS-OSGeo4W-2.99.0-50-Setup-x86_64.exe | 11-Dec-2017 15:22 | 469M). However, when I go to processing toolbox and type in basemap, I get nothing. Is it located elsewhere?

**Comment by Trashmonk** [comment]
Disregard the last message, I have deleted it. The short answer is it works, thanks! Although the tool appears to have been renamed from "basemap" to "convert map to raster" for anyone interested.
