### ISSUE TITLE
QField Sync - package for QField not working

### ISSUE THREAD

**Issue by Jokubasss** [opengisch/qfieldsync#561]
Does not create package file for QField, fails to create basemap and QGIS freezes after it. By the way if using QFieldCloud to convert project, everything works just fine. Just this is a issue with package for QField function.

**Comment by suricactus** [comment]
Hello! We did no manage to reproduce your issue. Can yoy please provide a bit more info:
QGIS version
QFieldSync version
Python version
Sample project attached as .zip

**Comment by SeqLaz** [comment]
Hello @Jokubasss , to address a workflow issue, you have two options if you want to work offline: you can either have a separate GeoPackage for each layer, or you can use the Copy action.
