### ISSUE TITLE
error when upgrading the plugin

### ISSUE THREAD

**Issue by 3nids** [opengisch/qfieldsync#565]
No module named 'libqfieldsync.offliners'

![image](https://github.com/opengisch/qfieldsync/assets/127259/dbf9d321-feb5-4e82-b772-78509f178541)

**Comment by m-kuhn** [comment]
version?

**Comment by 3nids** [comment]
when updating to 4.7.1

**Comment by m-kuhn** [comment]
upgrade worked well here :thinking:

**Comment by suricactus** [comment]
@3nids are you using the installed version from the QGIS repo, or you use the development version from this repo?

**Comment by 3nids** [comment]
installed from QGIS
I got no error when restarting QGIS, not sure what happened.
Feel free to close it if that doesn't ring any bell on your end.

**Comment by m-kuhn** [comment]
Interesting is that line 26 on the screenshot imported fine.
I suspect you had an older version installed which used libqfieldsync as subdirectory, while upgrading the new qfieldsync version with the wheel got installed, the python interpreter of the running instance still had the old subdirectory based structure cached and preferred that one over the updated wheel version.
If it works well after a restart, I'd say we don't invest here.

**Comment by suricactus** [comment]
Just came here to post the reason why you see the error, but @m-kuhn already did it. I do agree it does not need any further investigation, it's single time error.
