### ISSUE TITLE
Qfield Sync Not Working on Certain Projects

### ISSUE THREAD

**Issue by seades0630** [opengisch/qfieldsync#568]
I've been encountering the following Python Error in Qgis when I try to use the "Package for Qfield" function of the Qfield Sync Plugin.

![image](https://github.com/opengisch/qfieldsync/assets/123121519/2ded30b4-89ba-4185-8f70-aa3ad744ec47)

This only occurs with one particular project, however. I have several other QField projects set up in a very similar manner that do not produce the same error and export/package without issue.  It's possible that the issue is with one of my files, but I have other projects created with data form the exact same sources that doesn't cause the same issue.  Anyways, I thought I would put it up here and see if anyone might recognize the issue/potentially point me towards a solution.

QGIS ver 3.34.4 LTR
QField Sync ver 4.7.1
Python Ver 3.9.18

**Comment by suricactus** [comment]
Can you try with the latest 4.9.1?
