### ISSUE TITLE
Basemap algorithm improvements

### ISSUE THREAD

**Issue by Trashmonk** [opengisch/qfieldsync#57]
I am not sure if this is the right location for this, if not, I am happy to post this elsewhere. I have been using the "convert map to raster" in QGIS 2.99 and it's great. I have noticed two features that are missing that would increase usability a lot I believe. I have had to write a gdal python script to deal with these issues.

1. No alpha band is added to the exported raster, therefore the raster is not transparent in the absence of vector data, which I believe would be what most people would want.
2. You can currently only set the the x-axis tile size, for a lot of global datasets it would be ideal to also be able to set the y-axis tile size.

Again thanks for the great tool, and if I should post this elsewhere, please send me the appropriate location.

**Comment by m-kuhn** [comment]
These are nice enhancement proposals.

If you have scripting experience, feel free to modify the script https://github.com/qgis/QGIS/blob/master/python/plugins/processing/algs/qgis/Rasterize.py and make a pull request.

> You can currently only set the the x-axis tile size, for a lot of global datasets it would be ideal to also be able to set the y-axis tile size.

It's not specific for X, it's for both. But if there are good reasons to have different sizes in X and Y direction, why not.

**Comment by Trashmonk** [comment]
So, I have gotten transparency to work for the background (all areas that don't have points, lines or polygons. I did however modify the Rasterize.py script that comes included with QGIS 2.99. I think I will send the changes to there. Would you like the code so you can add it to the plugin?

**Comment by m-kuhn** [comment]
Nice, can you make a pull request on QGIS upstream? We moved the algorithm there and don't plan to maintain the old copy here in the long run.

**Comment by Trashmonk** [comment]
Ok, Will do that.
