### ISSUE TITLE
Python error after installing new release of Qfield Sync plugin (v4.8.0.)

### ISSUE THREAD

**Issue by bakkerss** [opengisch/qfieldsync#570]
I just installed the new version of Qfield Sync v4.8.0.

I get the following error when I try to package my project.

2024-03-08T10:08:33     WARNING    Traceback (most recent call last):
              File "C:\Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\package_dialog.py", line 161, in package_project
              offline_convertor = OfflineConverter(
              File "C:\Users\SebastiaanBakker\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfieldsync\libqfieldsync.whl\libqfieldsync\offline_converter.py", line 114, in __init__
             AssertionError

I am still using 3.28.4-Firenze (can't upgrade to the new LTR release as the new release continues to crash for our projects)

Below you can find additional information which is shown in the error log

Python versie: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS versie: 3.28.4-Firenze Firenze, fd0fb72ab3 

Python pad:
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\apps\grass\grass82\etc\python
C:\Users\SebastiaanBakker\OneDrive - Natuurlink\Documenten
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\SebastiaanBakker\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfieldsync\libqfieldsync.whl
C:\Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\SebastiaanBakker\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\SebastiaanBakker\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
C:\Users\SebastiaanBakker\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfieldsync\libqfieldsync.whl
C:/Users/SebastiaanBakker/Natuurlink B.V/Natuurlink - Documenten/QGIS/Woonstichting Lieven de Key

**Comment by suricactus** [comment]
Hey! Can you please try the newest patch release? There was a regression that slipped in, sorry for the inconvenience. https://github.com/opengisch/qfieldsync/releases/tag/v4.8.1

**Comment by bakkerss** [comment]
I did not di a full test but the errors are gone so you can close this issue. Thank you for the quick update.
