### ISSUE TITLE
QGIS 3.28.4 crashes when exporting from PostGIS to QField on Win10

### ISSUE THREAD

**Issue by mlanini** [opengisch/qfieldsync#579]
I've got the following error message when trying to export to QField from PostGIS:

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00002dd8 (most recent call first):
  File "C:\Users/t107508.AC/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\package_dialog.py", line 177 in package_project
    offline_convertor.convert()
```

**QGIS Info**
QGIS Version: 3.28.4-Firenze
QGIS code revision: fd0fb72ab3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

**Comment by m-kuhn** [comment]
3.28 is end of life, can you reproduce this with 3.34?

**Comment by mlanini** [comment]
Indeed... smoothly working with >3.34
