### ISSUE TITLE
Password Manager After the plugin is installed

### ISSUE THREAD

**Issue by valorgeografico** [opengisch/qfieldsync#580]
After the plugin is installed, you are prompted to “Enter the current authentication master password.” I don't know her, and I don't know her goal.

Luego de la instalación del complemento, se solicita "Ingrese la contraseña maestra de autenticación actual". No la conozco, y no sé su objetivo.

**Comment by suricactus** [comment]
This is needed so QFieldSync can store you QFieldCloud in a secured way. Read more about his promt here. Closing. https://docs.qgis.org/3.16/en/docs/user_manual/auth_system/auth_overview.html?highlight=master%20password#master-password
