### ISSUE TITLE
Overnight issue with sync between Qfield cloud and Qfield app

### ISSUE THREAD

**Issue by btoshropshire** [opengisch/qfieldsync#585]
I have a Qfield project that has been successfully used in the field to collect point data since the middle of May. There have been no issues so far. We also used it last year with great success.

All of a sudden as of last night (3rd June 2024) when synchronsing via the app - layers suddenly became empty of points features. The layers are there but now empty where as previously they would have contained many points. They are still on the Desktop project and there are no errors when syncing between desktop and cloud.

On the Qfield app the message log keeps saying the following:

Cannot use project transform between EPSG:27700 and EPSG:3857<br><li>This transformation requires the grid file “uk_os_OSTN15_NTv2_OSGBtoETRS.tif”, which is not available for use on the system.</li><br>This grid is available for download from <a href="https://cdn.proj.org/uk_os_OSTN15_NTv2_OSGBtoETRS.tif">https://cdn.proj.org/uk_os_OSTN15_NTv2_OSGBtoETRS.tif</a>.

We have reached a crucial point in our project where people need to be able to see the locations of things in field (we are biologists ringing birds at nests so there is a huge time constraint at play here!). Please can anyone help me resolve this.

Jonathan

**Comment by SeqLaz** [comment]
Hi @btoshropshire 
Could you try to fix the schema of the layer by using the core plugin called "Refactor field"? 

I have attached a document with a common workflow to use the plugin. Make sure that you save the newly generated GeoPackage in the QFieldCloud local project on your computer. After successfully completing the processing, copy all the styles from the original layer to the new one and paste all the styles onto it. Optionally, and as a recommendation, you could delete the layers from the layers list and from the project folder, then synchronize the changes to the cloud. Now the layers should be shown correctly in QField.
[Workflow fixing displaying features 001.pdf](https://github.com/user-attachments/files/15855758/Workflow.fixing.displaying.features.001.pdf)
