### ISSUE TITLE
Error message for version 1.1.1

### ISSUE THREAD

**Issue by saemiw** [opengisch/qfieldsync#59]
I am testing version 1.1.1 under qgis 2.18.16. So far I have not noticed any bad effects but it is of course worrying to get this errors. Can you check if anything is wrong/should be corrected:

Error messages from the log message panel:

General tab:
![grafik](https://user-images.githubusercontent.com/20398621/36429562-4ebca894-1653-11e8-8354-cd850fc29510.png)

Python warning: 
![grafik](https://user-images.githubusercontent.com/20398621/36429653-8be6998c-1653-11e8-8276-b7e726ffcb66.png)

Python error:
![grafik](https://user-images.githubusercontent.com/20398621/36429688-a8df6af0-1653-11e8-87d8-ab3c1090bf54.png)

**Comment by m-kuhn** [comment]
Thanks for the report.

Only the 3rd one is related to qfieldsync, replace `QgsApplication.instance().messageLog().` with `QgsMessageLog.instance().` (that was only introduced in QGIS 3) and possibly adjust the import.

@signedav @3nids not sure who's on this ;)
