### ISSUE TITLE
error with GeoPackage polygon layer for offline editing

### ISSUE THREAD

**Issue by noerw** [opengisch/qfieldsync#60]
When trying to select an GeoPackage Polygon layer for `offline editing`, I get the following error in the message bar on export:
```
Layer gpkg-layer (offline): Geometry type MultiPolygon not compatible with provider type Polygon.
```

The resulting QGIS project then contains an `gpkg-layer (offline)` without any features, as well as the originial, untouched geopackage layer!

The same layer saved as shapefile works fine.

- QGIS v2.18.16
- QField Sync v1.0.0, v1.1.2

**Comment by m-kuhn** [comment]
The whole offline editing functionality has mostly been tested with postgis.
For file-based formats like GeoPackage it works often very well to not do any offline copy but just copy the file to the device and in the end back.

**Comment by noerw** [comment]
Thanks for the reply. In this case, the merge-changes logic would not be applied when re-importing the layer, correct? This would be necessary for us, as we are editing with multiple users at once in the field.

Btw: geopackage (and also sqlite, shp) layers have no 'copy' option displayed most of the time. Will open an issue when I find out how to reproduce

**Comment by m-kuhn** [comment]
> Thanks for the reply. In this case, the merge-changes logic would not be applied when re-importing the layer, correct?

Yes

> This would be necessary for us, as we are editing with multiple users at once in the field.

I agree it would be great if you could allocate some resources to get this fixed.

**Comment by noerw** [comment]
This is unrelated to QFieldSync but seems to be a bug in QGIS / OGR with handling GeoPackage layers. Not sure how to debug this further though.

This only occurs with some GeoPackage layers. Trying to save it results in a similar error:
```
Objekterzeugungsfehler (OGR-Fehler: sqlite3_step() failed:
  layer.GEOMETRY violates Geometry constraint [geom-type or SRID not allowed] (19))
```

After piping the layer through `ogr2ogr -nlt MULTIPOLYGON -f GPKG out.gpkg in.gpkg` everything works. Might be the same as https://issues.qgis.org/issues/10584

**Comment by m-kuhn** [comment]
We would very much like to port the whole offline editing code to geopackage instead of spatialite. Would there be interest in the QField user community to financially support this work?
