### ISSUE TITLE
Conversion error with newest QFieldSync update

### ISSUE THREAD

**Issue by georgiaslim** [opengisch/qfieldsync#604]
I'm running the latest update of QFieldSync plugin (version 4.10.1) in QGIS 3.34.7

After packaging my project and all the layers for QField I sync it with QFieldCloud using QFieldSync the way I've always done it before the update as follows.
1. Opening the QFieldCloud Projects Overview
2. Click "Create New Project"
3. Select "Create New Project: Convert currently open project to cloud project (recommended)" and click "Next"
4. Sssign it to the correct organization in the drop-down list.
5. Browse and select the local mirror directory (an empty folder within my project folder)
6. Click 'OK' on the pop-up dialog: "The entered path does not contain a QGIS project file yet. You can always add one later." (Clicking 'Create' used to make a new project file in the local mirror directory, so this was always fine.)
7. Click 'Create'

This is the exact same as before the update, only now get this error

2024-08-13T19:14:20     CRITICAL    The project could not be converted into the export directory.

**Comment by SeqLaz** [comment]
Hi @georgiaslim,

I did a test using QFieldSync v4.10.1, and it worked perfectly for me. As a recommendation, use the default folder suggested by QFieldSync usually ../{user}/QField/cloud/{Project name}/, to avoid conflicts.

[Test Conversion error with newest QFieldSync update 001.pdf](https://github.com/user-attachments/files/16608646/Test.Conversion.error.with.newest.QFieldSync.update.001.pdf)

**Comment by georgiaslim** [comment]
@SeqLaz thank you. I did as you recommended, but it did not solve the issue. 
Here's what it's running on:
![image](https://github.com/user-attachments/assets/a2c62a5a-3845-4158-b5f7-60e601a6816d)

**Comment by HBarrau** [comment]
I got the same issue. On my other desktop I did not run the update so used version 4.9.1 from QFIELD sync and that one is working fine for me. Looks like version 4.10.1 has an issue

**Comment by nirvn** [comment]
I can't replicate this, tried converting two projects (one if the preferred path, one as a subdirectory of the project I was converting).

We'll probably need a small sample project that fails when converting to look into this some more.

**Comment by grosbous-web** [comment]
Hi, I get exactly the same error message after updating QFieldSync to 4.10.1 today. Is it possible to convert to version 4.9.1 that was working fine?

**Comment by m-kuhn** [comment]
Old versions can be downloaded from [the release page](https://github.com/opengisch/qfieldsync/releases) and installed as zip.

Meanwhile we would greatly appreciate any further insights that may help to reproduce the problem.

**Comment by HBarrau** [comment]
Goodmorning Matthias,

Today I have some time. What can I do to help you to reproduce the problem?

Greetings


Henri Barrau
Assistent Deskundige Opsporen Ontplofbare Oorlogsresten
+31(0) 6 51 12 54 55


        +31 (0) 71 402 85 86
Noordwijk
        ***@***.***
        www.idds.nl
        IDDS Explosieven BV   
KvK20139114
Email disclaimer
Van: Matthias Kuhn ***@***.***>
Verzonden: Sunday, August 18, 2024 1:02 PM
Aan: opengisch/qfieldsync ***@***.***>
CC: Henri Barrau ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [opengisch/qfieldsync] Conversion error with newest QFieldSync update (Issue #604)

U ontvangt niet vaak e-mail van ***@***.******@***.***>. Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Old versions can be downloaded from the release page<https://github.com/opengisch/qfieldsync/releases> and installed as zip.

Meanwhile we would greatly appreciate any further insights that may help to reproduce the problem.

**Comment by nirvn** [comment]
@HBarrau , what we'd need is a small sample project that fails to convert to cloud project (as is described in this issue).

**Comment by HBarrau** [comment]
Ok, I will finish my current project work and will sent a small project to you. Same mailing?

Met vriendelijke groet,

Henri Barrau
Assistent Deskundige Opsporen Ontplofbare Oorlogsresten
+31(0) 6 51 12 54 55


        +31 (0) 71 402 85 86
Noordwijk
        ***@***.***
        www.idds.nl
        IDDS Explosieven BV   
KvK20139114
Email disclaimer
Van: Mathieu Pellerin ***@***.***>
Verzonden: Tuesday, August 20, 2024 9:42 AM
Aan: opengisch/qfieldsync ***@***.***>
CC: Henri Barrau ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [opengisch/qfieldsync] Conversion error with newest QFieldSync update (Issue #604)

U ontvangt niet vaak e-mail van ***@***.*** Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

@HBarrau<https://github.com/HBarrau> , what we'd need is a small sample project that fails to convert to cloud project (as is described in this issue).

**Comment by fan32111** [comment]
Hello 
I have the same issue and tested same project on other pc with qgis version 3.28.15 and works fine.
I assume it's a qgis LTR version problem

**Comment by HBarrau** [comment]
I have a project for you. Just tested it and still the same error. Where can I sent it to?

**Comment by nirvn** [comment]
@HBarrau , mathieu@opengis.ch

**Comment by HBarrau** [comment]
Thats great. Thanks for the feedback
