### ISSUE TITLE
QFieldSync and Filters

### ISSUE THREAD

**Issue by saemiw** [opengisch/qfieldsync#63]
I have QGIS project with a layer that has many points in it and a timestamp as an attribute. I filter this layer with the timestamp so QGIS only shows newer data. When I use this layer on QField (transfer by copy'n' paste) everything works fine. BUT if i set this layer offline with QField Sync and create a new point. The point is not synchronised back to QGIS but lost (without error). 

Does this make sense to the developers? Obviously at the moment layers should not be filtered when used in combination with qfieldsync because will lose data.

I use QGIS2.18.17, QField 0.10.9 and QFieldSync 1.1.2

**Comment by m-kuhn** [comment]
I mus admit, I never tried that.
This is almost certainly a bug in the QGIS offline copy code and not in the plugin.

**Comment by saemiw** [comment]
This issue can be closed. Using filters in combination with QFieldSync works on QGIS 3.4.4, QField 1.0.0-rc3 and qfieldsync 3.1.1. 

It probably already worked earlier but was masked by another issue (https://github.com/opengisch/QField/issues/447) which affected the project I tested with on 25.9.2018

**Comment by m-kuhn** [comment]
Thanks for the feedback @saemiw !
