### ISSUE TITLE
OSerror: [WinError 123] QField-Export doesn't work

### ISSUE THREAD

**Issue by megis-at** [opengisch/qfieldsync#630]
[Python-Error.log](https://github.com/user-attachments/files/18048689/Python-Error.log)
Since the last update, packaging in QField no longer works. I get this error message:

OSError: [WinError 123] Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch: 'C:\\temp\\Nenzing\\Gewerke\\Kanal\\GIS\\Kanal.gpkg|layername=KaBauwerkPunkt|subset="Kanalart" = \'KS\' AND "Betreiber" = \'Marktgemeinde Nenzing\''

I am using the latest version 3.12 of QField, QGIS 3.28 / 3.34, Windows 11 23H2

Any idea? Best regards
Enrico

[Project.zip](https://github.com/user-attachments/files/18048694/Project.zip)

**Comment by suricactus** [comment]
Can you provide a test project and translation to the error message you experience to increase the probability of finding an answer?

**Comment by m-kuhn** [comment]
A complete stack trace would be helpful, probably visible from the qgis message log.

**Comment by megis-at** [comment]
> Can you provide a test project and translation to the error message you experience to increase the probability of finding an answer?

I did an Upload the error.log, thx

**Comment by megis-at** [comment]
> A complete stack trace would be helpful, probably visible from the qgis message log.

I did an Upload the error.log, thx

**Comment by megis-at** [comment]
Release 4.11 work's well without problems

**Comment by megis-at** [comment]
@m-kuhn thx a lot. You closed the ticket. This means in future releases the error will be fixed?
Best regards - Enrico

**Comment by m-kuhn** [comment]
Hi @megis-at this should be fixed thanks to @suricactus who fixed it.
A new release should be out soon.
Thanks for the high quality report and the responsiveness.

**Comment by megis-at** [comment]
Hello Matthias,
I would like to thank you for the quick response and processing of my e-mail.
Have a nice Sunday!
Best regards
Enrico


Von: Matthias Kuhn ***@***.***>
Gesendet: Sonntag, 8. Dezember 2024 09:02
An: opengisch/qfieldsync ***@***.***>
Cc: Enrico Mahl ***@***.***>; Mention ***@***.***>
Betreff: Re: [opengisch/qfieldsync] OSerror: [WinError 123] QField-Export doesn't work (Issue #630)


Hi @megis-at<https://github.com/megis-at> this should be fixed thanks to @suricactus<https://github.com/suricactus> who fixed it.
A new release should be out soon.
Thanks for the high quality report and the responsiveness.

**Comment by suricactus** [comment]
@megis-at can you test the new https://github.com/opengisch/qfieldsync/releases/tag/v4.12.1 version when it reaches QGIS plugins. This should most probably fix your issue.

**Comment by megis-at** [comment]
Ivan,
yes, the extension is now working properly again. Many thanks for the prompt resolution of the problem.
Best regards
Enrico

Von: Ivan Ivanov ***@***.***>
Gesendet: Sonntag, 8. Dezember 2024 18:27
An: opengisch/qfieldsync ***@***.***>
Cc: Enrico Mahl ***@***.***>; Mention ***@***.***>
Betreff: Re: [opengisch/qfieldsync] OSerror: [WinError 123] QField-Export doesn't work (Issue #630)


@megis-at<https://github.com/megis-at> can you test the new https://github.com/opengisch/qfieldsync/releases/tag/v4.12.1 version when it reaches QGIS plugins. This should most probably fix your issue.
