### ISSUE TITLE
Cannot usse decimal places on MapUnits/Pixel

### ISSUE THREAD

**Issue by signedav** [opengisch/qfieldsync#65]
On 2.18 Plugin it's not possible to use decimal places (0.1 etc.) as MapUnits/Pixel on creating base map.
There comes an error:
```
warning:/home/david/.qgis2/python/plugins/OSMEditorRemoteControl/plugin.py:23: DeprecationWarning: QgsMapCanvas.mapRenderer() is deprecated
			  extent = self.iface.mapCanvas().mapRenderer().extent()
			
			traceback:  File "/home/david/.qgis2/python/plugins/OSMEditorRemoteControl/plugin.py", line 32, in changeStatus
			    extent = self.getLonLatExtent()
			
```
This need to be another type probably that allows decimal places.

**Comment by signedav** [comment]
Is this in 3.0 solved already? @marioba You know something about it?

**Comment by marioba** [comment]
Sorry, I don't know.

**Comment by m-kuhn** [comment]
It's the core rasterize algorithm done in Nodebo, I think it's fixed there.
