### ISSUE TITLE
 QGIS 3?

### ISSUE THREAD

**Issue by Alancowlishaw** [opengisch/qfieldsync#66]
Can you tell me if qfieldsync will be migrated to QGIS 3?

When I try to install using the zip file I get the error:

Couldn't load plugin 'qfieldsync' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'processing.core.AlgorithmProvider' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/alan.cowlishaw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\__init__.py", line 70, in classFactory
    from qfieldsync.qfield_sync import QFieldSync
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/alan.cowlishaw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\qfield_sync.py", line 54, in 
    from .processing.provider import QFieldProcessingProvider
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/alan.cowlishaw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\processing\provider.py", line 22, in 
    from processing.core.AlgorithmProvider import AlgorithmProvider
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'processing.core.AlgorithmProvider'

Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.0.0-Girona Girona, 001c80b0c3 

Python Path:
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python
C:/Users/alan.cowlishaw/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/alan.cowlishaw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.0\bin\python36.zip
C:\PROGRA~1\QGIS3~1.0\apps\Python36\DLLs
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib
C:\Program Files\QGIS 3.0\bin
C:\PROGRA~1\QGIS3~1.0\apps\Python36
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages
C:/Users/alan.cowlishaw/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by m-kuhn** [comment]
You might be lucky be extracting this file https://github.com/opengisch/qfieldsync/archive/qgis3.zip and copying the `qfieldsync` folder within to your plugin folder.
Feedback very welcome!

**Comment by Alancowlishaw** [comment]
Thanks, 

I wasn't able to copy the folder into the plugins folder because I don't have administrative access (it's on my work computer), so I tried the "install from zip" function and got the following error message (I will try it on my home machine tonight):

An error occurred during execution of following code:
pyplugin_installer.instance().installFromZipFile(r'C:\Users\alan.cowlishaw\Downloads\qfieldsync-qgis3.zip')


Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
AttributeError: module 'qfieldsync-qgis3' has no attribute 'classFactory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "", line 1, in 
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\pyplugin_installer\installer.py", line 586, in installFromZipFile
    if startPlugin(pluginName):
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 338, in startPlugin
    _unloadPluginModules(packageName)
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 405, in _unloadPluginModules
    mods = _plugin_modules[packageName]
KeyError: 'qfieldsync-qgis3'


Python version:
3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]

QGIS version:
3.0.0-Girona 'Girona', 001c80b0c3

Python path:
['C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python', 'C:/Users/alan.cowlishaw/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'C:/Users/alan.cowlishaw/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins', 'C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python/plugins', 'C:\\Program Files\\QGIS 3.0\\bin\\python36.zip', 'C:\\PROGRA~1\\QGIS3~1.0\\apps\\Python36\\DLLs', 'C:\\PROGRA~1\\QGIS3~1.0\\apps\\Python36\\lib', 'C:\\Program Files\\QGIS 3.0\\bin', 'C:\\PROGRA~1\\QGIS3~1.0\\apps\\Python36', 'C:\\PROGRA~1\\QGIS3~1.0\\apps\\Python36\\lib\\site-packages', 'C:/Users/alan.cowlishaw/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python']

**Comment by m-kuhn** [comment]
The *install from zip* functionality won't work with this zip (we have to preprocess that a bit...).

Open your [user profile folder](https://gis.stackexchange.com/a/274374/9839) and copy it into the `python/plugins` subfolder.

**Comment by m-kuhn** [comment]
Thanks for the feedback, I just pushed an update, can you try again?

**Comment by soester** [comment]
same link to download? or v1.1.3 in releases?

**Comment by m-kuhn** [comment]
same link to download (it will always return the most recent qgis 3 version).

**Comment by soester** [comment]
no more python error :)

but: not all the layers get exported

local qgis file
---

1 point layer (postgres table)
1 point layer (postgres view)
1 polygon layer (postgres table)
several non spatial tables / valuelists (postgres tables)
tif orthophoto


in qgis qfield export file (also in sqlite-db)
---
point layers are lost
polygon, non spatial table and tif get exported

**Comment by soester** [comment]
generating offline project (core plugin) from the same file is throwing the following errors:
```
2018-04-13T08:44:43	WARNING	Offline Editing Plugin : messstelle_erfassungsdatum: Unknown data type QDateTime. Not using type affinity for the field.
2018-04-13T08:44:43	WARNING	Offline Editing Plugin : messung_datumzeit: Unknown data type QDateTime. Not using type affinity for the field.
2018-04-13T08:44:43	WARNING	Offline Editing Plugin : messung_in_hochrechnung: Unknown data type bool. Not using type affinity for the field.
2018-04-13T08:44:43	WARNING	Offline Editing Plugin : geo_gnss_antenna_heigth_corr: Unknown data type bool. Not using type affinity for the field.
2018-04-13T08:44:43	WARNING	Offline Editing Plugin : QGIS wkbType 1001 not supported
```
these warnings concern the layers not getting exported by qfieldsync.

the datatypes not supported are very important (eg. datetime, bool...)

Is it possible to fix this?

**Comment by soester** [comment]
This would also solve issues with datetime and so on?

**Comment by Alancowlishaw** [comment]
Hi, finally got round to applying your suggestions, it works fine now on my personal machine, I will have to speak to IT at work to get administrative access, I'll let you know how I get on.

Regards, Alan.

**Comment by m-kuhn** [comment]
Postgres know "datetime" etc. types, sqlite (and therefore spatialite and geopackage) does not know these types. So they will be converted to strings in the offline project.
In short: these warnings are expected and the best we can do is to hide them. Unless of course you are actually expecting real issues with datetime and so on, then we'll need to have a look.

**Comment by Delawen** [comment]
I can't install the zip file provided on the latest qGIS available on Debian:

> An error occurred during execution of following code:
> pyplugin_installer.instance().installFromZipFile(r'/tmp/qfieldsync-qgis3.zip')
> 
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 336, in startPlugin
>     plugins[packageName] = package.classFactory(iface)
> AttributeError: module 'qfieldsync-qgis3' has no attribute 'classFactory'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "", line 1, in 
>   File "/usr/share/qgis/python/pyplugin_installer/installer.py", line 586, in installFromZipFile
>     if startPlugin(pluginName):
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 338, in startPlugin
>     _unloadPluginModules(packageName)
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 405, in _unloadPluginModules
>     mods = _plugin_modules[packageName]
> KeyError: 'qfieldsync-qgis3'
> 
> 
> Python version:
> 3.5.3 (default, Jan 19 2017, 14:11:04) 
> [GCC 6.3.0 20170118]
> 
> QGIS version:
> 3.0.1-Girona 'Girona', a86bec2
> 
> Python path:
> ['/usr/share/qgis/python', '/home/delawen/.local/share/QGIS/QGIS3/profiles/default/python', '/home/delawen/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages', '/home/delawen/.local/share/QGIS/QGIS3/profiles/default/python', '/home/delawen/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/ext-libs']

**Comment by Delawen** [comment]
Ah, sorry, was trying the "install from zip". My fault. Leaving it there anyway in case someone else has a similar error :)

**Comment by m-kuhn** [comment]
What's the general opinion in here, are we ready for a release?

**Comment by soester** [comment]
So far (for QGIS 2.18) layers with 3d-Geometries were exported and converted to 2d. Now there is no export. Is QGIS3 more strict in these things?

We would be happy to support/fund improvements for 3d-Geometries in offline editing QGIS core...

**Comment by m-kuhn** [comment]
@soester thanks for the support, support for 3D has been introduced as of QGIS 3.2 (and current nightly builds of 3.1).

Given how quiet it is in here regarding issues on QGIS 3, I assume a release should not be too far away.

**Comment by m-kuhn** [comment]
According to #72 we are not ready yet for a stable release.
