### ISSUE TITLE
Relative project creation not working?

### ISSUE THREAD

**Issue by mandsch** [opengisch/qfieldsync#67]
In my QGIS (2.18.16) project, created with relative paths, when I use the QFieldSync plugin (1.1.3) to package it for copying to my mobile device, in the newly created "projectname_qfield.qgs" file the relative paths are replaced by absolute paths. So in QField the project cannot find the layers.

**Comment by mandsch** [comment]
Sorry, I just realised that this is only part of the problem. My vector data is stored in one spatiallite database (with several layers). Within QFieldSync properties I don't get the option to copy this file to the export directory, as it happens, e.g. with shapefiles. Is this intended behaviour?

The problem above remains, but might be resolved if the copying would happen.

Thx, Michael

**Comment by mandsch** [comment]
Ok, I guess the copy option is not shown because the database is not evaluated as a file in layer.py is_file(). Because layer.source() carries the layername=... string and is thus not detected as a file by os.path.isfile.

**Comment by m-kuhn** [comment]
There are two approaches to add a spatialite file: the native spatialite provider or ogr. Which one are you using (drag and drop from explorer uses ogr)? 

Since you are already investigating code, if you have a solution to that, pull request and patches will be happily accepted.

**Comment by mandsch** [comment]
The ogr provider is used, through qgis browser. I'll test with the other provider.

**Comment by mandsch** [comment]
Using the native spatiallite provider it works. Good to know. Thx.
