### ISSUE TITLE
GENERAL

### ISSUE THREAD

**Issue by JAVIERSIG** [opengisch/qfieldsync#69]
Hello; I have some doubts about qfield, because it does not work well and I do not know why; I am using version 2.18.19 of Qgis
1.- To be able to edit the layers (shp) from the mobile, as I have to put them in the configuration of qfield ?; copy, copy if missing, offline editing, remove.?
I have tried all of them and it always tells me that there are read failures of the layer in the mobile.
Has something to do with the android version ?, is 6.0.1 (I do not think so, no?)

On some occasion, he has not given me any fault; then when I try to synchronize, I do not load the changes made.

2.-Another topic:
I have put a photo field in the bbdd of the shp,. Where are stored in the mobile and as a field of qfield? Nor does it synchronize me in any way; or this photo option, I have to import after and from another plugin?

Thank you very much everyone for your enormous work

**Comment by m-kuhn** [comment]
Please redirect those questions to the [support channels](http://www.qfield.org/docs/development/index.html#support).

If you think the "read failures" are a bug, please open a detailed description for this problem in here with logs, screenshots, steps to reproduce and previous attempts to fix this.

Thank you
