### ISSUE TITLE
settings dialog disable ADB and Network for now

### ISSUE THREAD

**Issue by mbernasocchi** [opengisch/QFieldSync#7]

**Comment by carolinux** [comment]
In the specs, it says that the settings should just be the default import folder and default export folder and the copy mode should be in the push dialog. Or would you like to have the Settings have a "preselected default copy mode". 

Network = Cloud? 
Out of these 4 tab widgets, only the manual mode works fully, so do you suggest I gray the others out?

http://imgur.com/nVjGjzT

**Comment by m-kuhn** [comment]
Something grayed out normally indicates that the user is able to fix something from his side to make it active.
Is the user able to make these tabs accessible?

**Comment by carolinux** [comment]
No, should I just hide them?

**Comment by carolinux** [comment]
here is what the settings look like, also:
http://imgur.com/ie6RdRZ

**Comment by carolinux** [comment]
tagging @mbernasocchi

**Comment by mbernasocchi** [comment]
@carolinux FYI, you can just drag and drop pictures into github issues

**Comment by mbernasocchi** [comment]
if you can hide them easily, please hide them, if not no worries just disabled, as it is an alpha I'm not that picky for now.
