### ISSUE TITLE
Photo and cloud

### ISSUE THREAD

**Issue by JAVIERSIG** [opengisch/qfieldsync#70]
Hello;
I wanted to make two suggestions.
1.-Is it possible that the photos taken from qfield, could be stored in the same route as the project and could be synchronized also?
2.-It is possible that the whole package placed on the mobile, could be installed in the cloud, onedrive, dropbox, etc. and so that several users could interact. As well as in local?

Thank you very much

**Comment by m-kuhn** [comment]
This should both be possible already, where are you running into troubles?

**Comment by JAVIERSIG** [comment]
Many thanks for your help and answer Matthias; I was just watching a video on YouTube again (https://www.youtube.com/watch?v=WevRTiLe7ts&t=967s); about this theme.
The part of photos I have already been able to solve; It did not define the layers of the project well.
But I have other doubts that I can not fix.
(I will put them in another post-issue, so as not to mix it with this one)

However, about this, how could I synchronize it in the cloud? Could several users work on the same project?
When I try to open the project, the qfieldsync's own file browser does not let me go beyond those that are hosted on the mobile / tablet.
Pointing to an onedrive for example does not leave me.
I'm probably doing something wrong.

On the other question, the base map, I put it in the next post.

Thank you

**Comment by m-kuhn** [comment]
Hi @JAVIERSIG please note that this is not a support forum, but an issue tracker for bugs and feature requests.

The questions are very valid but should be redirected to one of the [various support channels](http://www.qfield.org/docs/development/index.html#support).
