### ISSUE TITLE
Add support for more snapping configuration

### ISSUE THREAD

**Issue by xyago** [opengisch/qfieldsync#75]
In my project offline i set snapping options: All layer visible, snap to vertex, tolerance 10 maps units (it works in qgis).
In Qfield don´t work with point entities.

I don´t know if i´m doing something wrong.

Thanks!

**Comment by xyago** [comment]
Only works when i set snap to vertex and segment, and all visible layer.

**Comment by suricactus** [comment]
@xyago is this still an issue?
