### ISSUE TITLE
QGIS: Profile Tool Plugin Installation Error

### ISSUE THREAD

**Issue by saurabhdkulkarni** [opengisch/qfieldsync#76]
Can anyone please help out? Thank you!

Error Details: 

Couldn't load plugin 'profiletool' due to an error when calling its classFactory() method 

AttributeError: module 'profiletool' has no attribute 'classFactory' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
AttributeError: module 'profiletool' has no attribute 'classFactory'

Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.0.3-Girona Girona, 8a899c8758 

Python Path:
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python
C:/Users/sakulkar/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/sakulkar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.0\bin\python36.zip
C:\PROGRA~1\QGIS3~1.0\apps\Python36\DLLs
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib
C:\Program Files\QGIS 3.0\bin
C:\PROGRA~1\QGIS3~1.0\apps\Python36
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\Pythonwin
C:/Users/sakulkar/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by m-kuhn** [comment]
Please post this to the profiletool issue tracker https://github.com/PANOimagen/profiletool/issues
