### ISSUE TITLE
"Project configuration" "Unsupported layers"

### ISSUE THREAD

**Issue by xyago** [opengisch/qfieldsync#78]
In the "Project configuration" option i obtein an advice: "Unsupported layers". Is an postgis layer with EPST 3857. Any idea what it is?
Thanks!

**Comment by m-kuhn** [comment]
What geometry type is it?

**Comment by xyago** [comment]
Points, and linestrings: there is tables without geometry in the project but i removed them.

**Comment by m-kuhn** [comment]
Can you add a screenshot of the layer properties -> information dialog?

**Comment by xyago** [comment]
I don´t have 'information dialog', you mean Properties / General?

**Comment by m-kuhn** [comment]
Right click on the failing layer -> Properties -> Topmost tab

**Comment by xyago** [comment]
![1](https://user-images.githubusercontent.com/38865790/42107679-8660bef8-7bd8-11e8-988b-274004cf8f9a.jpg)
![2](https://user-images.githubusercontent.com/38865790/42107844-11c37f1c-7bd9-11e8-927d-f8cb7cdd4b75.jpg)
![4](https://user-images.githubusercontent.com/38865790/42107849-15050fd8-7bd9-11e8-88c1-a87bc9210644.jpg)

**Comment by mirandadam** [comment]
Same issue here.

**Comment by mirandadam** [comment]
The "package for qfield" button is also grayed out, both in the toolbar and in the "plugins"->"QFieldSync" submenu.

**Comment by koenigherford** [comment]
Same issue here. 

Running QGIS 3.8.3.  QField-Update from today.

Test data can be shared if you like. 
Small layer with just 1 polygon. 
Tested with different projections / processing->geometry repair / formats (postgis/gpkg/shp) ... but same result.

Data-Properties:

Name | test4
-- | --
Pfad | C:\temp\test4.shp
Quelle | C:\temp\test4.shp\|layername=test4
Speicher | ESRI Shapefile
Kommentar |  
Kodierung | UTF-8
Geometrie | Polygon (MultiPolygon)
KBS | EPSG:3857 - WGS 84 / Pseudo-Mercator - Projiziert
Ausdehnung | 952566.2887555477209389,6810594.0904322182759643 : 974557.4591719328891486,6830911.8546357993036509
Einheit | Meter
Objektanzahl | 1


![grafik](https://user-images.githubusercontent.com/28433436/79202058-4db27c80-7e39-11ea-8fc6-6d701a36e19d.png)

**Comment by m-kuhn** [comment]
Is it just this string or is there any issue functionality wise?

**Comment by koenigherford** [comment]
Hi Mathias

I missed several layers in a project created by qfieldsync. Some layers were exported as expected.

I tried to narrow down the reason and deleted some layers before export to reduce the project at maximum but preserving the issue to make it easy for you to repoduce  the issue.

Made a new project with this data. Same issue. So it seems not to be a issue within the project-settings.

Sample-data is attached.

Mit freundlichen Grüßen

Ralf König

[cid:image001.gif@01D61332.FCFE38E0]
Von: Matthias Kuhn <notifications@github.com>
Gesendet: Mittwoch, 15. April 2020 14:33
An: opengisch/qfieldsync <qfieldsync@noreply.github.com>
Cc: König, Ralf (Hansestadt Herford) <Ralf.Koenig@Herford.de>; Comment <comment@noreply.github.com>
Betreff: Re: [opengisch/qfieldsync] "Project configuration" "Unsupported layers" (#78)


Is it just this string or is there any issue functionality wise?

**Comment by koenigherford** [comment]
Made some additional tests with the project:

Some layers were not exported form the original-project (see comparison below (1. export))
_red dot behind layer (first export): no export done 
green dot behind layer (first export) : export done_

For example the layer "stadtgrenze herford" was not exported (geometry from some days before) as you can see below. But in a reduced project (contains just this one layer) the layer is still exported as expected - although the (only) layer is marked as "unsupported" in qfield-project-export-settings.
So it seems to be not a problem with the data/geometry itself, but with other reasons skipping some layers during the export-loop.

I copied this single layer 35 times and pasted it into the layertree - and the export-result was as expected. So it seems not to be a reason of number of layers.
From first view  (into the qgs-file too) there seems not to be a pattern skipping some layers. 

After that I reduced the content of the original project further. Layers, which were exported before, were skipped now (i.e. layer "kleingaerten_flaechen_standard_symbologie" | "hausnummern")
_light red dot behind layer  (second export (from reduced project)): no export done 
light green dot behind layer (second export (from reduced project)): export done_

So it seems not to a reason in the layer-definition in project file.

![grafik](https://user-images.githubusercontent.com/28433436/79744141-26aaed80-8306-11ea-9016-002b3cf58cf8.png)

After that I copied all layers of the reduced project and pasted them into the same project (below blue line).
_orange dot behind layer (third export (from reduced project)): no export done 
blue dot behind layer (third export (from reduced project)): export done_

Surprisingly one of the layers (green arrow (abdeckungslayer_stadtgrenze)) - which was not exported in all exports before - was now exported as expected .

![grafik](https://user-images.githubusercontent.com/28433436/79746648-9fac4400-830a-11ea-848e-4ad4213c784a.png)

I've got no idea what pattern underlies this behaviour, but maybe it helps you narrowing down the issue during export-process.

**Comment by m-kuhn** [comment]
Thanks for this information.
We will be happy to look into this when time allows. For your information, we are currently overly busy with customer projects, so if you need a timely fix for this we would suggest to open a support issue.

**Comment by koenigherford** [comment]
..seems to be a problem with older QGIS-versions. Made an update to 3.12.2.
Layers were no longer lost.

**Comment by m-kuhn** [comment]
Thanks for the feedback !
So this can be closed?

**Comment by koenigherford** [comment]
"Unsupported layers"-warning is still there. 
Further consequences for the exported project / data are unknown for now. 
Were are testing, if something is missing / not running on hidden places.

**Comment by m-kuhn** [comment]
Keep us posted.
Also interesting, is there anything shown below / next to the title unsupported layers?
