### ISSUE TITLE
Basemap performance

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/qfieldsync#79]
Geopackage raster is much faster with pyramids. Can be created manually already.

**Comment by giedrioks26** [comment]
Maybe it is easy to make an automatic pyramid on the plugin? Like here https://www.qfield.org/docs/project-management/dataformat.html#use-geopackage
As I understand it, the plugin can do this action now `gdal_translate --config OGR_SQLITE_SYNCHRONOUS OFF -co  APPEND_SUBDATASET=YES -co TILE_FORMAT=PNG_JPEG -a_srs EPSG:21781 -of GPKG raster.tif raster.gpkg`

The plugin is missing this action `gdaladdo --config OGR_SQLITE_SYNCHRONOUS OFF -r AVERAGE raster.gpkg 2 4 8 16 32 64 128 256`

**Comment by m-kuhn** [comment]
Exactly, that would be the missing piece

**Comment by suricactus** [comment]
@m-kuhn should we prefer this or #283 ?

**Comment by m-kuhn** [comment]
#283 is preferable
