### ISSUE TITLE
 push proj dialog if we detect live layers we need to ask the user what he wants to do.

### ISSUE THREAD

**Issue by mbernasocchi** [opengisch/QFieldSync#8]

**Comment by carolinux** [comment]
@mbernasocchi I assume by 'live' and 'remote' in the specs here: http://imgur.com/h22VhLS
are the same thing.
If so, this should already work. I will demonstrate shortly.

**Comment by carolinux** [comment]
@mbernasocchi So, if there's a postgres layer present, this is what appears when I press "Push".
http://imgur.com/W4IOpKP

Question: If we are in hybrid mode, should I still offline convert the layer? (in addition to setting the hybrid flag, which I do). 

Another issue I noticed: The version of the offline plugin I have converts the postgres layer to sqlite, but manages to create "unknown geometry types" out of the features making the features invisible in the offline project. Maybe I have a buggy version of it installed, or my postgres layer wasn't explicit enough about the geometry type. Any input? @m-kuhn

**Comment by m-kuhn** [comment]
The plugin is shipped with QGIS and I did some changes for 2.16. But nothing related to what you mention here.
What geometry type is your database column?

**Comment by carolinux** [comment]
geom        | geometry(PointZ,25832)      |

**Comment by m-kuhn** [comment]
I guess `PointZ` resolves to `QGis::WKBPoint25D`.
Check the return of layer.wkbType() (https://github.com/qgis/QGIS/blob/master/src/core/qgsofflineediting.cpp#L530-L553)

I'd say check with a 2-dimensional point until there's a requirement for 3D points.

**Comment by carolinux** [comment]
Ok it works for plain points. :)

**Comment by mbernasocchi** [comment]
you can grey out hybrid mode for now as QField does not support it yet.
live and realtime is the same
