### ISSUE TITLE
Primarykey and export with qfieldsync

### ISSUE THREAD

**Issue by BeaSavoie** [opengisch/qfieldsync#80]
Help, please...
On our database on Postgres, we have defined primarykey on a text attribute. When we export to QField with QFieldsync, a spatialite database is created but there is no primary key defined. 
We want to see the primary key when we select an object in QField... 
How can we do ???
Thanks a lot.....

**Comment by VxTedxV** [comment]
Maybe an answer here ?
http://www.qfield.org/docs/en/project-management/vector-layers.html#display-expression
