### ISSUE TITLE
 QField Sync unable to add plugin

### ISSUE THREAD

**Issue by ISPLBB** [opengisch/qfieldsync#81]
Hi,  Been trying to add Qfieldsync to my QGIS and keep getting the following error - 
the plugin is broken.  Python said - cannot import name QtWidgets. I am getting the same error message for QGIS 2.18.14 and QGIS 2.18.19. Belinda

**Comment by m-kuhn** [comment]
Please uninstall the qgis2compat plugin.

**Comment by ISPLBB** [comment]
Tried you recommendation and received the following error after re adding QField Sync.
The pluggin is broke,  Python said: The plugin QField Sync requires the qgis2compat plugin.  Please install.

Any other suggestions.

**Comment by m-kuhn** [comment]
Update the QFieldSync plugin to the most recent version

**Comment by ISPLBB** [comment]
I am trying to install the plugin from the QGIS plugin repository.  Which I believe is the latest version.

**Comment by m-kuhn** [comment]
Can you check the version number in the plugin manager?
Here is the changelog with information about when qgis2compat has been dropped as dependency: http://plugins.qgis.org/plugins/qfieldsync/version/1.1.3/

With QGIS 2 manual installation is possible but more difficult than with QGIS 3, follow [the instructions for manual installation](https://gis.stackexchange.com/a/127791) and [download from the plugin page](http://plugins.qgis.org/plugins/qfieldsync/version/1.1.3/).

**Comment by ISPLBB** [comment]
It appears another plugin was causing the issue.

Regards

B

**Comment by m-kuhn** [comment]
Cool, closing this then :)
