### ISSUE TITLE
Accents incompatibility

### ISSUE THREAD

**Issue by Emic37** [opengisch/qfieldsync#84]
After completing my forms using Qfield with french words with accents, I synchronize my portable offline project using Qfield sync. 
All works well but all accents of my imported modifications were substituted by Ã© string. 
Any idea to correct that ?

**Comment by m-kuhn** [comment]
Looks like a character encoding issue. I would recommend to get some support hours, so we can look into that together.

**Comment by VxTedxV** [comment]
https://github.com/opengisch/QField/issues/92

**Comment by suricactus** [comment]
Is this still an issue?
