### ISSUE TITLE
tif files copied without companion files

### ISSUE THREAD

**Issue by damstep** [opengisch/qfieldsync#86]
Hi.
Thanks very much for the work you are doing on this, i can see it will be very useful, once a bit more compatibility is built in. to that end I wanted to point out an issue that I am having.
I have exported a project with a  tif (uncompressed) and a couple of ers files.
when I export the project with qconsolidate (qgis2.18) the tifs work fine and it converts the ers fiels to tif with tfw files.
doing the export with qfield sync comes up with an error that neither of these could be opened. 
it looks like qfieldsync isnt copying the tfw file along with the tif so qfield cant georeference it, and it it is retaining the ers files format?
what are the chances that qfield can emulate the qconsolidate behaviour?

**Comment by damstep** [comment]
wouldnt say that I am confident, but have played around a bit,
will try and give it a go. i think the same is the case with ers files.

damien stephens

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by damstep** [comment]
Hi Matthias.
I have made the changes for tifs, jpg, png, tab and added a few to .sho as well. I have made the commits under damstep, but am not overly confident.
I would appreciate any feedback.
Thanks

Damien stephens
Sent from mobile

-------- Original Message --------

**Comment by m-kuhn** [comment]
I am sorry, I cannot find where you did your changes.

Can you find a link to the branch where you did this change and create a new pull request.

Or go to https://github.com/opengisch/qfieldsync/blob/master/qfieldsync/core/layer.py#L13-L17 and click the edit button on top, make the changes, and then confirm the commit and make a new pull request from there?

**Comment by damstep** [comment]
That's because I have no idea what I am doing!

Have created a pull request - I think

Damien stephens
Sent from mobile

-------- Original Message --------

**Comment by m-kuhn** [comment]
I can see a pull request was opened, but unfortunately there are no changes in there.
I would suggest to use the second way described above or contact us for a support contract so we can do it for you.

**Comment by damstep** [comment]
ok tried it via option 2.

damien stephens

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by suricactus** [comment]
This issue is about QGIS 2.18. Please open a new issue if this is still a problem.
