### ISSUE TITLE
Sync backend for WebDAV or Nextcloud?

### ISSUE THREAD

**Issue by poVoq** [opengisch/qfieldsync#88]
This looks like a very cool plugin together with qField, but without jumping through a lot of hoops it is very difficult to automate the syncing right now, especially if trying to do it in an multi-user environment (i.e. multiple users on qField add into a single qGIS instance).

Really awesome would be support for WebDAV (works well with Nextcloud), as that would allow using a quite easy to setup and use multi-user system with multiple Nextcoud clients easily syncing the data to a directory (just mark it as available offline).

There seem to be quite a few WebDAV client libraries for Python, so it should be relatively easy?
See for example (just based on recent updates): https://github.com/ezhov-evgeny/webdav-client-python-3

Of course a simple to click button to sync the changes back into qGIS would be great as well.

**Comment by m-kuhn** [comment]
More functionalities to sync would be really nice, anyone interested in pushing this forward, please contact us!

**Comment by suricactus** [comment]
QFieldCloud should be the right tool to resolve these issues. Check https://qfield.cloud
