### ISSUE TITLE
snapping options are lost

### ISSUE THREAD

**Issue by soester** [opengisch/qfieldsync#89]
When exporting to offline project snapping options (advanced) are lost.

*QGIS-Project*
<img width="659" alt="bildschirmfoto 2018-09-12 um 11 19 43" src="https://user-images.githubusercontent.com/28543978/45417917-97e2e300-b683-11e8-9fb2-75072c3c83e0.png">

*Offline-Project*
<img width="696" alt="bildschirmfoto 2018-09-12 um 11 20 17" src="https://user-images.githubusercontent.com/28543978/45417937-a0d3b480-b683-11e8-9e24-21e0992661e2.png">

QGIS 3.2.2, Qfieldsync 3.0.2

**Comment by signedav** [comment]
This issue happens with the advanced configuration per layer, right @soester ?

**Comment by soester** [comment]
@singedav yes, if a layer is ticked as sappable, in offlineproject it isnt anymore.

**Comment by soester** [comment]
@signedav this is also important because of this behavior in qfield:
https://github.com/opengisch/QField/issues/361

**Comment by signedav** [comment]
Thanks @soester

**Comment by saemiw** [comment]
I think this issue is solved yes? Everything works nicely with QGIS 3.4.12, QField 1.2.0 and QFieldSync 3.1.5. @signedav or @soester can you close the issue if you agree?

**Comment by signedav** [comment]
Yes. @soester So opengisch/QField#361 as well, right?

**Comment by soester** [comment]
yes @saemiw this is fixed. i'll close the issue.
@signedav opengisch/QField#361 is still the same. Snapping is also active when the feature is not visible.
