### ISSUE TITLE
"Show feature count"-setting lost

### ISSUE THREAD

**Issue by saemiw** [opengisch/qfieldsync#90]
I have a project in the .qgz-Format (Qgis 3.2) when I use qfieldsync it creates a .qgs offline project that works perfectly well. But the setting to show the number of features per layer in the layers panel is lost. It used to work at least for .qgs to .qgs in Qgis 2.18

**Comment by saemiw** [comment]
More precision on this issue: It is not relevant whether I use .qgs or .qgz. The problem is only the use of QFieldSync that seems to remove the information whether or not I want to show the feature count.

**Comment by m-kuhn** [comment]
To be sure, is this only a QField issue? I.e. when setting the option manually in the offline project, it works fine in QField?

**Comment by saemiw** [comment]
> is this only a QField issue?

It is an issue of QField**Sync**. QGIS as well as QField do everything properly.


These situations work perfect:

- Activate feature count and copy qgs and data to qfield -> feature count is shown. 

- Activate feature count, use qfieldsync to set project and data offline, activate feature count in offline project manually, copy this modified project file and data to qfield -> feature count is shown

This situation doesn't work:
- Activate feature count, use qfieldsync to set project and data offline, copy this project file and data to qfield -> feature count is NOT shown - neither on qfield nor in qgis

**Comment by saemiw** [comment]
update: this is still a problem with qgis 3.4.4, qfield 1.0.0-rc3 and qfieldsync 3.1.1

**Comment by m-kuhn** [comment]
Implemented in 3.6, backport pending now

**Comment by saemiw** [comment]
works on 3.6.  - issue can be closed if you want...

**Comment by m-kuhn** [comment]
Thanks for the feedback. It will work on 3.4.6 too as soon as it's released.
