### ISSUE TITLE
QGIS-Project shown after synchronisation

### ISSUE THREAD

**Issue by saemiw** [opengisch/qfieldsync#92]
The synchronising process in a QGIS-QField field project has repeatedly caused some confusion with our users that are not too much informed about QField. I have the feeling it is also related to the following behaviour: When you open your QGIS-Project (lets call id motherproject) and from within that project you sync back your field data, you'd expect to see the new point inside the mother project. Instad QFieldSync opens some sort of temporary new qgis project. This is confusing. I propose that at the end of each synchronising process the mother project (where the they originally come from) should be opened. Is that possible - are there reasons why this should not be the case?

The following video show the confusing situations: https://youtu.be/Q7NSRjtNnss
From 00:04-00:07 the originally opend mother project (named "multilayer and edit") changes to "Untitled Project" and then to "multilayer and edit_qfield (offline)". In the final project basemaps disappear (because they are saved locally). In my proposition the original mother project would stay visible at all times and be updated with the newly syncronised data.

**Comment by saemiw** [comment]
I noticed that the lastest version of QFieldSync opens the "mother project" at the end of the synchronisation process. Great! However If some layers are removed they are also removed in the  mother project. We have for example very heavy basemaps. Users usually don't copy them from the tablet to the desktop computer but only copy the data (not the basemap). If synchronised now the basemap will be removed from the mother project.

I suggest (and if possible) that layers cannot be added or removed by qfield sync. Synchronisation should only affect data of existing layers. You know what I mean? Does anyone have another opinion/use case?

**Comment by suricactus** [comment]
QGIS really opens a temporary secondary project during sync/packaging, but the user cannot do much during that time. However,  the primary project is restored in the end and that temporary project is gone forever.
