### ISSUE TITLE
Synchronising pictures

### ISSUE THREAD

**Issue by saemiw** [opengisch/qfieldsync#93]
QFieldSync is currently "only" synchrnising gis-data but not pictures taken with the camera and stored in the DCIM folder. 
It would be nice if QFieldSync could be extendet to also synchronise the pictures coming from different tablets. Renaming is probably necessary to avoid overwriting of non-identical pictures that are named identically. 

Use case: 
I set a project offline copy it to 5 tablets. They go out collect pictures. In the evening they come back and I bring all the pictures taken during the day. QFieldSync copies all the files into the DCIM-folder on my local desktop computer (so that my mother-project can access all the pictures). For the field work the next day, all the tablets need to have all the pictures taken so far. So when putting my mother project offline again also all pictures need to be copied to the folder that is then copied manually to the 5 tablets.

**Comment by jescott2** [comment]
Sync of the QField DCIM folder would be useful. Now I drag&drop new pictures to the DCIM folder in the QGIS project_folder. I use this open Action to open the photos in Win 10 QGIS 3.8.2:
[% @project_folder %]\[%Image%]

**Comment by signedav** [comment]
This is merged and will be available in the next release
