### ISSUE TITLE
Offline editing does not work with non spatial tables

### ISSUE THREAD

**Issue by jonnyforestGIS** [opengisch/qfieldsync#95]
**Desktop SO:** Windows 7 64-bits
**QGIS Version:** QGIS 3.2.0 64-bits
**Qfield Version**: 0.11.9 - Lucendro

**Steps to produce the issue:**
1.º Create a QGIS project with a geopackage with geometry tables and non geometry tables;
2.º Export Project to a folder using QfieldSync in a folder;
3.º Copy to Android Device;
4.º Open Qfield and load the project. At this step, Qfield don't find the non geometry tables; 

**Workaround:**
Copy directly the folder of the QGIS project with the geopackage with a geopackage with geometry tables and non geometry tables and works fine.

Is this a known problem?

**Comment by suricactus** [comment]
This should be working by now. Whatismore QGIS 3.2 is no longer supported. If you are still experiencing the issue in a more recent QGIS 3.x / QFieldSync 3.x/ QFieldSync 4.xBETA, please file a new issue.
