### ISSUE TITLE
New field "fid" is added to offline package

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/qfieldsync#96]
Because geopackage is used, a new field "fid" is added (which is inevitable).
This field should be hidden in the offline attribute form.

@signedav is it sufficient to set the widget configuration for this field to hidden?

**Comment by signedav** [comment]
I will check that.

**Comment by vfonsecaz** [comment]
yes the new field "**fid**" sould be hidden by default!

Additionally in qgis 3.4.0 there's another problem in the output attribute table.
The first field after **fid** gets the value null, so all the other values are pushed one column forward...

In this example, "dicofre" column should have the value "011109",  "freguesia" should be "União de freguesias"....ans so on!

[https://imgur.com/N8oYxOu](url)

Updated to qgis 3.4.5 LTR and seems to be ok. Also tested in 3.6.0 with success

**Comment by saemiw** [comment]
update fid_1 is still apearing with geopackages and QGIS 3.4.12 and QField 1.2.0 and QFieldSync 3.1.3. It is not a very dramatic issue as one can easily use the drag'n'drop designer to create the form (which hides any unwanted fid_1 fields).

**Comment by AndeVandenberg** [comment]
> yes the new field "**fid**" sould be hidden by default!
> 
> Additionally in qgis 3.4.0 there's another problem in the output attribute table.
> The first field after **fid** gets the value null, so all the other values are pushed one column forward...
> 
> In this example, "dicofre" column should have the value "011109", "freguesia" should be "União de freguesias"....ans so on!
> 
> https://imgur.com/N8oYxOu
> 
> Updated to qgis 3.4.5 LTR and seems to be ok. Also tested in 3.6.0 with success

Would just like to add that I've ran into this issue with 3.4.2. Updating to the LTR has solved the problem.

**Comment by signedav** [comment]
So there only the issue left  that fid_1 is not null @saemiw ?

**Comment by jpnunn** [comment]
Seem to be getting this issue exactly (fid_1 is getting generated and is not hidden).  Using gpkg in QGIS 3.18.3 and  Qfield Sync 3.4.4  (and Qfield 1.10).  Would switching to spatialite fix this?

**Comment by suricactus** [comment]
hey, @jpnunn , can you try the experimental version of QFieldSync and confirm this is no longer the case?

**Comment by jpnunn** [comment]
Hi @suricactus thanks for looking at this so quickly. I installed the experimental version and all the layers within the gpkg still had been given the fid_1 field, however the fid_1 had now been hidden, so should not appear on the Qfield input form.  This will fix our issue.  Many thanks.

**Comment by suricactus** [comment]
For some deep technical details the `fid_1` is mandatory.

**Comment by jpnunn** [comment]
Just looking in to the move from Field Maps to QField. This instant fix is exactly why!  Should not be an issue with the fid_1 as long as it is hidden.

**Comment by AnomalousExploration** [comment]
Is it still neccesary for qfieldsync to still generate a second fid? I have a code that takes advantage of fid, and when it is packaged for export, qfieldsync generates a second id called 'fid_1' and my code no longer works properly. 

Thank-you!
Ellen

**Comment by suricactus** [comment]
it is `QgsOfflineEditing` that actually generates the second `fid` field. We cannot do much to mitigate this without changing some core parts of QFieldSync and QFieldCloud.
